### ISSUE TITLE
Residue & Segment slicing.  Residue.select_atoms?

### ISSUE THREAD

**Issue by richardjgowers** [MDAnalysis/mdanalysis#1163]
I'm going over the old tests in test_atomgroup and found some differences in behaviour between the old and new systems.  Because Residue and Segment used to be derived from AtomGroup, these could be sliced to give atoms.

```python
u = mda.Universe()

res = u.residues[0]

# Previously
res[2]  # would return second Atom in Residue

# Now have to go via atoms attribute
res.atoms[2]
```

This also applies to things like `__contains__`, should `atom in res` work?

Also, `select_atoms` now has to be called off either a Universe or AtomGroup object, but because it explicitly says `_atoms` in the method name, shouldn't this always work off any object? (ie with `SegmentGroup.select_atoms` it's obvious what is meant, so allow it?)

I'm in favour of changing these things back to how they used to work, but just checking this seems better with everyone else.

poking @dotsdl in particular

**Comment by kain88-de** [comment]
For me.

1. `res.atoms[2]` is better then the old way
2. `select_atoms` should be callable from any group object.

**Comment by orbeckst** [comment]
I agree with @kain88-de 👍

1. slicing a XGroup should give an X (this needs to be documented clearly in CHANGELOG and docs as something new! **It will break old code.**)
2. `select_atoms()` needs to work from anywhere

**Comment by mnmelo** [comment]
Another vote for @kain88-de's choice.

**Comment by dotsdl** [comment]
I'm in favor of @kain88-de's proposed approach as well. I don't think `Residue` and `Segment` objects should be sliceable, to keep things explicit and clean (not so many ways to do the same thing). Having `select_atoms` work from any group is fine; perhaps we should leave it off of `Residue` and `Segment` objects, though, since these technically aren't groups?

**Comment by orbeckst** [comment]
> since these technically aren't groups

"Technically" is not really important from a user's point of view. I liked Residue = group of atoms (and Segment = group of residues) because it makes sense semantically.

Could we have Residues and Segments *behave* like such groups?

**Comment by richardjgowers** [comment]
Yeah I think David is right about attribute access having to refer to the
Residue and never the atoms.

My question is with the special getitem and contains methods, isn't the
intent clear that we're trying to use the Residue as a group?

**Comment by orbeckst** [comment]
@dotsdl yes, if you could dig out that thread.

I would expect `Residue.charge` to be the total charge and `Residue.charges` an array of the charges of the constituents, i.e., the atoms. Similarly, `Segment.charges` should be charges per resdidue, at least that's what the Segment/Residue/Atom hierarchy means. And if this were true then slicing should again give lists of the elements, i.e., either residues or atoms.

If this is technically hard to do – fine, we have to figure out where to spend developer time – but from a semantic perspective it would be meaningful and unambiguous. I would argue that not having this behavior introduces some metaphor shear into the UI.

**Comment by dotsdl** [comment]
@orbeckst see [here for your own conclusion](https://github.com/MDAnalysis/mdanalysis/issues/703#issuecomment-190547898) and [here for some extended discussion](https://github.com/MDAnalysis/mdanalysis/issues/599#issuecomment-169495840).

My worry is that `Residue` objects will behave as `AtomGroup`s in some ways and not in others (and same for `Segment`s with regard to `ResidueGroup`s).

@richardjgowers those mechanisms were things I was resistant to adding back in, but they were [added back to maintain things that were present in the old system](https://github.com/MDAnalysis/mdanalysis/pull/698#issue-131903317). I don't like them, since I think they cause us metaphor shear as @orbeckst says.

**Comment by orbeckst** [comment]
@dotsdl : I agreed that `X.atoms` (and `X.residues`) is a semantically good way to access properties belonging to atoms and residues. 

I guess we had the discussion on `Segment` and `Residue` a long time ago https://github.com/MDAnalysis/mdanalysis/issues/599#issuecomment-169494122
> So in general, Residue and Segment only give information about the singular object, rather than the plural contents.

I'll stop flogging a dead horse ... (even though I am not convinced that it is ambiguous as to what should happen when referring downward: in my mind a `Residue` should behave like an `AtomGroup` and a `Segment` should behave like a `ResidueGroup`).

The hard line view would be that neither `Residue` nor `Segment` should be iterable or slicable (to be consistent with "Residue and Segment are 'singular objects'"), even though from an oo/semantic point of view `if atom in residue` would be nice to have. However, `if atom in residue.atoms` is perhaps even clearer so yes, fine, https://github.com/MDAnalysis/mdanalysis/issues/1163#issuecomment-272917750 the whole way:

1. no `res[:]`: `TypeError`
2. no `atom in res`: `TypeError`
3. have `Residue.select_atoms == Residue.atoms.select_atoms`

**Comment by richardjgowers** [comment]
Cool thanks for the quick consensus
