### ISSUE TITLE
Using ABCs in MDAnalysis

### ISSUE THREAD

**Issue by richardjgowers** [MDAnalysis/mdanalysis#1187]
So we've currently got a few "template" style classes, such as [Reader](https://github.com/MDAnalysis/mdanalysis/blob/develop/package/MDAnalysis/coordinates/base.py#L1160) [AnalysisBase](https://github.com/MDAnalysis/mdanalysis/blob/develop/package/MDAnalysis/analysis/base.py#L154) and [TopologyAttr](https://github.com/MDAnalysis/mdanalysis/blob/develop/package/MDAnalysis/core/topologyattrs.py#L110) which require you to define a method in them before they'll work.

We could start using the [abc](https://docs.python.org/2/library/abc.html) module to properly define them, most notably the [abstract method](https://docs.python.org/2/library/abc.html#abc.abstractmethod) decorator to denote what needs overriding in child classes.

Is it worth doing this?

ping @dotsdl in particular who likes design questions

**Comment by kain88-de** [comment]
It would definitely be useful for our abstract classes. That way we can define which methods are absolutely needed.

**Comment by jbarnoud** [comment]
I encountered abstract classes a few times, yet I still fail to see the benefit compared to explicit inheritance. Maybe just because I did not need them yet. What would be the gain?

**Comment by kain88-de** [comment]
A pure abstract class can be used to define an interface. The benefit isn't clear in python directly due to the use of duck-typing (everything is kind of based on promises for certain interfaces). But here we can make use to enforce that a new Analysis that actually subclasses has to implement `_single_frame` or the code won't get imported. That is the important difference right now we throw a runtime error. With meta class we kind of get a build error at import time.

Abstract classes and interfaces are more common in strongly typed languages where they are very useful.

**Comment by jbarnoud** [comment]
> That is the important difference right now we throw a runtime error. 

It is enough for me to be convinced. Are there drawbacks, though?

**Comment by richardjgowers** [comment]
@kain88-de afaik the error is still at runtime, just at class instance creation https://pymotw.com/2/abc/#incomplete-implementations

@jbarnoud the reason I'm asking is there isn't a huge benefit, just it's more of a correct way of defining these template classes. The downside is that it adds another (probably lesser known?, albeit standard library) module into the mix that developers will have to use.

For Reader/AnalysisBase it's a little overkill, for `TopologyAttr` it would be easy to forget to implement a method (eg `get_segments`) and only get bitten for it much later down the line.
