### ISSUE TITLE
In HydrogenBondAnalysis, include option to turn on periodic boundary conditions when searching for hydrogen bonds

### ISSUE THREAD

**Issue by jmborr** [MDAnalysis/mdanalysis#1188]
HydrogenBondAnalysis searches for acceptors and donors within a certain distance cutoff but does not take into account the case when the acceptor and donor are located on different sides of the periodic box. This will happen when searching for hydrogen bonds in the water solvent.

To prevent these bonds from being missed, include an option to turn on periodic boundary conditions when doing the search for bonds. Default should be off because distance search with periodic boundary conditions is much slower and is only of interest in certain cases.

```

### Currently version of MDAnalysis:
(run `python -c "import MDAnalysis as mda; print(mda.__version__)"`)

**Comment by richardjgowers** [comment]
WRT how to implement this @orbeckst has said that the real problem is that the distance and angle calculations shouldn't [live in the class itself](https://github.com/MDAnalysis/mdanalysis/blob/develop/package/MDAnalysis/analysis/hbonds/hbond_analysis.py#L992) but be imported from something like `lib.mdamath`.

Related issue #1185 where we talk about making a library for these sorts of calculations

Slightly more tangentially, the current implementation [is looping in python](https://github.com/MDAnalysis/mdanalysis/blob/develop/package/MDAnalysis/analysis/hbonds/hbond_analysis.py#L948) over atoms, which is probably slow(ish).  Better might be to [calculate all distances at once](https://github.com/MDAnalysis/mdanalysis/blob/develop/package/MDAnalysis/analysis/hbonds/hbond_autocorrel.py#L337).  But there might be a good reason that the HBA does it this way.

**Comment by jbarnoud** [comment]
From a (very) quick glance at the code, I noticed two places where distances are calculated: one of them is in a selection strings that uses the 'around' keyword, that one takes PBC into account if I'm not mistaken; the other is using a custom distance method (https://github.com/MDAnalysis/mdanalysis/blob/develop/package/MDAnalysis/analysis/hbonds/hbond_analysis.py#L1002). Why not using the distance functions we have in `analysis.distances`?

**Comment by richardjgowers** [comment]
The class methods are doing a single distance calculation, `lib.distances` does arrays of distances.

We don't actually have a function to do a single PBC distance calculation, which is why we end up with [weird code like this](https://github.com/MDAnalysis/mdanalysis/blob/develop/package/MDAnalysis/core/topologyobjects.py#L201)

**Comment by jbarnoud** [comment]
Maybe we should have one... That is a rather basic need, and I remember I wrote some ugly things like what you are pointing at.

**Comment by richardjgowers** [comment]
So for this, I think what is needed (as a first step) is for inside `MDAnalysis.lib.distances` add a `distance` function, which calculates a single pairwise distance, optionally applying PBC.  Then also in `lib.mdamath`, make `angle` also optionally calculate PBC.  So for both of these you need a PBC function which takes a vector and a box, and makes sure that the vector is the minimum image vector.

Then once this is in place we can make HBondAnalysis use these functions

**Comment by orbeckst** [comment]
Just for the record, the new WaterBridgeAnalysis in PR #1722 will also need to be refactored to use proper PBC-aware distance and angle calculations.

**Comment by navyakhare** [comment]
Please review PR #1782 . I have added pbc to the distance function, which calculates a single pairwise distance and also added a test case. But I not sure how to calculate the expected distance with pbc for the test case.

**Comment by navyakhare** [comment]
@richardjgowers  in HBondAnalysis right now angle calculation is being done through 
```
@staticmethod
    def calc_angle(d, h, a):
        """Calculate the angle (in degrees) between two atoms with H at apex."""
        v1 = h.position - d.position
        v2 = h.position - a.position
        if np.all(v1 == v2):
            return 0.0
        return np.rad2deg(angle(v1, v2))
```
which is using the angle() function from `lib.mdamath`. Instead of this why can't we directly use 
https://github.com/MDAnalysis/mdanalysis/blob/7b6ad00370e50c2a5a6479383984cb7a0e9333f1/package/MDAnalysis/lib/distances.py#L596
from `MDAnalysis.lib.distances` which already takes pbc into account.

**Comment by richardjgowers** [comment]
@navyakhare yep that's a really good idea, I think it'd be good to swap to using that.

**Comment by navyakhare** [comment]
@richardjgowers  while trying to swap I came across an error in the following function-
```
def _check_array(coords, desc):
    """Check an array is a valid array of coordinates

    Must be:
       (n,3) in shape
       float32 data
    """
    if ( coords.ndim != 2 or coords.shape[1] != 3):
        raise ValueError("{0} must be a sequence of 3 dimensional coordinates"
                         "".format(desc))
    _check_array_dtype(coords, desc)
```
the above function is checking for `coords.ndim != 2` which doesn’t look necessary. I removed it, changed to  `calc_angles()`  function and everything seems to be running perfectly fine. Since all test cases are passing is it fine to remove `coords.ndim != 2` condition ?

**Comment by richardjgowers** [comment]
@navyakhare `calc_angles` etc are made to accept arrays of coordinates and return arrays of angles, so mass production.  Don't change how they behave (because lots of other functions/users also use this function), but instead change how you are using it to give it a length 1 array, and unpack the single result

**Comment by navyakhare** [comment]
@richardjgowers thanks for the explanation and sorry for the trivial doubt.  I misinterpreted what `coords.ndim != 2` was checking. I have made the required changes. Please review PR #1782.
