### ISSUE TITLE
Add a method to copy a Universe

### ISSUE THREAD

**Issue by jbarnoud** [MDAnalysis/mdanalysis#1249]
This issue follows a comment by @kain88-de: https://github.com/MDAnalysis/mdanalysis/issues/1027#issuecomment-287622960

Copying a `Universe`, while is looks easy, can go wrong in multiple ways. When copying a `Universe`, one must think about, at least, these things:
* was the topology built from a file or not? If so, a new topology can maybe be built from the original file.
* was the topology modified since it got read? If so, building from file will be wrong.
* is the trajectory reader reading a file?
* is the trajectory a MemoryReader? If so, was it created from a file? Did the coordinates change since then?
* has the trajectory additional data attached to it?
* Is there any auxliary attached?
* ...

A `copy` method in `Universe` would streamline the copy.

One way to implement such method would be to have a `copy` method in readers, topologies, and auxiliaries. The standard case would be implemented in the base class. Specific case, like the memory reader, would overwrite the method.

Being able to copy AtomGroups and to attach them to a copy of a universe could also come handy, but is out of scope of the proposal.

**Comment by richardjgowers** [comment]
A lazy first effort (and probably valid for most cases) would be to read filenames and just recreate a Universe off those files, but a much better and rigorous approach is to properly copy the potentially modified objects. 

Another thing to bear in mind is whether we're doing deep copies or shallow copies of things.  This will be most notable when dealing with numpy arrays, and are we copying a view of the data (ie making a copy of a pointer for ourselves) or making an independent copy of the array.  Probably better to make sure we're making copies of the numpy arrays.

Definitely worth making `Universe.copy` just operate on `Topology.copy` and `Trajectory.copy`.  If we solve what copying a `Topology` means in terms of data, we've also half (or more) solved #643 

Similarly, if we can copy a trajectory, we are much closer to serialising, so that's also a huge step towards our parallel efforts.

**Comment by kain88-de** [comment]
I guess we might want to have a  `copy` and `deepcopy` method where the first is a shallow copy method.

**Comment by jbarnoud** [comment]
As a note: there is a prototype for #643 in the closed pull request #831

**Comment by orbeckst** [comment]
I very much like the idea of adding `copy` (or `deepcopy`) to the topology and trajectory/auxiliary objects. That makes the task somehow look more manageable.

We could start with a highly experimental version, which just does what probably most people have been doing when they cloned a universe: just re-read from files. Add `NotImplementedErrors` for cases where we know that this is going to fail, and clean up while we go along.

**Comment by jbarnoud** [comment]
Duplicate of #1029

**Comment by orbeckst** [comment]
I didn't know that [GitHub knows how to mark issues as duplicates](https://github.com/blog/2398-better-manage-issues-and-pull-requests-with-keyword-updates)!

Are there other [magic words](https://help.github.com/articles/closing-issues-using-keywords/) for issue comments ... ?
