### ISSUE TITLE
how to install mdanalysis via source files

### ISSUE THREAD

**Issue by ljzhou86** [MDAnalysis/mdanalysis#1351]
I downloaded the mdanalysis source files and extract in our supercomputer machinene. I get into the package and install it by running:
  
]$ /turquoise/users/ljzhou86/app/python-2.7.13/bin/python setup.py install
showing the error:
Traceback (most recent call last):
  File "setup.py", line 45, in <module>
    from setuptools import setup, Extension, find_packages
ImportError: No module named setuptools

Very strange. This error does not appear when I install other modules like numpy.  Could you help me to fix the install issue via the downloaded source files?

**Comment by orbeckst** [comment]
# setup.py
It looks as if you need to install [setuptools](https://pypi.python.org/pypi/setuptools). Then it should work with
```
python setup.py install --user
```
(or whatever options you need).

# pip

Is there any chance that you could install with `pip` (you can use the `--user` flag to install locally), because that will take care of all dependencies and you can use it to install from source, if you like. See http://www.mdanalysis.org/pages/installation_quick_start/ for background.

## PyPi releases
The tarballs on PyPi contain the package itself:
```
wget https://pypi.python.org/packages/55/bb/32c3dbd8e92b661a98839a50bd3185d29949afe4618fc1a846e42bad0ebf/MDAnalysis-0.16.0.tar.gz
pip install --user MDAnalysis-0.16.0.tar.gz
```

However, you don't need to do the downloading yourself: just
```
pip install MDAnalysis
```
will just work (and build the package from source).

If you want to work on the sources, unpack the sources and install with
```
pip install MDAnalysis-0.16.0/
```
(note the trailing slash `/`).

## GitHub releases
You would do something like (including download a source tarball):
```
wget https://github.com/MDAnalysis/mdanalysis/archive/release-0.16.0.tar.gz
tar zxvf release-0.16.0.tar.gz
cd mdanalysis
pip install --user package/
```
(again, note the trailing slash in order to tell `pip` to install a package inside a directory).

You might need to install other prerequisites:
```
pip install cython numpy
```

**Comment by kain88-de** [comment]
Install PIP for a single user

https://docs.python.org/2/library/ensurepip.html

```
python -m ensurepip --user
```

**Comment by orbeckst** [comment]
@ljzhou86 do you need more help to make it work?

**Comment by orbeckst** [comment]
@ljzhou86 I am closing this because we haven't heard from you in a week; feel free to post to this issue again if you need more help.
