### ISSUE TITLE
Caching things in Travis build

### ISSUE THREAD

**Issue by richardjgowers** [MDAnalysis/mdanalysis#1394]
As originally spotted by @utkbansal, installing our dependencies on travis can take 6-7 minutes, we could use the [caching](https://docs.travis-ci.com/user/caching/) facility on travis to reduce this.

Our build is a little complicated as we're using conda, but it looks like scikit-learn have done this:
https://github.com/scikit-learn/scikit-learn/issues/5455

@utkbansal is this something that you could look at?

**Comment by utkbansal** [comment]
I'll try to read more about this and get started on the coming weekend.

**Comment by utkbansal** [comment]
@richardjgowers  Looks like you will have to turn on this feature in TravisCI, it's not available by default.

> To use the caching feature, in your repository settings, set Build branch updates to ON.

**Comment by kain88-de** [comment]
Caches should be activated.

**Comment by orbeckst** [comment]
I think we need to

- [cache pip](https://docs.travis-ci.com/user/caching/#pip-cache) (basically, `~/.pip/cache`); I think we also need to make sure that we use `pip install --upgrade` so that we do pull in new versions of dependencies and not inadvertently keep stale packages around
- cache conda

Perhaps something like
```yaml
cache: 
   pip: true
   directories:
       - $HOME/miniconda
```
will work?

**Comment by utkbansal** [comment]
@kain88-de @orbeckst @richardjgowers @jbarnoud Why are we dependent on astropy's ci helpers? Why don't we have our own?

**Comment by kain88-de** [comment]
They are very responsive and so far did everything we needed them to do. They are also used by a lot of other projects so we can assume they do stuff correct. If you have problems with the script you can run from a fork temporarily and then we fix it upstream. They might be also interested in the caching.

**Comment by orbeckst** [comment]
Sort of related to the problem of keeping our run time on travis under 50 mins: We could split the tests in *analysis* and *core* using the build matrix (which was suggested in #286 a long time ago). However, the problem has been to maintain coverage. Assuming that #1369 works and we can merge the coverage reports we could now make use of Travis' new feature [Build Stages](https://blog.travis-ci.com/2017-05-11-introducing-build-stages): As I understand it, we can run our matrix as one stage and then run another stage that combines the coverage reports (if the first stage is successful). We could use a GitHub repo or an S3 bucket as temporary storage for coverage reports; I don't know if Travis allows us to keep build artifacts from earlier stages.

**Comment by kain88-de** [comment]
One thing. Since we now run different python versions on travis the caching from help us. Dependencies have to be downloaded again for each new python version. Right now I only see general improvements in conda to reduce our installation times. Or alternatively reducing the number of dependencies we have.

**Comment by orbeckst** [comment]
This looks as if we decided not to pursue caching at this time.

I will close and if anyone is interested, please reopen.
