### ISSUE TITLE
AtomGroups are not hashable on python 3

### ISSUE THREAD

**Issue by jbarnoud** [MDAnalysis/mdanalysis#1397]
### Expected behaviour

An `AtomGroup` is hashable, it can therefore be placed in a `set` or as a dictionary key. `topologyattr.Bonds.fragments`, that creates a set of `AtomGroups`, works as intended.

### Actual behaviour

Attempting to get the hash of an `AtomGroup` on python 3 raises the following error:

    TypeError: unhashable type: 'AtomGroup'

It works on python 2.

In python 3, a class that defines `__eq__` but not `__hash__` has `__hash__` set to `None`, see <https://docs.python.org/3/reference/datamodel.html#object.__hash__>. So we should define a `__hash__` method for the `GroupBase` class. I think this method could look like:

```python
def __hash__(self):
    return hash((self.universe, self.__class__, self._ix))
```

### Code to reproduce the behaviour

``` python
#!/usr/bin/env python

import MDAnalysis as mda
from MDAnalysisTests.datafiles import TPR, XTC

u = mda.Universe(TPR, XTC)

print(hash(u.atoms))
```

### Currently version of MDAnalysis:
(run `python -c "import MDAnalysis as mda; print(mda.__version__)"`)
'0.16.2-dev0'  (76527108a83030d69c6db270be313c11dd27c05b)

**Comment by richardjgowers** [comment]
Looks good.

`self.__class__` already implicitly contains `self.universe` because of the metaprogramming we do (I think?), but it's harmless and more explicit to also put universe into the hash.

We shouldn't use `self._ix` as the underscore bypasses any magic we want to put into the property, eg `UpdatingAtomGroup` wouldn't update itself when `._ix` is accessed.

**Comment by richardjgowers** [comment]
@jbarnoud if you want, you can add a knownfailure test and merge that, then @tylerjereddy or I will make sure that this passes for py3
