### ISSUE TITLE
empty universe always is created with a single residue

### ISSUE THREAD

**Issue by kain88-de** [MDAnalysis/mdanalysis#1771]
### Expected behaviour

with `n_residues=10` I get a Universe with 10 different residues.

### Actual behaviour

`u.atoms.n_resdidues` is 1

### Code to reproduce the behaviour

``` python
import MDAnalysis as mda

u = mda.Universe.empty(10, trajectory=True, n_residues=10)
u.atoms.n_residues
```

### Currently version of MDAnalysis:
(run `python -c "import MDAnalysis as mda; print(mda.__version__)"`)
0.17.1-dev

**Comment by kain88-de** [comment]
`u.atoms.residues.n_residues` is correct though.

**Comment by richardjgowers** [comment]
You've not supplied any information about which Residues atoms reside in, so they're all in the first Residue by default.  So then when you do `atoms.n_residues`, there's only one residue found as none other are filled. `u.atoms.n_residues` is sort of `len(set(atom.residue for atom in u.atoms))`, so because no atoms are in `u.residues[1:]`, they are never counted.

If you start to use any of the 10 residues they will start to "appear"

```python

In [11]: u.atoms[5:].residues = u.residues[1]

In [12]: u.atoms.residues
Out[12]: <ResidueGroup with 2 residues>

```

**Comment by kain88-de** [comment]
Can we make this automatic? It’s confusing currently as I would expect that `u.atoms.n_residues` and `u.residues.n_residues` give the same result after construction. 

If this isn’t possible we should add examples how to use the empty constructor efficiently.

**Comment by richardjgowers** [comment]
Examples of using the Empty constructor for topology building would definitely make good docs + blogpost material.

`u.atoms.n_residues` can't always return `u.residues.n_residues` because you're not using some of the residues.  We could add some warnings in if the user doesn't supply `atom_resindex` when requesting more than one Residue
