### ISSUE TITLE
Regarding printing the values of C-alpha and all the oxygen atoms of water molecules to a file

### ISSUE THREAD

**Issue by cy16f01** [MDAnalysis/mdanalysis#1823]
Hello,
1) I have a glycine-water system with a simulation run for 500 frames. Now i want the c-alpha (CA) atom and all the OW (oxygen atoms of water molecules) coordinates, wherein the first column is the time frame number, and second, third, fourth are the corresponding x, y, z coordinates of the atoms.

I have tried with normal python programming and here is the program...

```python
import  re
k=0
F=open('nptmdtrj500.gro','r')
A=open('CaOw-Coordinates500_1.dat','w')
with open ('nptmdtrj500.gro') as F:
    for x in F:
       line=x.strip()
       if line.startswith ("Generated by"):
           k=k+1
       if 'CA' in line or 'OW' in line:
           A.write(str(k) + '\t')
       A.write(x[22:44]+'\n')
A.close()
F.close()
```

I want to reproduce it in MDAnalysis, How can i do this..??
I tried the following:-

```python
import MDAnalysis as mda
u = mda.Universe('nptmdtrj500.gro', 'nptmdtrj500.xtc')
oxygens = u.select_atoms('name CA' and 'name OW') 
with open('oxygens.dat', 'w') as out:
    for ts in u.trajectory:
         for pos in oxygens.positions:
             out.write('{0}  {1[0]} {1[1]} {1[2]}\n'.format(ts.frame, pos))
```

but i am unsuccessful...where can i give the increment (as k=k+1) here, and define the k=0 globally..??

2) And by the way, how can i upload a .gro file here..(if i go to the selecting them line below, it doesn't show any .gro/.pd files within the folder.) and how to indent the python code here..?? the tab space or normal spacing is not getting accepted..!!!

Any suggestions are appreciated.

Thank you.

EDIT by @jbarnoud: fix the markdown around code extracts.

**Comment by jbarnoud** [comment]
How is it not working. Can you show an example of the output you get and the output you expect?

`k` is supposed to be the index of the frame, right? How isn't `ts.frame` working for you? An other option would be to replace your first `for` by

```
for k, ts in enumerate(u.trajectory):
```

`k` will then be the 0-based index of the frames you iter over as you iter over them, and not as it is written in the file. Because you loop over the frame with a `for`, you should not need to manually increment `k`.

To type some python in an issue message, you can use the code block syntax of markdown: write "\`\`\`python" at the beginning of the block and "\`\`\`" at the end. See the documentation at <https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown>.

**Comment by cy16f01** [comment]
I am getting only the oxygen coordinates for all the frames.... but i need C-alpha coordinates and then in the next lines i need to get all the Ow coordinates...
Expected Output (With the normal python code):
1	 1.158   1.191   1.103
1	 0.489   0.967   1.356
1	 0.867   0.127   1.703
1	 1.842   1.511   1.331
1	 0.117   0.751   2.129
1	 2.405   0.185   1.774
1	 0.016   2.177   0.277
1	 2.102   1.499   2.365
1	 1.564   0.262   1.918
1	 0.160   0.088   2.300
1	 1.410   0.025   0.109
Delivered Output (with MDAnalysis):
0 	 4.890000343322754 	 9.670001029968262 	 13.5600004196167
0 	 8.670000076293945 	 1.2699999809265137 	 17.030000686645508
0 	 18.420001983642578 	 15.110000610351562 	 13.310001373291016
0 	 1.1700000762939453 	 7.510000228881836 	 21.290000915527344
0 	 24.050003051757812 	 1.850000023841858 	 17.739999771118164
0 	 0.1600000113248825 	 21.770000457763672 	 2.7699999809265137
0 	 21.020000457763672 	 14.99000072479248 	 23.649999618530273
0 	 15.64000129699707 	 2.6200003623962402 	 19.18000030517578
0 	 1.6000001430511475 	 0.8800000548362732 	 23.000001907348633
0 	 14.100000381469727 	 0.25 	 1.090000033378601
If u compare it with the Expected output, the first line is the coordinates for C-alpha and the next lines are the coordinates for all Ow's, but in the Delivered output there is no C-alpha coordinates.
2) And how can i constrain the decimal values to 3 or 4 positions as in Expected output since the decimal values as in delivered output goes from 2 places to 15 places.. how can i restrict that..?? and hence it will be easy for further analysis..

Thank you.

**Comment by jbarnoud** [comment]
> I am getting only the oxygen coordinates for all the frames.... but i need C-alpha coordinates and then in the next lines i need to get all the Ow coordinates...

This is because of your selection. Your selection string should be `"name CA or name OW"`. It can also be `"name CA OW"`. The selection criterion is applied to each atom, and the atom is kept if it matches the criteria; therefore you want your atom to be either a CA or a OW to be kept. More importantly, everything has to be in the string. In what you wrote, you have 2 distinct strings: `"name CA"` on one hand, and `"name OW"` on the other. Because it is out of the strings, the `and` is not handled by MDAnalysis but by python directly. You are therefore doing boolean logic on strings, and you get a weird result because of how the `or` operator works in python.

> And how can i constrain the decimal values to 3 or 4 positions as in the Delivered output of normal python since the decimal values as in delivered output using MDAnalysis goes from 2 places to 15 places.. how can i restrict that..??

You need a more specific formating line. You can change your template line from `'{0}  {1[0]} {1[1]} {1[2]}\n'` to `'{0}  {1[0]:.3f} {1[1]:3f} {1[2]:3f}\n'` to tell python that the coordinates have to be written as floats with 3 decimal places. See the documentation of the formating language <https://docs.python.org/2/library/string.html#formatstrings>.

**Comment by cy16f01** [comment]
Thank you very much, sir, for your valuable inputs... it really solved the issue..
Lastly, I have a minor doubt...
Can u kindly tell me why this in out.write('{0}  {1[0]} {1[1]} {1[2]}\n'.format(ts.frame, pos)), the indexing are as these..??ie., {0}  {1[0]} {1[1]} {1[2]} i understand that it is writing the frames, and the 0,1st,2nd indexed values which correspods to the x, y, z coordinates..

I want to know how does it work in general...

Thank you.

**Comment by jbarnoud** [comment]
What is in between the braces are references to the argument of the `format` method. Here, the method has two arguments: `ts.frame` and `pos`. The order of these arguments matters as you reference them by index. When you write `{0}`, you make a reference to the first argument, *i.e.* `ts.frame`; when you write `{1}`, you make a reference to the second argument, being `pos`. The format language also allows you to make deeper references; with the square brackets, you get an item from the object. Then, with `{1[0]}`, you ask for the second argument of the `format` method (`pos`), and the first element within it (the x coordinate).

**Comment by cy16f01** [comment]
Sir,
I have extracted the C-alpha and all the Ow atoms of water molecules for all time frames (500-time frames) and saved in .xyz format. But now if i view this in VMD, and if i calculate the distance between two oxygen atoms  (VMD->mouse->lable->bonds) i am getting some inter oxygen atoms distance less than 2.8Angstrom (from RDF of Ow-Ow the interatomic distance is 2.8 Angstrom). like 1.2A, 2A, 0.9A etc.. 
How is this possible...??

It's really astonishing...

Any suggestions ..??

I am attaching the file, but since i cant attach the .xyz file (no options for certain file format) i have converted only the extension ie., .xyz to .log (so to view in VMD kindly change back the extension from .log to .xyz 
[CaOw_1.log](https://github.com/MDAnalysis/mdanalysis/files/1805634/CaOw_1.log)

**Comment by cy16f01** [comment]
Is this something to do with PBC..?? how to implement  PBC here in the code then..??

**Comment by jbarnoud** [comment]
The RDF is a distribution, you cannot use it to say that all the distances correspond to where the peaks are. If you want to check how correct you xyz file is, I suggest you compare the coordinates in that file with what you have in your initial GRO file: the coordinates for your frame 0 should match those in the GRO file. Account in your comparison that the GRO file is defined in nm and your XYZ file is in Å.

**Comment by cy16f01** [comment]
Sir,
I have checked the .xyz file and the .gro files and accounting for the comparison of \AA \unicode{x212B}, 
all the coordinates are exactly matching.
But the problem is that if the .gro file is viewed, there is no such wired/such short distances,  but only in case of viewing .xyz file, it is a problem.
How can i rectify this error..??

**Comment by cy16f01** [comment]
Sir, 
I have a Lithium-chloride (lithium ions and chloride ions)+amino-acid+water system.
So, for this system, if i give the same code to extract the C-alpha and Ow's.
```python
import MDAnalysis as mda
u = mda.Universe('nptmdtrj500.gro', 'nptmdtrj500.xtc')
oxygens = u.select_atoms('name CA OW')
#calpha = u.select_atoms ('name CA') 

with open('CaOw500.dat', 'w') as out:
    for k, ts in enumerate(u.trajectory):
        for pos in oxygens.positions:
            out.write('{0}\t{1[0]:.<0.3f}\t{1[1]:.<0.3f}\t{1[2]:.<0.3f}\n'.format(ts.frame, pos))
```
I am getting an error/warning message as:
/home/dilip/anaconda3/lib/python3.6/site-packages/MDAnalysis/topology/guessers.py:56: UserWarning: Failed to guess the mass for the following atom types: LI
  "".format(', '.join(misses)))
But the output file (CaOw500.dat) is written. 

Why is this coming only for Licl system..?? I have run the same code for Kcl+amino-acid+water system, but i didn't get any error message as such.
How do i solve this issue..??

Any suggestions...

Thank you.

**Comment by cy16f01** [comment]
My question is that how can't it find the mass of lithium ions..?? my simulation system has lithium and chloride ions+amino-acid+water. If it can find the mass of other ions system (Kcl+amino-acid+water), why not this..??

Any suggestions...??

**Comment by jbarnoud** [comment]
You get your topology from a GRO file that does not have the mass 
written in. MDAnalysis has to guess the mass and use a table for that. 
The key for lithium in that table is "Li", without much surprise. But 
for some reason, the element is guessed to be "LI" (all in capitals). 
Because "LI" is not in the table, the mass is not found. There are more 
discussions on the matter on #1808.


What is the atom name for your lithium ions in your GRO file?

**Comment by cy16f01** [comment]
My GRO file has Lithium-ion named as "LI". In GROMACS, i used 'gmx genion' command to add the ions and it adds ions named in capital letters.

**Comment by orbeckst** [comment]
Mass guessing is not working all the time and it is hard to make it work reliably, see the discussion that Jonathan pointed to. If you need masses then load your topology from a file that contains masses; for Gromacs this means a TPR. 

--
Oliver Beckstein
email: orbeckst@gmail.com
