### ISSUE TITLE
Deprecation warnings

### ISSUE THREAD

**Issue by yurivict** [MDAnalysis/mdanalysis#1898]
```
/usr/local/lib/python3.6/site-packages/MDAnalysis/core/universe.py:482: DeprecationWarning: Instant selector Universe.<segid> is deprecated and will be removed in 1.0. Use SegmentGroup[SegmentGroup.segids == '<segid>'] instead.
  DeprecationWarning)
/usr/local/lib/python3.6/site-packages/MDAnalysis/core/topologyattrs.py:507: DeprecationWarning: Instant selector AtomGroup['<name>'] or AtomGroup.<name> is deprecated and will be removed in 1.0. Use AtomGroup.select_atoms('name <name>') instead.
  DeprecationWarning)
```

Version 0.18.0, python-3.6, FreeBSD 11.1.

**Comment by orbeckst** [comment]
Hi @yurivict , in which context does this deprecation warning show up? Can you please post the code that lead to the warning?

**Comment by yurivict** [comment]
This example: https://www.mdanalysis.org/pages/basic_example/ prints:
```
$ python3.6 ex.py
/usr/local/lib/python3.6/site-packages/MDAnalysis/core/universe.py:482: DeprecationWarning: Instant selector Universe.<segid> is deprecated and will be removed in 1.0. Use SegmentGroup[SegmentGroup.segids == '<segid>'] instead.
  DeprecationWarning)
/usr/local/lib/python3.6/site-packages/MDAnalysis/core/topologyattrs.py:507: DeprecationWarning: Instant selector AtomGroup['<name>'] or AtomGroup.<name> is deprecated and will be removed in 1.0. Use AtomGroup.select_atoms('name <name>') instead.
  DeprecationWarning)
frame = 0: d = 11.712209701538086 A, Rgyr = 16.43512217722917 A
...skipped...
```

**Comment by orbeckst** [comment]
You can ignore the warnings. We have deprecated the [instant selectors](https://www.mdanalysis.org/docs/documentation_pages/selections.html#instant-selectors) since release 0.16.0 and we will remove them in 1.0 (see the deprecation note there). We recommend that you *do not* use these instant selectors anymore but instead use normal [selections](https://www.mdanalysis.org/docs/documentation_pages/selections.html).

Many thanks for pointing out that the basic examples page is outdated – that's a bit embarrassing...

I raised a separate issue https://github.com/MDAnalysis/MDAnalysis.github.io/issues/80 so I will close this one here.
