### ISSUE TITLE
coverage is not reported by COVERALLS

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#1918]
### Expected behaviour
[coveralls](https://coveralls.io/github/MDAnalysis/mdanalysis) should report the code coverage status.

### Actual behaviour
[![Coverage Status](https://coveralls.io/repos/github/MDAnalysis/mdanalysis/badge.svg?branch=develop)](https://coveralls.io/github/MDAnalysis/mdanalysis?branch=develop)

The status is "unknown" (as of 2018-05-27 and about a week before).

### Background
- @richardjgowers (?) moved mdanalysis from travis-ci.org to travis-ci.com, https://travis-ci.com/MDAnalysis/mdanalysis ; in the process we reset our history.
- In the coveralls settings menu I did a *Resync with github* (Sync the location, privacy setting, and default branch of this repo with Github.)
- Coveralls reports as "build type" *travis-pro* so I assume that means it refers to travis-ci.com.

**Comment by richardjgowers** [comment]
I also had to change to using a token to upload our coverage, because of using the "pro" travis.

https://github.com/MDAnalysis/mdanalysis/commit/f184da17b39f2812438c553a6427ef3a89d1ef17

We're using .com now, which is what the pro travis used to be, so I think coveralls still calls it pro.

The link to this repo from coveralls doesn't seem to work either, it goes to mdanalysis/tree/ which is odd.

**Comment by orbeckst** [comment]
Coverage is back, I ain't gonna ask no questions...
