### ISSUE TITLE
Nucleic acid analysis Chi torsion calculation

### ISSUE THREAD

**Issue by aakognole** [MDAnalysis/mdanalysis#2248]
Hi @orbeckst ,

I think the chi torsion calculation could use a correction. 

Currently you have this,
https://github.com/MDAnalysis/mdanalysis/blob/da5f93428f576f95379e4e971c5ca71815fbdfd5/package/MDAnalysis/analysis/nuclinfo.py#L669-L677

However, the if loop will always be skipped as all the nucleosides have those 4 atoms selected before. 
So, in case of ADENINE and GUANINE, you still get a value for O4'-C1'-N1-C2 but you want O4'-C1'-N9-C4. One might not have got much of a different value as for ADE and GUA the atoms N1-C2 and N9-C4 are lying almost in the same plane, but it's not exactly what you want.

Exchanging the selections with each other should work. 

```python
c = universe.select_atoms(" atom {0!s} {1!s} O4\' ".format(seg, i), 
                               " atom {0!s} {1!s} C1\' ".format(seg, i), 
                               " atom {0!s} {1!s} N9 ".format(seg, i), 
                               " atom {0!s} {1!s} C4  ".format(seg, i)) 
if len(c) < 4:
    c = universe.select_atoms(" atom {0!s} {1!s} O4\' ".format(seg, i), 
                               " atom {0!s} {1!s} C1\' ".format(seg, i), 
                               " atom {0!s} {1!s} N1 ".format(seg, i), 
                               " atom {0!s} {1!s} C2  ".format(seg, i)) 
```

**Comment by orbeckst** [comment]
Then in function `tors()` the code for `c` https://github.com/MDAnalysis/mdanalysis/blob/da5f93428f576f95379e4e971c5ca71815fbdfd5/package/MDAnalysis/analysis/nuclinfo.py#L446-L454 also needs to be changed. In fact, the function https://github.com/MDAnalysis/mdanalysis/blob/da5f93428f576f95379e4e971c5ca71815fbdfd5/package/MDAnalysis/analysis/nuclinfo.py#L388 should just call the separate torsion functions in order to reduce duplicated code.

**Comment by orbeckst** [comment]
@denniej0-2 any comments?

**Comment by aakognole** [comment]
Yes, you need to change it also in the main function `tors()`.
Calling the separate functions works best.

**Comment by orbeckst** [comment]
Sorry, I am totally snowed under with other things – PR very welcome!
