### ISSUE TITLE
Rebuild Wiki on GitHub

### ISSUE THREAD

**Issue by GoogleCodeExporter** [MDAnalysis/mdanalysis#234]
```
1. turn the wiki branch into a GitHub wiki (see Wiki)
2. manually fix up pages where necessary
3. start filing issues re: wiki where community cleanup is needed 

See MoveToGitHub for further details, in particular for links on how to 
transmogrify the wiki.
```

Original issue reported on code.google.com by `orbeckst` on 28 Mar 2015 at 1:38
* Blocking: #223
* Blocked on: #233

**Comment by orbeckst** [comment]
I moved the converted wiki from the wiki branch (now deleted) to the github wiki (using [morgant/finishGoogleCodeGitHubWikiMigration](https://github.com/morgant/finishGoogleCodeGitHubWikiMigration)). I also fixed most of the top page of the wiki (the old Google Code home page) but there's plent left to do:
* links on wiki pages have to be changed
  * links to docs should point to the release docs on https://pythonhosted.org/MDAnalysis/
  * links to code should point to files in the [MDAnalysis/mdanalysis master branch](https://github.com/MDAnalysis/mdanalysis)
  * any other links to Google Code should be changed appropriately
* images were not included (mostly affects the statistics page but that should probably addressed with issue #167  .

(The history of the old wiki was also lost in the migration because the Google Code Exporter only converted the HEAD from Google Code wiki syntax to [GitHub-flavored Markdown](https://help.github.com/articles/github-flavored-markdown/). I have a complete clone of the old [Google Code Wiki repository](https://code.google.com/p/mdanalysis/source/browse?repo=wiki) (mdanalysis.wiki) if we ever need it.)

**Comment by orbeckst** [comment]
Additionally needed
* sidebar similar to what we had on Google Code (see [TableOfContens](https://code.google.com/p/mdanalysis/wiki/TableOfContents)); a list of 54 pages is not helpful...
* removal (or burial) of pages that are not relevant any more (eg related to SVN or the migration to GitHub)
* clean-up of the [Home](https://github.com/MDAnalysis/mdanalysis/wiki) page (it's too verbose at the moment and not a good entry into the wiki).
* ... and probably lots more.

Once we have a sidebar or an entry page that fulfills the function of a useful table of contents we can close this issue and open issues for individual wiki problems.

**Comment by tylerjereddy** [comment]
I've added a sidebar to the new github wiki page. It has a format that matches what we had on Google Code quite closely, so I'm closing this issue. As you suggest, there are still many other wiki adjustments needed, for which we should open issues where appropriate, etc.
