### ISSUE TITLE
New MDAnalysis home page

### ISSUE THREAD

**Issue by GoogleCodeExporter** [MDAnalysis/mdanalysis#236]
We will need a home page for MDAnalysis after the move to GitHub (Issue #223). The "organization" page https://github.com/MDAnalysis really only allows us one link and that should point to a page that contains the most important information (similar to what the current home page http://mdanalysis.googlecode.com contains, i.e. overview, links to PyPi, code, docs, wiki, issue tracker, mailing lists and people).

We could probably use [GitHub pages](https://pages.github.com/)  and put everything under http://mdanalysis.github.io/ for the time being. 

(I quite like http://seb-buch.github.io/ ;-) )

Original issue reported on code.google.com by `orbeckst` on 29 Mar 2015 at 5:48
* Blocked on: #223

**Comment by orbeckst** [comment]
I got the domain *mdanalysis.org* for us and set the CNAME so that the MDAnalysis "home page" [MDAnalysis.github.io](http://MDAnalysis.github.io) now appears at [www.MDAnalysis.org](http://www.MDAnalysis.org).

**Comment by dotsdl** [comment]
Looks nice! However, the [Home](http://www.mdanalysis.org/) and [About MDAnalysis](http://www.mdanalysis.org/about/) pages currently show redundant information. I'm guessing this is because the Jekyll site uses **Home** as a blogroll? That's fine if we intend to use it as a place for release notes and other happenings, but at the moment it just seems strange.

**Comment by orbeckst** [comment]
Am Apr 5, 2015 um 15:19 schrieb David Dotson <notifications@github.com>:

> Looks nice! However, the Home and About MDAnalysis pages currently show redundant information. I'm guessing this is because the Jekyll site uses Home as a blogroll?
> 
No, I pretty much duplicated the content on purpose so that a visitor would be sure to find all the information that was previously available. The blog format is not really useful for the site because the primary use is static content. But Poole/Hyde was the first that I found and it was simple. We just need someone who is going to properly set up the home page. 

Oliver

**Comment by orbeckst** [comment]
I am moving all discussion about website specifics (i.e. [www.mdanalysis.org])(http://www.mdanalysis.org) over to the [MDAnalysis.github.io issue tracker](https://github.com/MDAnalysis/MDAnalysis.github.io/issues). This issue continues as [Issue #1](https://github.com/MDAnalysis/MDAnalysis.github.io/issues/1) over there.
