### ISSUE TITLE
why is (cached) fragments slow?

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#2376]
**Is your feature request related to a problem? Please describe.**
The "make whole" (unwrap) on the fly transformation PR #2038 needs the fragments at every time step. ~Apparently, the fragments are recalculated every time~ (EDIT: They are not – see discussion below) 

```python
>>> u = mda.Universe(data.TPR, data.XTC)
>>> %timeit u.atoms.fragments
556 ms ± 71.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

Recalculating fragments takes 0.5 seconds per step.

**Describe the solution you'd like**
~There is no need to recalculate fragments as they are based on bonds. Fragments can be created when the topology is created.~

~Or only recalculate if the bonds change, or just tell users that if they change bonds then they also need to recalculate fragments.~

EDIT: Recalculating fragments is not the problem but building the actual data structure appears to be slow.

**Describe alternatives you've considered**
Recalculating fragments every time the managed attribute is accessed guards against stale data, which is good. However, user expectation is that attributes behave as instantaneous value stores (and the fact that we use managed attributes should not concern users). Furthermore, I contend that the case of accessing fragments for different time steps is more common than the case of changing the topology. 

**Additional context**

Doing the unwrap is slow no matter what, ca 4s/iteration
```python
In [81]: u = mda.Universe(TPR, XTC)
In [82]: u.trajectory.add_transformations(MDAnalysis.transformations.wrap.unwrap(u.atoms))
In [83]: with mda.Writer("unwrap.xtc", n_atoms=u.atoms.n_atoms) as W:
    ...:     for ts in tqdm.tqdm(u.trajectory):
    ...:         W.write(u.atoms)
    ...:
100%|██████████████████████████████████████████████████████████| 10/10 [00:39<00:00,  3.90s/it]
```
but at least shaving off 0.5 s is a start.

**Comment by richardjgowers** [comment]
https://github.com/MDAnalysis/mdanalysis/blob/develop/package/MDAnalysis/core/universe.py#L998

I think they are cached at a universe level... so maybe something else
weird is happening here. Maybe it’s the construction of the fragments for
this AG from the master list?

**Comment by orbeckst** [comment]
As they are cached then something else appears to be slow. Needs some line profiling, I think.

**Comment by orbeckst** [comment]
Can we cache https://github.com/MDAnalysis/mdanalysis/blob/e1101089ffc7aa58be654f7d0a82840a9d5a7175/package/MDAnalysis/core/topologyattrs.py#L1830 ?

**Comment by zemanj** [comment]
Caching `AtomGroup.fragments` is not straightforward since it requires an `AtomGroup` to know if the underlying `Universe._fragdict` changed.

I worked on a solution (without caching) to this problem a while ago based on 0.19.3, I just didn't have time to write tests and create a PR for it, plus some of the stuff I added probably needs to get thrown out again. It currently lives in my [faster_unwrapping branch](https://github.com/zemanj/mdanalysis/tree/faster_unwrapping).

Regarding the performance of `AtomGroup.fragments`, I get the following:
```python
import MDAnalysis as mda
from MDAnalysisTests.datafiles import TPR, XTC
%timeit u.atoms.fragments
```
Result for current dev branch (0.20.2):
```
328 ms ± 6.05 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
Results for faster_unwrapping branch (0.19.3):
```
537 µs ± 5.53 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```
That's 610 times faster and should make the problem go away.

Anyway, it won't help if it keeps growing mold in my MDA fork...

**Comment by orbeckst** [comment]
Maybe it would motivate you to see a massive drop in the benchmarks? (I realized that we were not timing fragments because the naming of the benchmark was incorrect – thus PR #2240 )

Making fragments faster would be an important first step to making `make_whole()` faster. 4s per frame is just way too slow to be really useful.

**Comment by zemanj** [comment]
Gamification FTW! :wink:
Unless I missed something in the `AtomGroup` methods benchmarks, we still need to add `AtomGroup.unwrap()` there for all supported `compound`s.

**Comment by orbeckst** [comment]
Hmph – the benchmark https://www.mdanalysis.org/benchmarks/#ag_methods.FragmentFinding.time_find_fragments is failing. Need to look into it.

**Comment by mnmelo** [comment]
@zemanj, I'm having similar caching limitations in #3000 / #3005. Again, the problem with caching at the `AtomGroup` level is that there are `Universe`-level events that are hard/impossible to propagate to individual `AtomGroups` so that they invalidate their relevant caches.

I thought of a solution that might solve all this. What if (using `'fragindices'` as an example attribute):
 - All `AtomGroups` caches are moved to `Universe._cache` as `WeakKeyDictionaries`;
 - Each `AtomGroup` object is a `WeakKey` to its own cache under `Universe`;
 - Caches are organized by attribute name, then by `AtomGroup`, e.g.: `u._cache['fragindices'][ag]`;
 - `AtomGroup._cache['fragindices']` get/set access becomes a redirector to `self.universe._cache['fragindices'][self]`;
 - And best of all for our problem: **universal cache invalidation becomes as easy as `u._cache['fragindices'].clear()`**

Any thoughts?

**Comment by mnmelo** [comment]
So, I implemented those ideas and universe-based caching is indeed possible, and completely abolishes fragment construction-time (assuming we cache the tuple of fragments itself). Besides the need of carefully invalidating caches at the relevant points in the code (`add_bonds`/`delete_bonds` must invalidate fragment-related caches, `segments.setter` invalidates segment-related caches, etc.) it can be implemented with minimal impact to existing cache operations.

Additionally, unwrapping also gets sped up by the optimized compound-indices splitting code I put forth in #3005 

And finally, a major speedup can be achieved if not all molecules are unwrapped, but only those that span more than 0.5 of any box vector. This is a relatively cheap check and easy to implement (don't know if @zemanj's [solution](https://github.com/zemanj/mdanalysis/tree/faster_unwrapping) also leverages this or just an optimized Cython unwrapper).

What do you think of this strategy? Should I make PRs for the caching and selective unwrap features?

**Comment by richardjgowers** [comment]
The speedups here look significant.  One initial option for keeping caches fresh is to go nuclear on any change to topology attributes.  This would just be removing everything in `u._cache` (or wherever everything is stored) on `TopologyAttr.set_atoms/anything`.  I'm much more in favour of having everything cached at Universe level rather than Groups.

**Comment by mnmelo** [comment]
A lighter alternative is to use some sort of topology versioning (say, an `int` stored under `Universe.topology._version`: any time a topology-modifying method is used it increments this version, and then it is easy for Group-based cache management to keep track of it and know whether caches need to be re-built.

I really have no preference for one solution over the other; input is welcome.
