### ISSUE TITLE
update links to GitHub or www.mdanalysis.org in the documentation

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#240]
The reST doc (and everything else) needs to be updated to point to the new site(s). In particular:
* New *home page*: http://www.MDAnalysis.org
* Links to the *new wiki*: https://github.com/MDAnalysis/mdanalysis/wiki/
* New *issue tracker*: https://github.com/MDAnalysis/mdanalysis/issues

Links to  the sphinx-generated online docs should all be inside the reST but for reference, they should end up at https://pythonhosted.org/MDAnalysis/
If a link to the docs for the development branch is needed (#235): http://www.mdanalysis.org/mdanalysis/package/doc/html/

@tylerjereddy : Tyler, I assigned this one to you as the Doc-Czar but of course feel free to delegate ;-).

**Comment by tylerjereddy** [comment]
I've done my best to perform the requested changes for the development branch source code  (these have now been pushed after passing unit tests). Note that links to attachments on google code issues have also been adjusted to reflect the move to github, but that the new links still appear to depend on google in some way (probably based on the migration process). Also note that my substitutions were only performed for files in the MDAnalysis package directory tree with last two characters 'py' (basically as in gist linked below).

The process of performing the rather large number of string substitutions was semi-automated using parts of the code I wrote (https://gist.github.com/defd459f7f0bb34a35ee.git) + manual intervention. It would probably be sensible for someone to do a little grep work on the package tree to see if they can find anything I missed. Finally, if that looks ok, then someone can rebuild the docs and merge as needed. I think I've done most of the annoying stuff though.

Presumably similar changes will be needed to the wiki / new webpage (?) -- perhaps those should be treated as separate issues -- if only to encourage me or others to complete them / close an issue rather than having a broad issue of 'update all links in all doc presentation media.'

**Comment by orbeckst** [comment]
Many thanks, Tyler!! You even fixed the stuff in the comment headers.

I think the links to attachments are ok; I don't know for how long google will keep them alive but it's not overly critical, at least looking at the actual links.
I did a few more cleanups (see commit message) and will now close the issue.

Please open separate issues for the remaining things, I leave this to you. I agree with you, smaller manageable chunks are better.
