### ISSUE TITLE
Issues don't close on pushing to dev

### ISSUE THREAD

**Issue by richardjgowers** [MDAnalysis/mdanalysis#242]
So I recently "closed" #221 but the issue has remained open.  After a bit of reading, github closes issues once the commit hits the default branch, which for us is master.

https://github.com/blog/1386-closing-issues-via-commit-messages

So could we change the default branch to dev? Or does this break something else?

**Comment by orbeckst** [comment]
I would want to keep master on the front page, given that's the safe bet for anyone new. However, automatic issue closing from develop make *a lot* more sense!

**Comment by orbeckst** [comment]
Btw, close #221 manually.

**Comment by orbeckst** [comment]
@richardjgowers : on thinking about this again and reading the blog post about  [closing issues with commit messages](https://github.com/blog/1386-closing-issues-via-commit-messages) I think we should make *develop* the default branch and have commits close issues immediately. This is the way that we have been handling things so far, and we haven't left issues open until a new release. There's also no way to manually close an issue "until merged into master" so there's no easy way of keeping the issue reports properly synced up (some will have been closed, other are waiting for auto-closing). Ultimately, I think we have to make this easy for @MDAnalysis/coredevs and @MDAnalysis/contributors .  Users with problems will probably ask on the user list as they did in the past and in my experience are also less likely to go to the issue tracker as their first resort when checking if there's a problem with the released version. With the [increased release frequency](https://github.com/MDAnalysis/mdanalysis/wiki/SemanticVersioning), the state of the issue tracker should also be much closer to the state of the *master* branch (and the released packages) as we had before (pre-0.9.x).

So for right now I am going ahead and **make *develop* the default branch**:

* *develop* will show up at https://github.com/MDAnalysis/mdanalysis/ (instead of *master*)
* If a commit messages contains the words "Fixes Issue #NNN" or (closes or similar — see the blog post) then it will automatically close the issue.

If anyone has strong feelings some other way, please re-open this issue for discussion.

With the added emphasis and exposure of the *develop* branch it becomes ever more important that the branch also stays in a usable state. Use feature branches liberally to develop new stuff and run the unit tests. Obviously, getting CI running #134 would be very helpful in this regard.
