### ISSUE TITLE
Release 1.0

### ISSUE THREAD

**Issue by richardjgowers** [MDAnalysis/mdanalysis#2443]
I think we're due another release.  I think the only ongoing thing is @lilyminium 's work on docs, so ideally this release captures all changes necessary to the package for their doc work. (ie if this is an awful idea tell me and we can postpone).

Looking at #2303 (esp https://github.com/MDAnalysis/mdanalysis/issues/2303#issuecomment-529680541 ) it looks like the plan is that this release is called 1.0 and is the last python 2.7 release.  Work then continues ~~(supporting only py 3)~~ as 1.x until we finish the annoying API change stuff and we call the result 2.0 (and drop py 2)

following feedback, todo:
 - [x] flags @richardjgowers 
 - [x] ncdf @IAlibay 
 - [x] tpr jazz @jbarnoud 
 - [x] #2408  @lilyminium 
 - [x] #2382 @lilyminium 
 - [x] instant selectors removal @richardjgowers

**Comment by IAlibay** [comment]
As previously discussed with @richardjgowers I'd like to at least fix the NCDF reader portion of #2323 and #2327 before release 1.0.

I'll hopefully get this done within the next couple of weekends if that's ok with your schedule?

**Comment by richardjgowers** [comment]
![doeeet](https://i.giphy.com/media/bKnEnd65zqxfq/200.webp)

**Comment by jbarnoud** [comment]
With gromacs 2020 released, I'd like to see #2431 merged before 1.0. Especially as, in the current state there will be unreadable errors as the TPR parser expects a TPR from gromacs 2020-beta that are very different.

**Comment by lilyminium** [comment]
Sounds good! Will you be going through and looking at currently open PRs before release? There's some GSOC stuff and I would prefer to have #2408 in the release, as the current ITPParser is very flawed. #2382 would be nice too.

**Comment by orbeckst** [comment]
In an ideal world we would have everything ready for 1.0. 

But the things mentioned above should be in 1.0 and we also wanted to remove the flags #782 . It would be easier to make this 0.21 and then follow up with 1.0. A release is overdue, and it might as well be 0.21 and then we follow up with 1.0.

Btw,  @richardjgowers – you looked at the wrong comment, the last one was https://github.com/MDAnalysis/mdanalysis/issues/2303#issuecomment-543937601 and the official roadmap is the (ambitious) https://www.mdanalysis.org/2019/11/06/roadmap/. 
> 1.0 will be similar to upcoming 0.21 (i.e., no major annoying API breaks but clean-up and deprecations)

**Comment by richardjgowers** [comment]
Ok thanks @orbeckst so we'll see what we can get finished in a week or two then make a release, maybe it's 1.0 maybe it's 0.21.

**Comment by orbeckst** [comment]
Ok, [sounds fair](https://www.youtube.com/watch?v=RBw8yL1SVbo).

**Comment by xiki-tempula** [comment]
Sorry for the try to rush this in the last minute #2480. I have replaced the distance search with capped_distance, so it should provide a decent speed boost.

**Comment by IAlibay** [comment]
@richardjgowers 

Re: netcdf it looks like if we aren't going for an API complete version 1.0, the only thing needed here is to remove the `degrees` keyword on the reader. I'll deal with adding `scale_factor` support to the writer in a future version.

Additionally, as mentioned in #2479 there's a few things that need to be removed on time for v1.0 (currently making my way through this and will make appropriate PRs over the next few days):

 - [ ] `save()` and `store()` analysis methods and certain instances of `filename` #1745 
 - [ ] extra `kwags` in analysis/base.py
 - [ ] waterdynamics `t0`, `tf`, and `dtmax` (question for this, it was set for deprecation but no removal version was set, is v1.0 reasonable?)
 - [ ] `degrees` in the NCDFReader
 - [ ]  core/distances.py
 - [ ] analysis/x3dna.py
 - [ ] core/log.py
 - [ ] core/parallel.py
 - [ ] core/qcprot.py
 - [ ] core/transformations.py
 - [ ] core/units.py
 - [ ] core/utils.py
 - [ ] core/KDTree.py
 - [ ] `test_generated_residueselection` in test_segment.py
 - [ ] at least one test from test_transformation.py
 - [ ] `FullSelgroupSelection` in core/selection.py
 - [ ] `heuristic` test in test_hbonds.py
 - [ ] `__getitem__` in core/groups.py
 - [ ] `test_chainid_quick_select` in core/test_universe.py
 - [ ] `test_segments` in core/test_atomgroup.py 

Since it doesn't seem clear if we are going for v1.0, I'll start the PRs for these and if they don't lead to anything, we could either keep them around for when we do go v1.0, or just drop em and re-open new PRs next time around?

**Comment by orbeckst** [comment]
The next release will be 1.0 —  along the lines of the [Roadmap](https://www.mdanalysis.org/2019/11/06/roadmap/). 

One goal is to make the jump from 0.20.1 to 1.0 painless and to avoid breaking existing code as much as possible as 1.0 will be the *last version with Python 2 support*. Users might have to rely on it for a while (until they get rid of legacy Python 2, which might take a long time in science) so we don't want to additionally burden them with having to rewrite their old code just to run 1.0. 

If you want to remove something, try to keep the old thing around but deprecate it in 1.0 (add deprecation warnings and deprecated doc) and schedule it for removal in 2.0 (say it in the warning and add comments to the code for anything that should go in 2.0). Even better: raise an issue to remove the thing an tag it with ["remove-2.0"](https://github.com/MDAnalysis/mdanalysis/labels/remove-2.0).

**Comment by orbeckst** [comment]
Just to clarify: The avoid "breaking existing code" mainly referred to things like rewriting analysis classes. All the scheduled 1.0 removals and changes that had been planned for a long time should just go ahead as planned (and indeed have mostly be done already).

**Comment by orbeckst** [comment]
We should start changing the 0.21 to 1.0; in particularm, it would be good if the dev docs and the version string started showing 1.0.0-dev.

**Comment by richardjgowers** [comment]
Its fine I can just do them all in one go

**Comment by orbeckst** [comment]
Can we get a 1.0 out?

What is holding us up? It really only should be real bugs or important API decisions, not features/nice-to-haves.

I don't think we want to wait for GSoC projects – they can go in 2.0 (or a 1.x if we do one and they still support py 2.7)

**Comment by lilyminium** [comment]
The following would be nice to have in 1.0 and are close to done / need review:

- #2665 (bug fix)
- #2636 (error messages) / #2635 / #2565
- #2206 (may already be fixed with the waterdynamics PR)

There are some old issues in the milestone, are they still applicable?
- #1769 does not look urgent
- #1738 -- box dimensions -- nice to clean that up?
- is #1463 done yet?
- #919 perhaps review all the class docs to make sure they're not in `__init__`, recently I had to move `Ramachandran`'s
- #1105 looks pretty resolved and maybe more of a user guide issue
- #206 and #309 look old...

**Comment by IAlibay** [comment]
#1738 / #2698 would be nice to get done depending on how large a change it involves. I'll have a dig through later today and see how much needs to be done.

**Comment by RMeli** [comment]
I might have a bit of time for #2698 this weekend if you need help @IAlibay, but if it's not an easy change (they never are ;) ) it might drag a bit longer...

#2694 should be ready too if you want to include the fix only and not @lilyminium's suggestion for a more advanced functionality.

**Comment by richardjgowers** [comment]
I’m going to try and bash out 1.0 this weekend, it’s been far too long.

**Comment by richardjgowers** [comment]
I think re: #206 is Writers need a bit of API love, but that can wait as there's nothing showstopped bad about them right now

I've updated the 1.0 milestone, currently there's 2 PRs waiting, my deprecating Timestep to Writers and Lily's cool attribute error hacks.  If anyone wants anything else going in to 1.0 you've got about 24 hrs to make lots of noise (with an associated PR where possible).

**Comment by lilyminium** [comment]
If refactored helanal (#2622) is okayed by someone (preferably better at geometry than me) before then, that'd be nice, otherwise it can wait. Thanks for pushing things along @richardjgowers!

**Comment by orbeckst** [comment]
Can you email the dev list for this momentous occasion, please? Just in case not everyone gets the notifications. Thanks!

**Comment by hmacdope** [comment]
@richardjgowers I know i'm a bit late to the party but thoughts on #2619? Its almost there, if not it can wait for sure. :)

**Comment by richardjgowers** [comment]
Might have to wait, sorry.

**Comment by hmacdope** [comment]
No worries :)

**Comment by orbeckst** [comment]
We still need the github release.

**Comment by orbeckst** [comment]
Do we want to advertise right now or do the 1.0.1 so that Python 2 pip installation works #2736 ?

**Comment by lilyminium** [comment]
Could you please upload a 1.0 testsuite package to conda-forge @richardjgowers :-)

**Comment by richardjgowers** [comment]
@lilyminium done!

**Comment by IAlibay** [comment]
Should the meta.yaml file under mdanalysis/maintainer/conda/MDAnalysis also have been updated for 1.0? https://github.com/MDAnalysis/mdanalysis/blob/329c3fc2f9376f1ec040addf3cc69fc969f00bca/maintainer/conda/MDAnalysis/meta.yaml#L4

**Comment by richardjgowers** [comment]
Not used. I don’t think I use anything in maintainer/

**Comment by orbeckst** [comment]
I don’t think we use it at all. Better delete it and replace with a README pointing to the two conda-forge repos for mdanalysis and mdanalysistests.

**Comment by orbeckst** [comment]
We can delete
- `maintainer/conda`
- `maintainer/install_all.sh`
- `maintainer/adapt_sitemap.py` (superseded by @lilyminium new doc installation #2749 )
- `maintainer/change_release.sh` (given that @richardjgowers is not using it)

The rest is used in CI.

**Comment by orbeckst** [comment]
@richardjgowers can you please also put the 1.0.0 release up under https://github.com/MDAnalysis/mdanalysis/releases ? Thanks.

**Comment by orbeckst** [comment]
That's actually done.
