### ISSUE TITLE
water bridge problem

### ISSUE THREAD

**Issue by jito-tj** [MDAnalysis/mdanalysis#2446]
I also want to calculate the water bridge for bulk water system. Here is my code:

import numpy as np
import profile
import MDAnalysis as md
import MDAnalysis.analysis.hbonds
import matplotlib.pyplot as plt
import MDAnalysis.analysis.hbonds
import MDAnalysis.analysis.hbonds.WaterBridgeAnalysis

u = MDAnalysis.Universe('298-add.pdb', '298-add.xtc')
w = MDAnalysis.analysis.hbonds.WaterBridgeAnalysis(u, 'resname SOL', 'resname SOL')
w.run()

------------------------------------------
but it still have error, like this:
Traceback (most recent call last):
  File "t3.py", line 11, in <module>
    import MDAnalysis.analysis.hbonds.WaterBridgeAnalysis
ImportError: No module named WaterBridgeAnalysis

Could you help me to solve this problem?

Best regards

**Comment by orbeckst** [comment]
@jito-tj – please ask "how do I" questions on the mailing list. For MDAnalysis we decided that the issue tracker is for bugs and features only. We look at the mailing list and if it looks like a bug we will ask you to file a issue here. But we found that it is too distracting if we answer questions in the tracker.

I'll make an exception because you were likely not familiar how we handle things here: 

In short: Your error says that `WaterBridgeAnalysis` is not something that can be imported as a module – because it is a class. See https://www.mdanalysis.org/docs/documentation_pages/analysis/wbridge_analysis.html#how-to-perform-waterbridgeanalysis  and the following should work (just drop the superfluous/wrong line `import MDAnalysis.analysis.hbonds.WaterBridgeAnalysis`):

```python
import MDAnalysis.analysis.hbonds
u = MDAnalysis.Universe('298-add.pdb', '298-add.xtc')
w = MDAnalysis.analysis.hbonds.WaterBridgeAnalysis(u, 'resname SOL', 'resname SOL')
w.run()
```
