### ISSUE TITLE
Guess bonds on Universe creation

### ISSUE THREAD

**Issue by richardjgowers** [MDAnalysis/mdanalysis#245]
Currently PDBParsers have a guess_bonds keyword which lets them guess bonds on construction.  It would be good to move this out of PDB and available for all formats.

So I could do..
```python
u = mda.Universe('something.gro', guess_bonds=True)
```
And have bonds guessed.

What would be the best way to do this?

Adding a keyword to Universe init to guess bonds once top and trj and loaded?
```python
u = mda.Universe(top, trj, guess_bonds=True)
```
Add a method to Universe which guesses bonds?
This has an advantage as you could pass custom vdwradii
```python
u.guess_bonds(radii = ?)
```
Or extend this to include bonds, angles, torsions & impropers
```python
u = mda.Universe(top, trj, guess_topology=True)
u.guess_topology()
```
Or all of the above?

The guessing functions exist are in topology.core, so this should be something easy to include, just wanted some feedback on what looks best.

**Comment by mnmelo** [comment]
Cool idea!
How about merging 1 and 2 together? Thus:
u = mda.Universe(top, trj, guess_bonds_radii=5)
with the default guess_bonds_radii being None, meaning no guessing.

**Comment by orbeckst** [comment]
I also like the idea, especially putting the machinery in a single place where it can be maintained, tested, and re-used.

One should be able to do this automagically when creating the universe using an optional argument as suggested. I think you'd also want to have a way to re-trigger the process (perhaps even on an AtomGroup basis??).

Providing the list of radii might be a bit more tricky because in principle this can become more involved than VDW radii for elements. You could start applying force-field tables over atom types to do a pretty decent job. Not that we need to implement this right now — the VDW-based guess is probably good enough and if anyone really cares they should provide a proper topology — but I am simply thinking how this mechanism could be improved in the future.

**Comment by richardjgowers** [comment]
Yeah, guessing for a single AtomGroup might be very handy, eg I've got something solvated and don't care about my water bonds.  I'll add that in too.

**Comment by richardjgowers** [comment]
Got a rough outline of this will look up now.  It should allow AtomGroup.guess_bonds([vdwradii=dict()]) to guess everything.
