### ISSUE TITLE
select vs selection

### ISSUE THREAD

**Issue by lilyminium** [MDAnalysis/mdanalysis#2461]
**Expected behavior**

MDAnalysis analysis functions and classes have a standard keyword for selecting atoms from a Universe.

**Actual behavior**

It varies largely between 'select' and 'selection', meaning that I have to look up each function when I want to use it. It's usually a keyword argument (everything below has it as such), so I do have to give the right keyword.

**select**
- rms.RMSD, rms.RMSF
- align.AlignTraj, align.AverageStructure
- diffusionmap.DistanceMatrix
- pca.PCA

**selection**
- contacts.q1q2, contacts.Contacts
- gnm.GNMAnalysis, gnm.closeContactGNMAnalysis
- helanal.helanal_trajectory, helanal.helanal_main
- hole.HOLEtraj
- all of encore
- hydrogenbonds.HydrogenBondAnalysis

**atomselection**
- density.density_from_Universe, density.density_from_PDB, density.BfactorDensityCreator

**ref_select**
- psa.PSAnalysis (also has `path_select`)

**Currently version of MDAnalysis**

- Which version are you using? (run `python -c "import MDAnalysis as mda; print(mda.__version__)"`) 0.20.1
- Which version of Python (`python -V`)?
- Which operating system?

**Comment by IAlibay** [comment]
So I'm mostly going from memory here, but am I correct in thinking most of the `select` cases are the analysis methods that have been moved to `:class:AnalysisBase`?

**Comment by lilyminium** [comment]
Yup. The only odd ones out are `contacts.Contacts` and `hydrogenbonds.HydrogenBondAnalysis`, which subclass AnalysisBase but use `selection`.

**Comment by orbeckst** [comment]
`select` seems to be the modern way to go!

- add select
- document select 
- deprecate the others and drop 
  - Should we drop *before* or *after* 1.0?

**Comment by richardjgowers** [comment]
It will need to get done soon for 1.0 :)

**Comment by lilyminium** [comment]
If this does get addressed, can I also suggest that the default argument is "all"? The encore classes, at least, all have `selection='name CA'` as default.

**Comment by orbeckst** [comment]
I think ENCORE is special in this regard; I doubt that anyone would want to run it for all atoms — maybe @mtiberti has an opinion or can say why, at least for ENCORE, the default makes most sense.

**Comment by IAlibay** [comment]
On the idea of having uniform selection strings, this might be a bit controversial, but could I suggest that the selections actually default to `None` or make it non-optional instead?

My main rationale here is that it would preferable to have empty (rather than wrong) results if a user fails to set the selection flag correctly. This would hopefully make it a lot more obvious that something went wrong.

**Comment by orbeckst** [comment]
If something is `None` then it will still default to something sensible, at least that's my expectation for any Python code. 

@IAlibay what examples do you have where the default will lead to wrong results?

One can also make the argument that the default for a selection should be specific to the analysis that is performed. For example, the typical RMSD analysis that I see in papers is based on the C-alphas of a protein, so it's not the worst default to choose.  Personally, I prefer sensible defaults, especially when I am exploring code, as opposed to having to know values for everything. But I can be convinced otherwise – I understand that "choosing sensible defaults" can mean vastly different things for different people from different scientific backgrounds.

**Comment by IAlibay** [comment]
> I understand that "choosing sensible defaults" can mean vastly different things for different people from different scientific backgrounds.

So my above suggestion basically stems from this idea. Personally, I think probably the best option here is to have a selection that reflects the intent of the original analysis code. However, I also definitely see the value in @lilyminium's original suggestion, uniformity would probably be better. 

> @IAlibay what examples do you have where the default will lead to wrong results?

So I should probably clarify what I meant by "wrong" here. It's probably not the best choice of wording. I conflated a "wrong" result as either of these two cases:

1) A result which significantly deviates from the intended purpose of the analysis method. So for example, if we set the `density_from_Universe` selection to `all`, then we'll likely just get a density array that probably doesn't mean much in most cases (I can probably still think of a couple of cases where that could be useful though, more so than say `c-alphas`, but that probably just reflects the type of work I use MDAnalysis for).

2) A set of results where the user forgets to pass a selection value and gets a result that isn't what they wanted to use the analysis method for, i.e. pure user error. I realise that this scenario really is on the user, there's no way any code could remove the element of user error and it would be rather rare for anyone not to try to cross-check their analysis outputs.

So the thought from my initial comment is that, if the idea is to create a uniform selection string across all analysis methods, which has merits, you could possibly end up in the realm of the above case no. 1. So at that point you might as well also tackle case no. 2, set it so that all analysis methods return a `null` result by default and provide more usage examples in the docstrings.

I did however not consider how un-pythonic such a solution would be. In that light, it probably isn't the best of ideas.

**Comment by orbeckst** [comment]
1. Switching everything to `select` is not controversial — so if anyone can get it done, please do it!
2. On the matter of defaults for `select`: In this case I see the purist approach (all uniformly "all" or all required)  doing more harm than good, given that reasonable defaults existed historically, especially with the view towards a 1.0 that is least disruptive. My vote is therefore to essentially keep the old defaults. If there are inconsistencies between somewhat similar classes (e.g., if RMSD and RMSF had different defaults) then I would choose something consisten (e.g., "all" when it makes sense).

**Comment by RMeli** [comment]
PR #2528 (WIP) tries to fix 1, but all the default are left unchanged.

This might be a larger discussion for 2.0 where changes can be introduced?
