### ISSUE TITLE
Merge() does not create a topology structure

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#249]
[Merging atom groups](https://pythonhosted.org/MDAnalysis/documentation_pages/core/AtomGroup.html#merging) with [Merge()](https://pythonhosted.org/MDAnalysis/documentation_pages/core/AtomGroup.html#MDAnalysis.core.AtomGroup.Merge) does not create *any* topology information. In particular, it does not even create the `Universe._psf` structure dict.

Even simple things like the `_repr_` break (although its [advertised function](https://pythonhosted.org/MDAnalysis/documentation_pages/core/AtomGroup.html#merging) works):

```python
import MDAnalysis; from MDAnalysis.tests.datafiles import *
u = MDAnalysis.Universe(PSF, DCD)
m = MDAnalysis.Merge(u.atoms[:2000], u.atoms[2000:])
print(m)
```
gives
```
AttributeError: 'Universe' object has no attribute '_psf'
```
It would be desirable for `Merge()` to also create a minimal topology (possibly empty). Even better would be a sensible combination of using existing topology parts and guessing the rest.

**Comment by richardjgowers** [comment]
I think the __repr__ failing is simply because the empty Universe it makes doesn't make a _topology dict (previously called _psf) in it's empty constructor

Merging topology should be possible too, although a bit more fiddly.  The topology information is stored at its most basic level as tuples of indices, ie (0, 1), but when the Universe gets merged the indices of the atoms can (and will) get changed.  This would then mean you'd need to remap the "old" indices to the "new" universe.

An alternative possibility would be to a "deeper" copy of the Atoms, so that their bonds get copied too.  There's no link between the Bonds and the Universe, the Bond is essentially an object with a pointer to a few Atoms.
