### ISSUE TITLE
Universe() should either work as Universe.empty() or raise an exception

### ISSUE THREAD

**Issue by Luthaf** [MDAnalysis/mdanalysis#2527]
**Expected behavior**

```python
import MDAnalysis as mda
u = mda.Universe()
print(u)
```

Prints something sensible.

**Actual behavior**

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-f7a893c68ed4> in <module>
----> 1 print(u)

~/code/mdanalysis/package/MDAnalysis/core/universe.py in __repr__(self)
    775
    776         return "<Universe with {n_atoms} atoms>".format(
--> 777             n_atoms=len(self.atoms))
    778
    779     def __getstate__(self):

TypeError: object of type 'NoneType' has no len()
```

**Currently version of MDAnalysis**

- Which version are you using? (run `python -c "import MDAnalysis as mda; print(mda.__version__)"`): 0.20.2-dev0
- Which version of Python (`python -V`)? Python 3.7.6
- Which operating system? macOS 10.14.5

**Comment by Luthaf** [comment]
After looking a bit more at the docs, it looks like I should use `mda.Universe.empty()` instead to create a Universe. Then maybe calling `mda.Universe()` with no argument should fail?

**Comment by orbeckst** [comment]
Honestly, since we have `Universe.empty()` it is not clear to me why `Universe()` cannot (semantically) do the same thing — I concede that this would be pythonic behavior.

(There's a good chance that this is simply due to history and the fact that for the longest time empty universes weren't possible. I am also not sure if there are insurmountable technical difficulties.)

**Comment by richardjgowers** [comment]
@Luthaf thanks for the report. Because there's C allocation going on, and resizing is a pain, even an empty Universe needs to know its size.

It might actually be that you want to pass in the `Topology` object, which is the thing that a `Parser` (our reader of everything but coordinates/velocities/forces/dimensions) spits out?

**Comment by Luthaf** [comment]
> It might actually be that you want to pass in the Topology object, which is the thing that a Parser (our reader of everything but coordinates/velocities/forces/dimensions) spits out?

I ended up using `Universe.empty()` and working with that without issue.
