### ISSUE TITLE
better raise error for file format

### ISSUE THREAD

**Issue by hainm** [MDAnalysis/mdanalysis#266]
Hi,

as in this post, I got this error
https://github.com/MDAnalysis/mdanalysis/issues/262#issuecomment-98142731

`TypeError: Unknown topology format 'PARM7' for './myparm.parm7'; only ['XPDB', 'PRMTOP', 'Permissive_PDB', 'TOP', 'PSF', 'PDBQT', 'MOL2', 'PQR', 'DMS', 'TPR', 'CRD', 'GMS', 'GRO', 'XYZ', 'DATA', 'PDB'] are implemented in MDAnalysis.`

and Richard pointed that we can use 
```python
u = mda.Universe('something.parm7', trj, topology_format='PRMTOP')
```

should it be better to add more comment in the `raise` saying user can use `topology_format` if he/she know what it is?

Hai

**Comment by orbeckst** [comment]
That's a really good (and easy to implement ;-) ) suggestion, @hainm!

The current format detection is dumb and only looks at file extension but one could add machinery that hooks into `guess_format()` that does more clever things. Admittedly, this hasn't been the highest priority because once a user knows that they can use `format=...` they typically get it right in the future but I totally agree that a better error message would go some way to make this easier for the user.

**Comment by orbeckst** [comment]
P.S.: @hainm: If you have a pull request, let us know....

**Comment by richardjgowers** [comment]
A cool thing would be if the format dict would map to a list of readers, which would be tried in turn until one worked.
so {'crd': [charmmreader, amberreader]}

You'd have to then also make readers have reliable checks on if they've read the file ok.

It could look like:

For reader in readers:
    Try: 
        Traj = reader(file)
    Except (ioerror, valueerror):
        Pass
    Else: 
        Break
else:
    Raise ioerror("no reader found etc etc")

But admittedly it's pretty low priority

**Comment by orbeckst** [comment]
Maybe have each Reader implement its own format checker as a static method. This could be as simple as "check the file suffix" to more complicated checking of magic numbers or format headers up to trying to read. Having it with the reader would bundle all the logic with the appropriate format. `guess_format()` then only has to collect all the static methods and try them in a certain order.
But as you say... somewhat low priority.
