### ISSUE TITLE
Provide AtomGroup selections to Contacts

### ISSUE THREAD

**Issue by lilyminium** [MDAnalysis/mdanalysis#2666]
## Feature request ##
_Originally posted by @orbeckst in https://github.com/MDAnalysis/mdanalysis/issues/2368#issuecomment-545079547_

* Add AtomGroup functionality:
  - It is  clunky that I have to provide *selections* instead of AtomGroups for `Contacts(..., selections=...))` to indicate which groups the contacts are formed between. I should be able to use static AtomGroups (cannot be dynamic). See #2369 

* Tidy up the helper function:
  - The https://github.com/MDAnalysis/mdanalysis/blob/9372d093acebb78bc5b1a2b4dba815a4e3281b04/package/MDAnalysis/analysis/contacts.py#L464 helper function can just use `Universe.copy()`.

**Comment by mkadiya20** [comment]
Hello, am I able to work on this?

**Comment by IAlibay** [comment]
Please do go ahead @mkadiya20. Put up a pull request and link this issue, and it will get reviewed. If you need help getting started, please check out the [user guide](https://userguide.mdanalysis.org/stable/index.html), particularly the [Contributing](https://userguide.mdanalysis.org/stable/contributing.html) and [Contributing code](https://userguide.mdanalysis.org/stable/contributing_code.html) sections.

**Comment by IAlibay** [comment]
Please also don't forget to introduce yourself on the developer list if you are looking to apply for GSOC @mkadiya20 (see here for more details: https://www.mdanalysis.org/2021/03/09/gsoc2021/)

**Comment by mkadiya20** [comment]
Thank you very much! I will do a PR once I solve the issue and I'll be sure to introduce myself.

**Comment by mkadiya20** [comment]
I was working on this a little bit, I got the helper class to use `Universe.copy()`. As for providing AtomGroups, a tuple of two AtomGroups is passed in `Contacts` rather than `selections` string. So, I just pass `Universe.select(atmgrp[0])` rather than with selection string. So should I completely get rid of selection string from the class argument or just add AtomGroup tuple as optional or make selection string optional?. Also, I'm assuming I need to create a unit test to make sure these inputs work for AtomGroups right?
