### ISSUE TITLE
Add triclinic_vector information to timestep

### ISSUE THREAD

**Issue by mnmelo** [MDAnalysis/mdanalysis#276]
Following up the discussion on #274:

It's sometimes desirable to have access to the triclinic vector description of the unit cell. The current implementation provides only `Timestep.dimensions`, which is the norm-angle representation of the unit cell.

Currently, triclinic vectors can be calculated using `coordinates.core.triclinic_vectors(Timestep.dimensions)`. Advantages of providing something like `Timestep.triclinic_vectors` or `Timestep.triclinic_dimensions`, as @richardjgowers suggested, would be the saving of redundant such calculations (again, see #274), and a slight increase in readability.
Drawbacks are the constant (pretty minor) cost of one such calculation per frame.

Implementation can be done naïvely, with `Timestep.triclinic_dimensions` always calculated from `coordinates.core.triclinic_vectors(Timestep.dimensions)`, or it can be done cleverly on a per format basis since some formats expose unit cells already as triclinic vectors (and in such cases converting to and from `Timestep.dimensions` will certainly entail some loss of precision).

I'll be looking at how difficult it will be to implement the clever version. I haven't looked at the detalis of how `Timestep.dimensions` is calculated, but I guess some sort of per format approach must already be taken. I'll see if I can add `Timestep.triclinic_dimensions` to that.

In the meanwhile, please drop any comments here.

**Comment by richardjgowers** [comment]
There needn't ever be a performance hit if it's just a property

Then if there's format where you can shortcut this (GRO and DCD off the top of my head), then they can override the base.Timestep implementation of this property easily enough

**Comment by orbeckst** [comment]
Just FYI, Gromacs XTC and TRR formats store triclinic box vectors, DCD ... depends: If NAMD or old CHARMM then its box/angles, new CHARMM it's box vectors. 

In any case, the property based implementation in #358 is a good enough start and we can refine it later.

**Comment by richardjgowers** [comment]
Hmm, yeah I think all you'd need to do is override the properties in the subclasses of Timestep....

**Comment by richardjgowers** [comment]
So I tried this, and the annoying thing is you lose the docs when you redefine the property.  I tried a couple recipes for inheriting docs, but I don't think they were playing nice with the property decorator.  

inheriting docs:
http://code.activestate.com/recipes/576862/

**Comment by tylerjereddy** [comment]
What is the meaning of `ts.dimensions` when I'm using a triclinic (rhombic dodecahedron) container? By definition, such a container does not contain an orthogonal angle, so how can it be considered valid for it to have one in `ts.dimensions`? Furthermore, why doesn't `ts._unitcell`, which is documented to contain the **native** unit cell information, contain the 9 elements used **natively** by GROMACS to specify the triclinic cell? It actually looks exactly like the `ts.dimensions` property to me.

Only, `ts.triclinic_dimensions` seems to do the right thing, but why shouldn't all types of unit cells just automatically populate `ts.dimensions` appropriately?

I can probably guess the answers to some of the above from a design standpoint, and possibly there are some internal dependencies on a fixed data shape for `ts.dimensions`. On the other hand, why should orthorhombic containers get `dimensions` instead of `orthorhombic_dimensions` -- providing a general name seems to imply that orthorhombic deserves to be the default and that triclinic is merely an edge case with its own specially-named property that you have to know about (and `dimensions` doesn't warn you as far as I can tell).

**Comment by richardjgowers** [comment]
@tylerjereddy `ts._unitcell` will contain whatever the format defined the unitcell to be, so for GRO it stores the 9 vectors found at the bottom of the GRO file.  The `ts.dimensions` method/property then converts this into the 6 element representation we use everywhere in MDA.  AFAIK we only support orthogonal and triclinic boxes, that can be represented with the 6 element representation.

**Comment by tylerjereddy** [comment]
I'm getting 6 elements for `ts._unitcell` with XTC

**Comment by tylerjereddy** [comment]
Looks to me like the base class for trajectory `Timestep` is [hard coded](https://github.com/MDAnalysis/mdanalysis/blob/develop/package/MDAnalysis/coordinates/base.py#L362-L365) to have `._unitcell` of size 6. The GRO reader overrides `_init_unitcell` in its version of the `Timestep` class to allow for the expansion. I see no evidence that the XDR base class or the derived XTC reader perform this expansion to accommodate tricinlinic formats, which is almost certainly why I'm observing this problem.

**Comment by orbeckst** [comment]
> I'm getting 6 elements for ts._unitcell with XTC

As far as I can tell, our TRR/XTC readers do not any more populate `ts._unitcell` (but @kain88-de can correct me). They directly populate `ts.dimensions`: e.g., in [coordinates.TRR.TRRReader._frame_to_ts()](https://github.com/MDAnalysis/mdanalysis/blob/develop/package/MDAnalysis/coordinates/TRR.py#L138):
```python
ts.dimensions = triclinic_box(*frame.box)
```
`frame.box` is a 3x3 array but this is not exposed; perhaps we should add a line like
```python
ts._unitcell = frame.box
```

When representing triclinic boxes with 6 numbers, the first three are lengths and the second three are the three angles. Compared to a description with 3 box vectors (9 numbers) you loose the information of the absolute orientation of the box in space: we always take axis a to be along x, axis b in the x-y plane, and axis c as needed.

**Comment by tylerjereddy** [comment]
Ok, that helps a bit. I still find the interface a bit confusing.

I think #1575 is a real problem though -- something really strange is going on there and I can use our standard test files to reproduce the issue as shown in the code block / output.

**Comment by kain88-de** [comment]
I was not aware of the `_unitcell` convention and I found conflicting information in the code. Personally I'm trying to use the normal TimeStep when refactoring a reader instead of using a inherited class. In the normal TimeStep `dimensions` is a [property](https://github.com/MDAnalysis/mdanalysis/blob/develop/package/MDAnalysis/coordinates/base.py#L731) that returns `_unitcell`. Therefore I should store our default unitcell of `a, b, c, alpha, beta, gamma`.  This is what XTC currently follow.

For some historic reason though the [GRO](https://github.com/MDAnalysis/mdanalysis/blob/develop/package/MDAnalysis/coordinates/GRO.py#L120) documents that the xtc should store triclinic unitcells in `_unitcell`.  

I haven't found any general reference in our docs that `_unitcell` should be the raw unitcell data as read from the trajectory file.

**Comment by richardjgowers** [comment]
I think the idea behind `_unitcell` was it allowed for better round trips when reading/writing.  So we only mangle to `[x, y, z, a, b, g]` on demand, but keep the original representation to avoid rounding errors.

**Comment by orbeckst** [comment]
The [Trajectory API for Timestep](http://www.mdanalysis.org/mdanalysis/documentation_pages/coordinates/init.html#private-attributes) prescribes that `_unitcell` is the
> native unit cell description; the format depends on the underlying trajectory format. A user should use the `dimensions` attribute to access the data in a canonical format instead of accessing `Timestep._unitcell` directly.
> The method Timestep._init_unitcell() is a hook to initialize this attribute.

and that `dimensions` should generally be a property that does an on-the-fly conversion of `_unitcell`:
> system box dimensions (x, y, z, alpha, beta, gamma) (typically implemented as a property because it needs to translate whatever is in the underlying _unitcell attribute. Also comes with a setter that takes a MDAnalysis box so that one can do
>
>    `Timestep.dimensions = [A, B, C, alpha, beta, gamma]`
>
>    which then converts automatically to the underlying representation and stores it in `Timestep._unitcell`.

I think we should try to be consistent with the API and fix the Readers to use `_unitcell` and `_dimensions` as described above. In the context of #1575 we should decide clearly if `_unitcell` is going to behave like a view (like `Timestep.positions`) or like a copy. For `.positions` we should keep a view for performance reasons; creating big coordinate arrays is really bad. For `_unitcell` the overhead of creating a copy is small so we could just do that if necessary.
