### ISSUE TITLE
replace Windows tests on AppVeyor with Azure

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#2846]
I noticed that we are often waiting for AppVeyor to complete whereas Azure is fast. 

Could we replace AppVeyor's Windows testing with Windows testing under Azure?

**Comment by orbeckst** [comment]
ping @tylerjereddy ?

**Comment by tylerjereddy** [comment]
Yep, I did that migration for NumPy & SciPy too. We might see the symlink error show up again if memory serves me correctly, since that was Azure specific on the 32-bit job but we could just generalize the skip until resolved.

**Comment by orbeckst** [comment]
@tylerjereddy would you be able to take on this migration? Simplifying/speeding up CI has high karma reward ;-).

**Comment by tylerjereddy** [comment]
Yeah, I should be able to--main obstacle I see is that I'd be hesitant to use the same `conda` deps as Appveyor and instead just add extra deps via `pip` so that the Azure config remains fairly consistent in using wheels/PyPI instead of `conda` for deps. (more deps used in appveyor vs. 32-bit Windows on Azure at the moment I think)

We can just check the final suite results before removing appveyor in any case, for consistency

**Comment by orbeckst** [comment]
I don't know if we can install everything that we need with pypi/wheels – I thought, one example was h5py with the hdf5 libraries, as discussed in PR #2787 . However, apparently @edisj could just install pip-install h5py and the new tests for coordinates.H5MD ran with 95% coverage (see [azure job 20200714.11](https://dev.azure.com/mdanalysis/mdanalysis/_build/results?buildId=567&view=logs&j=1cdae27b-58e8-5c64-01e2-519b6cdf4b73&t=15e2290a-ee6f-51a8-922c-29ec56e58ae3) so that one might be ok.

**Comment by tylerjereddy** [comment]
I think RDKit is a problem here. They have blog posts about why they don't provide PyPI wheels, but... really we should probably require new deps to provide wheels/sources on PyPI except in truly exceptional circumstances, and even then under the understanding that the integration may be fragile and tested sparingly.

My current plan then is to leave the Appveyor config alone for RDKit testing on Windows and otherwise keep Azure CI config `pip` based, such that removal of Appveyor is contingent on RDKit providing wheels, but speedy/reliable Windows testing can still be provided by Azure minus RDKit.

**Comment by tylerjereddy** [comment]
Perhaps we could even just slim down the Appveyor entry to just do RDKit/conda-only stuff so it is not so slow.
