### ISSUE TITLE
Allow MDAnalysis.lib.NeighborSearch.AtomNeighborSearch to return empty AtomGroup instead of []

### ISSUE THREAD

**Issue by xiki-tempula** [MDAnalysis/mdanalysis#2892]
## Is your feature request related to a problem? ##
When using `MDAnalysis.lib.NeighborSearch.AtomNeighborSearch`, if no atoms have been found, `AtomNeighborSearch` would return `[]`. 

When using `select_atoms`, if no atoms have been found `<AtomGroup with 0 atoms>` would be returned.

I personally found that the way `select_atoms` handles the empty selection is better compared with `AtomNeighborSearch` and wish `AtomNeighborSearch` could return empty atom group.

## Additional context ##
Allowing `AtomNeighborSearch` to return `<AtomGroup with 0 atoms>` would means that the code

```
selection = AtomNeighborSearch(self.u.atoms[self._s1], box=self.box)
if selection.search(self.u.atoms[self._s2], self.selection_distance):
    s1 = selection.search(self.u.atoms[self._s2], self.selection_distance).ix
```

could be optimized into 
```
selection = AtomNeighborSearch(self.u.atoms[self._s1], box=self.box)
s1 = selection.search(self.u.atoms[self._s2], self.selection_distance).ix
```
to make the code more clear.

**Comment by orbeckst** [comment]
I like your idea because it makes for a unified user experience.

While looking at [MDAnalysis/lib/NeighborSearch.py](https://github.com/MDAnalysis/mdanalysis/blob/develop/package/MDAnalysis/lib/NeighborSearch.py) I realized that this file should not live in lib: we have a rule that nothing in lib gets to import from core. This seems to be a historical oversight (as well as the camel-case name).

I would want to extend your proposal to move `NeighborSearch.py` search elsewhere (and possibly change its name). I am not 100% set on where it should go – @MDAnalysis/coredevs any opinions? How about
1. `core.neighbor_search`
2. `analysis.distances.neighbor_search` (make analysis.distances a sub-package containing distances.py and neighbor_search.py)
3. `analysis.distances.AtomNeighborSearch` (copy the class into distances.py)
4. ... ?

**Comment by IAlibay** [comment]
I'd probably vote to not put NeighborSearch in analysis, at the risk of making things increasingly more complicated one option could be to create a new `utils` section for things that are lib-like but don't follow the lib rules?

**Comment by richardjgowers** [comment]
Looking at the code it doesn't use `core.AtomGroup` and it just does an `isinstance(x, Atom)` to make the positions 2-dimensional.  I think? that capped distance does the upcast of 1d to 2d dimensions automatically now, so I think that check isn't required... tl;dr it's fine as is

**Comment by richardjgowers** [comment]
Oh and the actual issue idea is a good one!  This is probably a leftover from when this class used to return a list of Atoms or something.

**Comment by xiki-tempula** [comment]
@richardjgowers If the return is not empty, the AtomNeighborSearch returns a normal atom group. It is just that when the return is empty, it returns an empty list.

**Comment by orbeckst** [comment]
So if we get rid of the `instance(Atom)` check then it will be fine for `lib` as it will just take an AtomGroup as input. We then just return `n_atom_list` as it is for 'A' (slicing with empty indices produces the empty AtomGroup since we changed it a while ago).

As a sidenote: we should also be returning `n_atom_list.residues` and `n_atom_list.segments` instead of lists of these objects.

**Comment by orbeckst** [comment]
@xiki-tempula do you want to do a PR
- [ ] return `n_atom_list` for "A"
- [ ] return `n_atom_list.residues` for "R"
- [ ] return `n_atom_list.segments` for "S"
- [ ] update tests
- [ ] update docs

(The latter also work with empty ` ResidueGroup` and `SegmentGroup`, e.g., `u.atoms[[]].segments`.)

**Comment by xiki-tempula** [comment]
@orbeckst I could do
 return n_atom_list for "A"
 return n_atom_list.residues for "R"
 return n_atom_list.segments for "S"
 update tests
 update docs

I will try to see if I could do `remove import from core and make sure that it still works without the Atom check`.

I can see that there is some discussion regarding where the file should be. I'm not sure if we should move this file to some other place.

**Comment by richardjgowers** [comment]
It’s a pain to move files and break API. A single import isn’t a good
reason to do this.

**Comment by xiki-tempula** [comment]
I will do a PR and implement @orbeckst 's suggestions.

**Comment by orbeckst** [comment]
First off, let's keep `lib.NeighborSearch` in its old place. We'll make it work without the explicit `Atom`.

> It’s a pain to move files and break API. A single import isn’t a good reason to do this.

Generally I agree. Now just talking hypotheticals: With the move from 1.0 to 2.0 we would have the unique opportunity to do such a painful move and make sure that we follow our own guidelines. I remember that circular imports were a pretty annoying when we had to chase them down so trying to keep lib clean is a good idea. It also makes it a lot easier for everyone else to follow the simple rule in the future.
