### ISSUE TITLE
Add a lower bound for the hydrogenbond distance between heavy atoms

### ISSUE THREAD

**Issue by yzhang9404** [MDAnalysis/mdanalysis#2947]
## Is your feature request related to a problem? ##

We could just choose the maximum distance between atoms when calculating hydrogen bond, could you add an option to filter the distance larger than some specific number user could put in. For example, the O-H-O distance is in [1.2, 3.2].

**Comment by orbeckst** [comment]
The output in [HydrogenBondAnalysis.hbonds](https://docs.mdanalysis.org/1.0.0/documentation_pages/analysis/hydrogenbonds.html#output) contains the distances. You can filter them once they have been generated by looking for any h-bonds whose distance (at index 4 along the second axis) is greater or equal 1.2:
```python
long_h_bonds = h.hbonds[:, 4] < 1.2
my_hbonds = h.bonds[long_h_bonds]
```
where `long_h_bonds` is a boolean array to pick out the h-bonds with distance ≥ 1.2.

The cutoff is mainly a performance setting because filtering out distances that can never be a h-bond is important to keep computation down. Shorter distances are generally not important for performance because there are so few of them. So from this perspective we are not likely to implement a special lower cutoff feature but if you can explain in more detail why this would be important we can consider it.

**Comment by orbeckst** [comment]
There have been no more comments so I will close.
