### ISSUE TITLE
Coarse-grained

### ISSUE THREAD

**Issue by alejob** [MDAnalysis/mdanalysis#301]
Hi everybody, 

I want to know if MDA is able to analyze coarse-grained output. If the answer is negative, where should I implement that, in the parser? or maybe coarse-grained analyze is out of the scope of MDA?

Cheers

**Comment by richardjgowers** [comment]
Hey Alejandro,

If it's just the trajectory of a CG simulation, then everything should work the same? I mainly use MDA for CG stuff.

I did make a version of "Universe" that coarse grains an atomistic trajectory as you read it, so it's atomistic data but looks coarse grained
https://github.com/richardjgowers/MDAnalysis-coarsegraining

**Comment by orbeckst** [comment]
@alejob – If there's a specific feature that you'd like to see then open a new issue in the tracker. We can also discuss on the user list (where you might get a broader response).

As long as something is a particle-based simulation then you should be able to use MDAnalysis to work with it. Some features in the selection language depend on specific residue names, and other code (such as hydrogen bond detection) relies on specific atom names and that may or may not work with your flavor of CG. Issue #104 might also be relevant here because it would provide a user-defined way to describe specific selections.

I am closing this issue – as I said, feel free to open new issues for specific features and make sure to say as clearly as possible what you'd like to see. Example input is particularly useful (and even better, example code/pull requests)!
