### ISSUE TITLE
MNT: Stop using ci-helpers in appveyor.yml

### ISSUE THREAD

**Issue by pllim** [MDAnalysis/mdanalysis#3017]
To whom it may concern,

If you are using https://github.com/astropy/ci-helpers in your appveyor.yml , please know that the Astropy project has dropped active development/support for Appveyor CI. If it still works, good for you, because we did not remove the relevant files (yet). But if it ever stops working, we have no plans to fix anything for Appveyor CI. Please consider using native Windows support other CI, e.g., Travis CI (see https://docs.travis-ci.com/user/reference/windows/). We apologize for any inconvenience caused.

If this issue is opened in error or irrelevant to you, feel free to close. Thank you.

xref astropy/ci-helpers#464

**Comment by IAlibay** [comment]
Thanks for giving us the heads up @pllim 👍 

Since we have azure pipelines running now, is there any reasons to keep appveyor CI going too? Pinging @tylerjereddy who probably knows most here.

**Comment by orbeckst** [comment]
Appveyor tends to be slow nowadays – it would help if we could drop it, especially in favor of Azure Pipelines, which run fast.

**Comment by tylerjereddy** [comment]
Yeah, pretty common to drop Appveyor in favor of Azure for Windows testing. I think in our case we had retained appveyor testing in CI because it was using `conda` to provide a few more test-time dependencies (so a few more code paths were getting tested maybe).

I was trying to keep Azure "pip only" to the extent possible so it was reasonably fast/clean, etc. There's no problem using `conda` in Azure if you really want to do that though; may slow you down a bit though.

I guess the thing to check is the % coverage difference between the Azure/Appveyor builds and see how much that matters.

**Comment by orbeckst** [comment]
Given how much AppVeyor tends to hold up CI nowadays, I'd be ok with dropping it right away and then open a new issue to add back conda coverage under windows.

**Comment by IAlibay** [comment]
Closing as we no longer use appveyor.
