### ISSUE TITLE
Travis failing intermittently 

### ISSUE THREAD

**Issue by richardjgowers** [MDAnalysis/mdanalysis#312]
So sometimes the CI builds fail with an error message like `/home/travis/build.sh: line 41:  6616 Killed                  nosetests`.  Restarting the job will usually make it pass though.

Example of error:
https://travis-ci.org/MDAnalysis/mdanalysis/jobs/66850464

A little googling makes me think that this is caused by file IO....

I'm going to put the nosetests in `.travis.yml` to verbose for now so we can see which tests are running when failures happen.

**Comment by richardjgowers** [comment]
`test_TS_indices (MDAnalysisTests.test_timestep_api.TestTimestep_Copy_TRR) ... /home/travis/build.sh: line 41:  6616 Killed                  nosetests -v`

So this test has made travis fail twice now....

**Comment by orbeckst** [comment]
It really is intermittent: a few builds passed but most of the 2.6 ones fail at exactly the same step that you mention. A bit annoying really.

**Comment by orbeckst** [comment]
Could this be a problem with [exhausting the 3GB memory limit](http://docs.travis-ci.com/user/common-build-problems/#My-build-script-is-killed-without-any-error). Some related suggestions at https://jira.duraspace.org/browse/DS-2292

**Comment by richardjgowers** [comment]
Could link up to #297 then

**Comment by richardjgowers** [comment]
I think making Universes and Readers `del` properly (#297) should fix this, so I'm removing 2.6 travis for a while (2.7 seems to pass?)

**Comment by orbeckst** [comment]
Ok.

**Comment by mnmelo** [comment]
I'll comment here, even though this covers multiple interrelated issues:

I'm adding a simple unit test that checks for uncollectable stuff. It has already been useful because it pointed out that using a `ChainReader` causes the readers to become uncollectable and leak.
Regular trajectories don't. I'm fixing that now.

Universe `__del__` (#297) is now implemented cleanly with the weakrefs and I will upload once the above is fixed.
`AtomGroups` now also unpickle automagically (#293). I actually found a way using `weakref.WeakSet()` that doesn't require the Universe to have a `__del__`, at least not for this feature.
I'm leaving the `Universe.__del__` in with a `pass` statement as proof of concept, but it might be better practice to leave it out?

**Comment by richardjgowers** [comment]
Sounds awesome, couple questions/points

Doesn't calling `del` on a universe require you to make sure that the trajectory is closed?  Or is `del` automatically called on all members of Universe when it is `del`'d?

With the tests, can you put them in their own file (`test_persistence.py` or something) as they're kind of a separate category.  Is it possible to test that things are deletable?  I'm working with Readers currently, and I don't want to make them immortal again by accident :)

**Comment by mnmelo** [comment]
`test_persistence.py`: Ok, I'll group them together.

There's no need to specifically close the trajectory in the `__del__` of the `Universe` because trajectories have their own `__del__`. As soon as they go out of scope that takes care of closing the respective files (as long as the implementation is careful to have a `Reader.close()` method). The `ChainReader` probably needs to lose its `__del__` to prevent that memleak I mentioned, but I'm not yet sure that's the cause.

As for the testing I'm really just loading and deleting a `Universe` and then calling `gc.collect()` and `assert`ing that nothing is left uncollected in `gc.garbage`. Because of the test environment I actually diagnosed the leak in older objects, other than the universe I had just loaded. The best would be to run this test at the very end of all tests (and still, parallelization might hide some leaks). Is there an easy way to specify this?

BTW, if you're looking for `Reader.__del()` it's defined in the base `Reader` class. There should be no need to redefine it in the individual readers unless they have exquisite requirements for resource deallocation other than just closing files. The `SingleFrameReader` base class also has it's own `__del__` but I'm taking it out since the exact same one is already inherited from `Reader` anyway.

**Comment by richardjgowers** [comment]
Yeah `SingleFrameReader` might not even need a `del` at all.  They don't keep a file handle open, (hence `close` does nothing).

Yeah I'm not sure how a test environment will play with `gc`, but even if it's just some scripts that I can run to check manually that would be a huge help.

With `Universe.__del__` just being `pass`.. is this different to not having a `del` method?  If it's identical, I'd leave it out, otherwise putting `pass` makes it look like we're changing something? (Ie. actively `pass`ing rather than letting `del` do its thing)

**Comment by mnmelo** [comment]
There's no default `__del__` action in python. We won't override anything by setting it to `pass`.
However, the presence of `__del__` *will* affect the behavior of garbage collection, since circular references containing `__del__` methods will not be collected (== will leak).

It seems best practice to me to leave it out if it's not needed. I'll also run all the tests with it on, just to be on the safe side. The `weakref` changes that were made I think are still valid for the future if a `__del__` method indeed becomes needed, and therefore I'd leave them in (together with whatever that might break, such as the possibility of `AtomGroups` becoming orphaned if their `Universes` go out of scope, as we discussed in #297).

**Comment by richardjgowers** [comment]
So the memory leak fix probably fixed this, but it used `weakref.weakset` which is a 2.7+ only feature

https://docs.python.org/2/library/weakref.html#weakref.WeakSet

I'm in favour of dropping 2.6 support now; we should be spending any effort on 3+ rather than 2.6.  This would then make 0.10.0 the last to support 2.6.

**Comment by orbeckst** [comment]
On 23 Jun, 2015, at 00:33, Richard Gowers wrote:

> So the memory leak fix probably fixed this, but it used weakref.weakset which is a 2.7+ only feature
> 
> https://docs.python.org/2/library/weakref.html#weakref.WeakSet
> 
> I'm in favour of dropping 2.6 support now; we should be spending any effort on 3+ rather than 2.6. This would then make 0.10.0 the last to support 2.6.

Ok, agreed. Can you send an email to the dev list, just to see if any other opinions are around?

Oliver

**Comment by mnmelo** [comment]
I also favor dropping 2.6 support.
If we ultimately decide not to we can probably hack our way around the `weakref` limitation: it's only the `WeakSet` that doesn't exist in 2.6. It is a very useful container that does away with the need for a `Universe.__del__`. To keep that we could just copy over 2.7's `_weakrefset.py` (~200 lines) and distribute it along with MDAnalysis. Ugly, but probably gets the job done.

**Comment by orbeckst** [comment]
On 23 Jun, 2015, at 07:15, mnmelo wrote:

> If we ultimately decide not to we can probably hack our way around the weakref limitation: it's only the WeakSet that doesn't exist in 2.6. It is a very useful container that does away with the need for a Universe.__del__. To keep that we could just copy over 2.7's _weakrefset.py (~200 lines) and distribute it along with MDAnalysis. Ugly, but probably gets the job done.

That's a backup-plan but I concur with Richard: let's spend effort elsewhere (unless we hear loud screams of dismay, which I doubt).

Oliver

**Comment by hainm** [comment]
+1 for dropping 2.6. There is new buffer protocol from 2.7.
