### ISSUE TITLE
PPC64LE

### ISSUE THREAD

**Issue by jimboid** [MDAnalysis/mdanalysis#3127]
Hi folks. I compile codes for a large consortium of users across many HPC architectures in the UK. I've got a user that has requested to install mdanalysis into a conda env that she uses with openmm on ppc64le. 

I have noticed that there is no ppc64le version on conda repo's or pypi and wondered if there is a technical reason for this (like endian etc) or just that noone has access to the arch to build on, and if there's a reason I shouldn't try to do a conda build for this architecture?

Thanks

**Comment by IAlibay** [comment]
Hi @jimboid 

> I have noticed that there is no ppc64le version on conda repo's or pypi and wondered if there is a technical reason for this (like endian etc) or just that noone has access to the arch to build on

It's a case that we currently don't have any means of running CI on power arch, so we can't certify a release that would run on it.

> if there's a reason I shouldn't try to do a conda build for this architecture?

Off the top of my head, probably dependencies are going to be the biggest pain. There might be some floating point issues with the current gcc settings, but that should be relatively obvious from running the tests.

P.S. I assume this is Bede, unfortunately I don't have an allocation on it, otherwise I'd test it out :(

P.S.S. If anyone knows of a free CI solution that does include power arch, I would be happy to add it to our CI infrastructure.

**Comment by IAlibay** [comment]
Minimal support was added in #3149, I'm leaving this PR open as we haven't tested how much of our optional dependencies are covered by ppc64le.

**Comment by IAlibay** [comment]
Closing as both completed & partially abandoned - we have ppc64le wheels on conda-forge, but we have no means of testing MDAnalysis on such architecture. If this is still of interest to folks, then we would need someone to either a) work out a means to provision CI access to a ppc64le machine, or b) run tests for us regularly.
