### ISSUE TITLE
Tests for "Permission denied" fail on non-English computers

### ISSUE THREAD

**Issue by Sachty** [MDAnalysis/mdanalysis#3221]
Hello, I just installed MDAnalysis, the installation was fine, without any error. The problem is when I run the pytest commands, these are: 

## When I run this, it causes 2 errors. ##
pytest --disable-pytest-warnings --pyargs MDAnalysisTests
![Screenshot_20210406_144410](https://user-images.githubusercontent.com/79607941/113785403-adfe9600-96fc-11eb-9ce8-7b248d5665fa.png)

In the end this comes out.
![Screenshot_20210406_165548](https://user-images.githubusercontent.com/79607941/113785455-c969a100-96fc-11eb-82b8-c3200773040d.png)

 ## When I install the pytest puglin, there is no problem either.  ##
pip install pytest-xdist
![Screenshot_20210406_171345](https://user-images.githubusercontent.com/79607941/113784970-dc2fa600-96fb-11eb-8ca4-e4b31cad92a4.png)

 ## But when I run the test, I get 3 errors.  ##
pytest --disable-pytest-warnings --pyargs MDAnalysisTests --numprocesses 4
![Screenshot_20210406_172652](https://user-images.githubusercontent.com/79607941/113785741-57458c00-96fd-11eb-9b31-15445d2b0fc2.png)

In the end this comes out.
![Screenshot_20210406_174544](https://user-images.githubusercontent.com/79607941/113789350-8b707b00-9704-11eb-8138-b006f8315a4a.png)

## About installation; ##
I am using a virtual machine with linux OS (Debian 10). I have checked the installation of python, its pytest library and pip. I have also performed all the steps in order. The errors as you can see in the image mainly say "Permission denied". This is my first time participating in a project on this topic and I really want to implement it and learn more about molecular dynamics. I would appreciate if someone can guide me to solve this.

 ## Versions:  ##
MDAnalysis version: I had problems running the command to find out the version.
Python Version: Python 3.7.3
OS Version: Debian 10.9
Kernel Version: Linux 4.19.0-16-amd64

![Screenshot_20210406_185544](https://user-images.githubusercontent.com/79607941/113791707-d8a31b80-9709-11eb-8658-6dbdca4a4e77.png)

**Comment by lilyminium** [comment]
Thanks for finding this bug @Sachty -- the error is because the test assumes that it's running on an English language system, so is now dying on your computer. 

The test failure shown doesn't seem to indicate anything majorly wrong with the library installed on your computer; the test is to check that a Permission Denied error *is* raised, so the behaviour is correct. Where it's failing is that the permission denied error on your computer is "Permiso denegado" instead of "Permission denied".

However, you do mention other tests have failed. Could you screenshot or copy those for us so we can check that they're ok?

**Comment by Sachty** [comment]
Thank you very much for your response. No, it only failed those tests (with Pytest and Pytest-xdist), the screenshots I attached. The problem would be that it appears as "Permiso Denegado" because of the language of my system. I wanted to write my problem here, because in the MDAnalysis installation it said that the test shouldn't pass with any errors.

Now I know that's ok, then that won't cause any problems, when I want to make the scripts for molecular dynamics?

**Comment by orbeckst** [comment]
Your installation is fine. 

Our tests wrongly assumed that each computer speaks English. This is obviously a wrong assumption. Sorry!

The tests will need to be fixed.

**Comment by IAlibay** [comment]
This is a bit of a strange test because we capture the IOError that gets triggered, but it actually ends up triggering a `PermissionError`.

Maybe we can just try to capture the PermissionError and the error number (13) [I'm not sure if the latter is consistent in MacOS/Windows since I think it's a linux error number, but it's worth a try].

**Comment by orbeckst** [comment]
We can try checking with the symbolic error name in `errno`. Definitely better than assuming a language in the OS.
