### ISSUE TITLE
import modules to `analysis` namespace

### ISSUE THREAD

**Issue by hainm** [MDAnalysis/mdanalysis#328]
hi,

(1)
```python
In [2]: from MDAnalysis import analysis
```

I can not explore all analysis module if only importing `analysis`. I need to do

(2)
```python
from MDAnalysis.analysis import align
```

I think (1) is easier to see what's in `analysis` folder. But you, developers, might have a reason not doing this. What do you think?

Hai

**Comment by orbeckst** [comment]
I'll add the `__all__` that should make this work.

**Comment by orbeckst** [comment]
... well, that's already there (after I just added a few missing ones):
```python
__all__ = [
    'align', 'contacts', 'density', 'distances',
    'gnm', 'hbonds', 'helanal', 'hole', 'leaflet',
    'nuclinfo', 'psa', 'rms', 'waterdynamics',
    'x3dna',
]
```

Since 0.10.0 we do not import everything right away and let the user only import what she needs. This avoids additional imports that are not necessary but admittedly makes introspection harder. You can do
```python
from MDAnalysis.analysis import *
```
(although I wouldn't recommend it).

Bottom line: I'm afraid you need to look at `MDAnalysis.analysis.__all__` to see what's there (or look at the docs).
