### ISSUE TITLE
Remove "new" from DCD module

### ISSUE THREAD

**Issue by richardjgowers** [MDAnalysis/mdanalysis#337]
The DCD coordinate module uses the `new` module which is deprecated since 2.6.

https://docs.python.org/2/library/new.html

The imports to the DCD Reader class from the external C code need rejigging slightly to not use `new`.

This is blocking #260

**Comment by kain88-de** [comment]
I'm not very familiar with `new` what rejingling would be required? To me it looks like I can make them simple class members with.

```python
def _read_dcd_header(*args):
    return _dcdmodule.__read_dcd_header(*args)
```

Or does `new` something else then just adding a function to the class?

**Comment by orbeckst** [comment]
@kain88-de , do you want to give it a try? Once the unit tests pass and `new` is gone you're done ;-).

**Comment by richardjgowers** [comment]
Sorry, I used a word that isn't a word, to rejig is to rearrange.

Basically the usage of module "new" needs removing, but no functionality
needs changing

**Comment by kain88-de** [comment]
Ok my naive approach doesn't work. This is because you found a way to define a python class in pure python AND C. Which is either very much discouraged or not allowed anymore, I could find any information how to do this without new.

Most of the methods in dcd.c assume that they are already an instance method. Which means I can't call them as normal functions. This would mean all of these function need to be refactored to be called as single functions. Then my approach will work. I don't have much experience writing raw cpython. For me a rewrite in cython is better but that would take a while.

**Comment by richardjgowers** [comment]
I think `new` was made obsolete in favour of `types`, maybe if you used `types.MethodType`?  Something like `DCDReader.method = types.MethodType(_dcd.function)`

https://docs.python.org/2/library/types.html#types.MethodType
