### ISSUE TITLE
PDBParser does not save charges.

### ISSUE THREAD

**Issue by PicoCentauri** [MDAnalysis/mdanalysis#3418]
## Is your feature request related to a problem? ##
I have a PDB file containing charges according to format given in the documentation of the class. 

https://github.com/MDAnalysis/mdanalysis/blob/39850215eae5a3e2c9d28a24dbc670646e305f79/package/MDAnalysis/coordinates/PDB.py#L209-L213

However, charges are not saved as the feature was removed in 0.14 

https://github.com/MDAnalysis/mdanalysis/blob/39850215eae5a3e2c9d28a24dbc670646e305f79/package/CHANGELOG#L1540

which is also correctly stated in the documentation of the parser. Most likely, there was a reason for removing the feature but I didn't found any related issue or pr...

## Describe the solution you'd like ##

PDBParser should save charges.

## Describe alternatives you've considered ##

Leave as it is but make the docs clearer and put the lack of charge parsing at a more prominent position.

**Comment by IAlibay** [comment]
I wasn't around for the removal of charges, but I think the biggest issue here is that 1) we don't have a nice way to store formal charges in universes (maybe that's fixed with RDKit? would need checking), 2) PDB files are pretty bad at providing a full record of formal charges.

Probably a related issue here, the MMTF parser will read formal charges - but into "Charges", I personally think that's a bit problematic since we usually associate "Charges" with partial charges.

**Comment by orbeckst** [comment]
I can't remember why we removed charges — not sure where the discussion is.

Given that I don't know what my opinion X years ago was, I can just look at this problem with fresh eyes and say that I don't see it as a problem to load the formal charges into charges because if you have a PDB then that's the only information that you have and it won't collide with partial charges. It would be useful when scanning the PDB and wanting to identify ions (?).

Furthermore, if it's information provided in the PDB we should make it available (and making it consistent with MMTF is also good).

**Comment by IAlibay** [comment]
> I don't see it as a problem to load the formal charges into charges because if you have a PDB then that's the only information that you have and it won't collide with partial charges. It would be useful when scanning the PDB and wanting to identify ions (?).

I'm not going to fight for this strongly either way, but personally I would prefer we implement a new topology attribute for it - especially given @lilyminium's work on arbitrary topology attribute selections.

Main reasoning is:
1) I can see a case where someone loads in a PDB and generates partial charges with an external method (RDKit, something else, etc..), and now you end up with both partial charges and formal charges competing for the same topology attribute.
2) Ambiguity on what `.charges` is doesn't really serve much purpose? I can't see the benefit of having folks try to remember what their charge type is if we can just separate it out.

**Comment by PicoCentauri** [comment]
Thanks for your replies.

I am happy with both. If you decide what kind of attribute we would like to add I can create a PR.
