### ISSUE TITLE
Add python 3.10 support

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/mdanalysis#3457]
As per every year - a new python version is out. We should add it to the test matrix and see if anything breaks.

**Comment by tylerjereddy** [comment]
I was able to build MDAnalysis on Windows Python 3.10 and run most of the test suite on my fork: https://github.com/tylerjereddy/mdanalysis/pull/12

Test results were: `7 failed, 16982 passed, 384 skipped, 2 xfailed, 2 xpassed, 69147 warnings in 968.47s (0:16:08)`

I find it confusing that many tests were skipped because `h5py` was absent, but some tests failed because they have an obligate requirement on `h5py`. I guess my question is--what tests are right?

**Comment by tylerjereddy** [comment]
The other failures are in tests that count the number of warnings in certain situations--I suppose that shouldn't be too surprising--this is bound to change if you bump Python/dependency versions sometimes.

**Comment by IAlibay** [comment]
Currently python 3.10 cannot be used with all our optional dependencies. Currently the following libraries do not have a py3.10 release: `chemfiles-python`, `rdkit`, and `openmm`.

In #3458 I have added to CI a minimal dependency check for py3.10, so at least we know that it _works_ on base MDAnalysis. Once the above dependencies release py3.10 versions we can add a CI check for the full dependency set.

**Comment by IAlibay** [comment]
This is now complete, py310 is working fine in CI will all optional deps.
