### ISSUE TITLE
DistanceMatrix accept AtomGroup

### ISSUE THREAD

**Issue by lilyminium** [MDAnalysis/mdanalysis#3486]
## Is your feature request related to a problem? ##

Is there any reason DistanceMatrix cannot accept an AtomGroup inplace of a Universe? This would help with atomgroups created through non-selection-string ways, which you then need to re-create with atom indices. e.g.
https://groups.google.com/g/mdnalysis-discussion/c/ad4HW_6w2MM/m/-h3bRDv0DgAJ?utm_medium=email&utm_source=footer 

## Describe the solution you'd like ##

Here: https://github.com/MDAnalysis/mdanalysis/blob/5bf6359a821c085a1039ca414ce51ca2820722fb/package/MDAnalysis/analysis/diffusionmap.py#L251-L253

```diff
- universe.trajectory
+ universe.universe.trajectory
```

**Comment by richardjgowers** [comment]
AtomGroup is probably preferable everywhere to Universe as an argument
imho. Universe means a lot of things, AG is clearer.

**Comment by ceaserbutdumb** [comment]
Hey, I am a beginner here so could you guide me to what I can do to solve this issue?

**Comment by IAlibay** [comment]
@ceaserbutdumb in the first instance the minimal change required here would be to just change the documentation and `__init__` code to allow for an `AtomGroup` to be used instead of `universe`. For the most part it _should_ work as-is, but you'll need to add some test to make sure that it does what it should do.

It's hard for us to give specific guidance about these things, if you can open a pull request with an attempt at achieving this task, then we can try to help push the pull request along towards a merge.

**Comment by ceaserbutdumb** [comment]
@IAlibay I will try to work on it and thank u for the help

**Comment by ceaserbutdumb** [comment]
@lilyminium  I am getting an Attribute error when using `universe.universe.trajectory` saying that it does not exist

**Comment by ceaserbutdumb** [comment]
@lilyminium  shouldn't here we have `Universe.trajectory` instead of `universe.trajectory`

**Comment by IAlibay** [comment]
> @lilyminium shouldn't here we have `Universe.trajectory` instead of `universe.trajectory`

@ceaserbutdumb may I ask you that you do not write comments and then delete them please? Especially when you ping an individual directly this makes it difficult for us to work out what happened (i.e. we get an email notification but there's no comment when we attempt to reply on github).

**Comment by ceaserbutdumb** [comment]
> > @lilyminium shouldn't here we have `Universe.trajectory` instead of `universe.trajectory`
> 
> @ceaserbutdumb may I ask you that you do not write comments and then delete them please? Especially when you ping an individual directly this makes it difficult for us to work out what happened (i.e. we get an email notification but there's no comment when we attempt to reply on github).

I am sorry

**Comment by abhik-123** [comment]
@IAlibay I am new to open source and i wish to contribute in this project. Could you please suggest how should I begin? 
I am good at coding in python

**Comment by IAlibay** [comment]
> @IAlibay I am new to open source and i wish to contribute in this project. Could you please suggest how should I begin? I am good at coding in python

In the first instance I would recommend our user guide as your first point of call for getting to know MDAnalysis: https://userguide.mdanalysis.org/stable/index.html. The user guide includes a section on how to contribute to the project.

I would ask that questions about how to get started / how to contribute / etc... be asked on the MDAnalysis mailing lists or our discord server rather than issues. Please see here for more details: https://www.mdanalysis.org/#participating.

If you have questions specific to this particular issues, then please do ask them here.

**Comment by AnirG** [comment]
Hey @richardjgowers @lilyminium! 

> AtomGroup is probably preferable everywhere to Universe as an argument
> In the first instance the minimal change required here would be to just change the documentation and __init__ code to allow for an AtomGroup to be used instead of universe.

I'm not completely sure how this can still work. Without the universe passed on as a parameter, how can trajectories be looped over to update our AtomGroup which is needed to calculate pairwise metrics?
Apologies if it's a naive question, I'm kinda new to this stuff.

**Comment by richardjgowers** [comment]
@AnirG `AtomGroup.universe.trajectory`

**Comment by AnirG** [comment]
@richardjgowers Ah cool, I see! I can possibly try to work on this one. I will also try to code up some test cases. Should the changes and test cases be raised in a single PR?

**Comment by IAlibay** [comment]
> @richardjgowers Ah cool, I see! I can possibly try to work on this one. I will also try to code up some test cases. Should the changes and test cases be raised in a single PR? 

Yep, our standing contribution model is that all new code is matched with tests before we merge things.

**Comment by IAlibay** [comment]
@AnirG - I see that you're attempting to simultaneous work on two issues. May I suggest that you start with one and then do the other? There's always a learning curve to being a new contributor to a project and it's usually easier to go one at a time rather than trying to have similar discussions across two PRs.

**Comment by AnirG** [comment]
@IAlibay yeah sure, I just shortlisted those to work on and get an idea. Of course, I'll go one at a time.

**Comment by AnirG** [comment]
@IAlibay @richardjgowers @lilyminium hey! looks like `Universe` can be completely replaced with `AtomGroup` in the `DistanceMatrix` class. I compared the existing `dist_matrix` with one which takes` AtomGroup` and it seems to work fine. I'm not very sure about what kind of and how test cases are to be coded and tested.

**Comment by Nitin-patil2209** [comment]
Hi I want to contribute for this issue can you give me a little bit information about this issue.
