### ISSUE TITLE
NetworkX DeprecationWarning: `from_numpy_matrix`

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/mdanalysis#3536]
test_leaflet.py throws the following warning:

```
DeprecationWarning: from_numpy_matrix is deprecated and will be removed in NetworkX 3.0.
  Use from_numpy_array instead, e.g. from_numpy_array(A, **kwargs)
```

MDA version: 2.1.0-dev0

**Comment by jbarnoud** [comment]
It appears we do not explicitly call the deprecated function. Instead, the released version of networkx still relies on it in one place: https://github.com/networkx/networkx/blob/f4b528e230c6faadd5a2d426b39c29a0a165c38c/networkx/convert.py#L144

Therefore, the issue seems to come from upstream, but it also appears that it is fixed in the main branch of networkx: https://github.com/networkx/networkx/blob/e308b80f17264b89acf8defe185c71c6656d5105/networkx/convert.py#L143

**Comment by IAlibay** [comment]
thanks for looking into this @jbarnoud
