### ISSUE TITLE
hole run CG pdb file error

### ISSUE THREAD

**Issue by yang-guoli** [MDAnalysis/mdanalysis#3673]
## Expected behavior ##

![image](https://user-images.githubusercontent.com/73353085/169634426-feeba1e6-67ec-4c1a-a0d1-32098e98a4e4.png)

## Actual behavior ##

![image](https://user-images.githubusercontent.com/73353085/169634437-4d5736a2-5d47-4fd0-b80a-fc33f48ee403.png)

## Code to reproduce the behavior ##

``` python
import MDAnalysis as mda
from MDAnalysis.tests.datafiles import PDB_HOLE
from MDAnalysis.analysis import hole2
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline
mda.start_logging()

pdb = './hypersound_10.pdb' ## CGpdb
u = mda.Universe(pdb)
with hole2.HoleAnalysis(u ,executable='./hole2/exe/hole') as h2:
    h2.run()
    h2.create_vmd_surface(filename="hole_surface.vmd")

pdb = './final_cg2at_aligned.pdb' ##AApdb
u1 = mda.Universe(pdb)
with hole2.HoleAnalysis(u1 , executable='./hole2/exe/hole') as h2:
    h2.run()
    h2.create_vmd_surface(filename="hole_surface.vmd")
.... 

```

## Current version of MDAnalysis ##

- Which version are you using? (run `python -c "import MDAnalysis as mda; print(mda.__version__)"`)
- 
![image](https://user-images.githubusercontent.com/73353085/169634537-9aac0419-d5d2-476d-921d-0c1486b5dd55.png)

- Which version of Python (`python -V`)?
- 
![image](https://user-images.githubusercontent.com/73353085/169634552-821cb780-f0bc-4346-8a69-c5567cf8f5b6.png)

- Which operating system?
- ubuntu 22.04

**Comment by orbeckst** [comment]
From your issue report it is not clear to me what you're running HOLE on. It would help if you wrote the "expected" in words.

If you're using a MARTINI (or other CG) system then it's likely not working because HOLE does not know how to deal with the CG particles. You'd need to provide a custom HOLE radii file for the kwag `vdwradii_file` with [HoleAnalysis](https://docs.mdanalysis.org/stable/documentation_pages/analysis/hole2.html#MDAnalysis.analysis.hole2.hole.HoleAnalysis) that translates atomnames to radii. You can use the [MDAnalysis.analysis.hole2.utils.write_simplerad2()](https://docs.mdanalysis.org/stable/documentation_pages/analysis/hole2.html#MDAnalysis.analysis.hole2.utils.write_simplerad2) function to write an example radii file to see what the format is
```python
MDAnalysis.analysis.hole2.utils.write_simplerad2('example.rad')
```
or look through the documentation for HOLE to learn about the format.

**Comment by yang-guoli** [comment]
@orbeckst Thanks i will try

**Comment by orbeckst** [comment]
I don't think we can really do anything about this issue so I am closing it. If there's anything specific that you think MDAnalysis should be doing then please leave a comment and we can re-open. We'd also be keen to hear if you found a working solution that could be added to documentation.
