### ISSUE TITLE
make type checking in CI blocking

### ISSUE THREAD

**Issue by jbarnoud** [MDAnalysis/mdanalysis#3699]
This issue depends on #3698 which requests mypy and pyright to be run in CI to check type annotations. This issue suggests making the job non-blocking as type annotation is not yet implemented. Once the annotations are implemented to a point where the checking job passes, it should be made blocking to avoid breaking the existing annotations and to avoid introducing new broken ones.

This is part of @umak1106's outreach project.

**Comment by tylerjereddy** [comment]
You could also make it blocking from the start with an appropriate `mypy.ini` file that ignores errors in all paths, and then start to peel away those configured ignores for "progressive" enforcement so that you don't lose ground as you go.

For example, in another project I work on there's a problematic path where we don't have hints working yet so we do i.e.,:

```
# pydarshan modules that lack types
# or currently have errors

[mypy-darshan.backend.cffi_backend]
ignore_errors = True
```

But everything else is enforced. You can asterisks to broadly ignore paths at first and peel back from there.

**Comment by jbarnoud** [comment]
In that case, are the error still displayed in the report? If so, it is indeed a better solution.

**Comment by tylerjereddy** [comment]
The report is silent/clean when you ignore errors. So, if MDAnalysis had say 15 submodules that were ignored in the config file you wouldn't see any output, but when you are working on adding types to a submodule you could delete the ignore entry in the config file and the errors will show up until you fix them all in that part of the code.

Maybe that isn't exactly what you want, but seems to work well enough for me at least.

**Comment by jbarnoud** [comment]
It probably is the best solution for CI. @umak1106 will have to run mypy locally anyway and can be more stringent there.

**Comment by IAlibay** [comment]
It'll obviously be up to @jbarnoud et al. as reviewers / mentors, but I like @tylerjereddy's suggestion, it would make it a lot easier for those of us not directly involved to keep track of progress.
