### ISSUE TITLE
Inconsistent copyright/citation in file calc_distances.h

### ISSUE THREAD

**Issue by hmacdope** [MDAnalysis/mdanalysis#3717]
## Expected behavior ##

Code files should all have the same copyright header and list the same copyright year/citations.

## Actual behavior ##

In `calc_distances.h` the copyright year is listed as 2014, rather than 2017 as in most other headers.
Additionally it and only cites the 2011 J. Comp chem paper, whereas  most others also cite the 2016 Scipy proceedings paper.  

## Additional Query ##

Do we want to update the Copyright year at all? 2017 was a while ago.

**Comment by orbeckst** [comment]
We have to update this everywhere at some point. It's just such an intrusive change in the history that affects all open PRs that we basically never want to do it... probably ought to have done it prior to 1.0.

If this is an outlier then adjust it to the same as everything else so that when we do an automated rewrite, we don't miss this one.
