### ISSUE TITLE
Renaming topology methods

### ISSUE THREAD

**Issue by richardjgowers** [MDAnalysis/mdanalysis#373]
So currently `AtomGroup.angle` returns the size of an angle between 3 atoms in the AtomGroup, whilst `AtomGroup.angles` returns the angles within the AtomGroup.  I think we need to rename the methods that give a size, so proposed changes:

``` python
AtomGroup.bond() -> AtomGroup.bond_length()
AtomGroup.angle() -> AtomGroup.angle_size()
AtomGroup.dihedral() -> AtomGroup.dihedral_size()
AtomGroup.improper() -> AtomGroup.improper_size()
```

I'm a little unsure of the names, `bond_length` seems right, but `angle_size` seems awkward.

Then TopologyGroup methods would get a similar treatment

``` python
TopologyGroup.bonds -> TopologyGroup.bond_lengths()

 # which leads to the more aesthetically pleasing
AtomGroup.bonds.bond_lengths()
```

**Comment by mnmelo** [comment]
I guess the correct term would be `angle_amplitude`(likewise for `dihedral` and `improper`). This would be clearer, and has my vote, but maybe a bit long to type?

**Comment by orbeckst** [comment]
One could use `angle_degrees` although amplitude is more meaningful. 

Also, I'd actually like `AtomGroup.bonds.lengths` better as it has less redundancy and we could deprecate `AtomGroup.bond_lengths`.

**Comment by dotsdl** [comment]
To carry on @orbeckst idea, is it desirable to remove ``bond``, ``angle`` and ``dihedral`` convenience methods from the ``AtomGroup`` definition entirely, and instead promote the use of:

``atomgroup.bonds.values``
``atomgroup.angles.values``
``atomgroup.dihedrals.values``

which would each return an array of values equal to the length of each object they correspond to. That is, the ``bonds.values`` returns the bond lengths for every bond in the ``TopologyGroup`` of bonds? The use of a ``values`` property is consistent with e.g. ``pandas.DataFrame`` to access a numpy array of the raw numerical elements, and avoids inconsistent nouns like ``lengths`` for bonds and ``degrees`` for angles.

On the other hand, this will require:
* bonds to be guessed for the atomgroup if they don't already exist from the topology
* ``atomgroup.torsions`` will need to be changed to ``atomgroup.dihedrals``

**Comment by dotsdl** [comment]
The above use of ``values`` as the property for getting back the values avoids the problem of ``TopologyGroup``s that have a mixed set of members, such as some bonds, some angles, and/or some dihedrals.

**Comment by richardjgowers** [comment]
I did think of removing the methods from AtomGroup, but there's lots of stuff in analysis that uses 4 size AtomGroups as dihedrals, and there's nothing wrong with this workflow.  When you've not got bonds in your topology it might be the easiest way to select the dihedrals.  Although, all it would force would be:
``` python
from MDAnalysis import Torsion  # move TopologyObjects into top namespace

# renaming Torsion class probably..
dih = Torsion(*ag)

dih.dihedral()
```

I like @dotsdl 's idea for a generic "do it" method for TopologyGroup, `values` seems sane enough.

To clarify a few things:
If there's no bonds in the topology, then `atomgroup.bonds` will be zero length, so I *think* `ag.bonds.values()` will just return a zero size array.  We have got the `guess_bonds` method on AtomGroup in place, linking the two might get confusing though.

TopologyGroups can't have mixed types currently (so only Bonds, or only Angles etc).

**Comment by orbeckst** [comment]
It should always be possible to call `ag.dihedrals` on any 4-atom group. This is important for, e.g. pseudo-dihedrals in nucleic acids. By the same token, it should always be possible to quickly get angles and distances ("bond") between 3 and 2 element AtomGroups.

**Comment by dotsdl** [comment]
@orbeckst ah, I agree these convenience methods should be kept then.

**Comment by orbeckst** [comment]
How much slower would it be to generate a `topology.core.Bond` for the "bond" formed by the two-atom `AtomGroup` `ag` so that 

```python
ag.bond.values
```
would produce what currently 

```python
ag.bond()
```

does? (And of course for `angle`, `dihedral`?)

As a bonus, you get a bona fide `Bond` (or `Angle` or `Torsion`) for any suitable collection of atoms.

**Comment by orbeckst** [comment]
Hm, there might be some caching at work because making the `Bond` instance and getting its length is 7 times faster than calculating the length from the atom group itself ;-):

```
import MDAnalysis; from MDAnalysis.tests.datafiles import PSF, DCD
u = MDAnalysis.Universe(PSF, DCD)
ag = u.atoms[:2]

%timeit MDAnalysis.topology.core.Bond(ag).length
# 100000 loops, best of 3: 7.83 µs per loop

%timeit ag.bond()
# 10000 loops, best of 3: 42.2 µs per loop
```
I think @richardjgowers needs to jump in and say how to make this a fair comparison.

**Comment by richardjgowers** [comment]
Hmm, I like the idea of making `ag.bond()` spit out a `Bond` object, which you can play with as you want. So
``` python
b = ag.bond()
b.length()

# or
bondgroup = ag.bond() + ag2.bond()
bondgroup.values()
```

Having it return the `Bond`s means you can easily access the C functions, (which is what `values()` uses).


I'm getting caching too which is annoying, but the Bond class just holds a pointer to the two Atom objects, so is essentially just a skinny AtomGroup


** Everything above is equally applicable to Angle, Torsion/Dihedral etc

**Comment by orbeckst** [comment]
I would make `AtomGroup.bond` a managed property instead of a method. I think you'd always want to behave it like an object.

For `bond.values()` I am of two minds: Do we need a keyword to enforce or decline the use of PBC for the calculation? For real bonds and angles a user would probably always want the shortest length but for arbitrary "bonds" this might be less clear. We could, however, simply put in the docs for `Bond.values` that it will *always take PBC into account* and then I think a property produces less clutter than a method.

**Comment by mnmelo** [comment]
Since `bond.values()` is already a method, adding a keyword with a default seems pretty simple.
We can make it default to `None`, in which case `core.flags['use_pbc']` is used.

One other remark: if `bond` is a `topology.core.Bond` instance (not a `TopologyGroup` one) shouldn't the method be singular? As in `bond.value()`? Or did I miss some discussion on these names?

It's then useful to have plural<->singular lookup tables, as already exist for `Atom` vs `AtomGroup` methods (the existing tables can just be extended to accommodate the topology lexicon too).

**Comment by richardjgowers** [comment]
I think the use case of having fake bonds (end to end distance between two points) means you don't always want PBC, and that there's an actual calculation taking place (it's not just retrieving info.) makes me think that it should be a method.

With the AtomGroup to Bond conversion, would something like `AtomGroup.to_bond` or `AtomGroup.as_bond` read better?
``` python
ag = u.atoms[10] + u.atoms[25]
ag.as_bond.length()
ag.as_bond.value()
```

**Comment by orbeckst** [comment]
@mnmelo : I might have just typed hastily: as you say, `bond.value()` makes more sense.

@richardjgowers : I thought about `ag.as_bond`, too, and while I agree that it is semantically more accurate, I think in practice it won't make a difference in users' understanding of what `ag.bond` does — and the latter is shorter and more concise and I immediately see it as an object.

(numpy uses `obj.asarray()` so there's certainly precedent for your suggestion, too.)

**Comment by orbeckst** [comment]
Also, let's go with both your considerations and make `Bond.value()` a method.

I liked @dotsdl 's suggestion to use `value()` or `values()` as a common method for topology entities and `TopologyGroup`.

**Comment by richardjgowers** [comment]
Ok so to recap decided and undecided things:

To change:
 - all TopologyObjects yield their result via `value` method
 - all TopologyGroups yield their results via `values` method
 - add value/values as a singular/plural pairing
 - `AtomGroup.bond` yields a TopologyObject as a property (but name undecided)

For discussion:
 - `Dihedral`s or `Torsion`s throughout the package
 - `AtomGroup.as_bond` or `AtomGroup.bond`

**Comment by orbeckst** [comment]
For the discussion points:

1. I like `Dihedral` better than `Torsion` (partly that's what they are called in the force fields that I am most familiar with) and on Wikipedia [Torsion angle](https://en.wikipedia.org/wiki/Torsion_angle) just redirects to [Dihedral angle](https://en.wikipedia.org/wiki/Dihedral_angle).
2. I prefer `AtomGroup.bond` because it immediately sounds like an object whereas `AtomGroup.as_bond()` sounds more like a method that returns something. Given that it will often be used as `ag.bond.value()`, I find the simple `bond` more readable.

Any other opinions?

**Comment by dotsdl** [comment]
I dig it. I think this is what we're honing in on:

``AtomGroup.bond`` -> property yielding ``Bond`` object; raises exception if ``len(AtomGroup) != 2``
``AtomGroup.angle`` -> property yielding ``Angle`` object; raises exception if ``len(AtomGroup) != 3``
``AtomGroup.dihedral`` -> property yielding ``Dihedral`` object; raises exception if ``len(AtomGroup) != 4``

and at the very least:
``TopologyObject.value`` -> property yielding the value (bond length, angle size, dihedral size, depending on the type of ``TopologyObject``)

And we also want:
``AtomGroup.bonds`` -> property yielding ``TopologyGroup`` with all bonds in the ``AtomGroup``
``AtomGroup.angles`` -> property yielding ``TopologyGroup`` with all angles in the ``AtomGroup``
``AtomGroup.dihedrals`` -> property yielding ``TopologyGroup`` with all dihedrals in the ``AtomGroup``

and at the very least:
``TopologyGroup.values`` -> property yielding a numpy array of values giving the ``Bond``s, ``Angle``s, or ``Dihedral``s it contains, in order. Equivalent of ``np.array([item.value for item in topgroup])``.

Something I don't know the answer to: for topologies in which we already have bonds, we're good. But for topologies without explicit connectivity defined, do we require a call to ``AtomGroup.guess_bonds()`` first, or would it be useful to have the `AtomGroup` guess bonds automatically on first call to any of the properties that return a `TopologyGroup`?

**Comment by richardjgowers** [comment]
Ok so I think @dotsdl has everything in that list now, PR incoming.

I'm reluctant to do the automatic guessing because it would look and behave very ugly, so I'll leave it out for now, but maybe I'll get convinced later.

**Comment by richardjgowers** [comment]
Ok I've made the changes, but not docs yet.

I moved all the topology classes from `topology.core` into `core.topologyobjects`.  There were lots of circular imports between `AtomGroup` and `topology.core` and this fixed it.  The only problem is I couldn't find a nice name, `core.topology` is confusing because we have `topology.core`.  Maybe `core.bonding`

**Comment by orbeckst** [comment]
Two comments on @dotsdl 's list

1. I agree with @richardjgowers to not start guessing. Just complain for right now.
2. `value()` and `values()` should probably be methods (see discussion above) because of things like keyword `pbc=True`. At least that seems necessary for the arbitrary bonds, angles, dihedrals and for consistency, real Topology objects should then also have a method. Admittedly, it's not 100% satisfying but I don't see a better solution.

**Comment by tylerjereddy** [comment]
Can one of the developers involved please add a few examples of this API change / enhancement to the migration guide on the wiki? I've created a [Renamed topology methods] (https://github.com/MDAnalysis/mdanalysis/wiki/MDAnalysis-0.11-unifying-release-user-guide#renamed-topology-methods) section, so a few before / after 0.11 examples would be helpful. When that is done, could you also indicate this in the table in https://github.com/MDAnalysis/mdanalysis/issues/381.

**Comment by richardjgowers** [comment]
Yep I'm on this

**Comment by richardjgowers** [comment]
Ok I think I've finished this now
