### ISSUE TITLE
Calculate angles

### ISSUE THREAD

**Issue by hl2500** [MDAnalysis/mdanalysis#3979]
Hello, I'm wondering if there is an easy way to calculate angles and dihedrals of any set of atoms? Thanks.

**Comment by IAlibay** [comment]
Hi @hl2500 - this question is best asked on our user mailing list (https://groups.google.com/group/mdnalysis-discussion) rather than our issue tracker.

What you are likely looking for here is the functionality under MDAnalysis.lib.distances, specifically [calc_angles](https://docs.mdanalysis.org/stable/documentation_pages/lib/distances.html#MDAnalysis.lib.distances.calc_angles) and [calc_dihedrals](https://docs.mdanalysis.org/stable/documentation_pages/lib/distances.html#MDAnalysis.lib.distances.calc_dihedrals).

**Comment by IAlibay** [comment]
Apologies if this looks blunt, since this is a usage issue I'm going to close this as completed. I encourage you to reach out either on the mailing list or over discord if you have any further queries regarding this. Please see here for more details: https://www.mdanalysis.org/#participating

**Comment by hl2500** [comment]
> Hi @hl2500 - this question is best asked on our user mailing list (https://groups.google.com/group/mdnalysis-discussion) rather than our issue tracker.
> 
> What you are likely looking for here is the functionality under MDAnalysis.lib.distances, specifically [calc_angles](https://docs.mdanalysis.org/stable/documentation_pages/lib/distances.html#MDAnalysis.lib.distances.calc_angles) and [calc_dihedrals](https://docs.mdanalysis.org/stable/documentation_pages/lib/distances.html#MDAnalysis.lib.distances.calc_dihedrals).

Thanks!
