### ISSUE TITLE
[ENH]: Change MSD code to accumulate values using `.timeseries`.

### ISSUE THREAD

**Issue by hmacdope** [MDAnalysis/mdanalysis#3993]
## Is your feature request related to a problem? ##

The MSD code currently uses a custom loop to collect positions  in `_run()` and then calculates the actual MSD in `_conclude`. The loop over ts.positions is the same as that handled by  `.timeseries` so we could probably streamline it. 

## Describe the solution you'd like ##

This could be made more streamlined using `.timeseries` to replace the _run() loop.

**Comment by MohitKumar020291** [comment]
I want to contribute to this issue but do not have any idea about the mathematics getting used in MSD(mean square deviation).
But what I have understood after reading this issue is that there a loop use to know the different positions called  `_run()` then transfers it to `_conclude` (is `conclude()` wrong , I am just invoking it) for calculation of actual MSD. So, now we want to replace `.timeseries` (which will be faster than `_run`) with `_run()`.
@hmacdope , kindly guide me throughout the issue , what will be the next step after the above improvements/progress. I am totally beginner to MDAnalysis as well as to college mathematics. But have good desire to work on issues and have experience in python programming.

**Comment by MohitKumar020291** [comment]
@hmacdope I had made some changes can you please give me `commands for tests`.

**Comment by MohitKumar020291** [comment]
@hmacdope had done some changes [](https://github.com/MDAnalysis/mdanalysis/pull/4004)

**Comment by MohitKumar020291** [comment]
@hmacdope  tried my best https://github.com/MDAnalysis/mdanalysis/pull/4004 forgive if any mistake I am a beginner.

**Comment by MohitKumar020291** [comment]
@hmacdope please review it(https://github.com/MDAnalysis/mdanalysis/pull/4006) again , thanks for guiding.

**Comment by ooprathamm** [comment]
@hmacdope made a pull request for the same (#4013). I hope this is what you asked for.
NOTE - somehow running the test case as given in docstrings gives different results.

**Comment by hmacdope** [comment]
@ooprathamm I have reviewed, have a look on the PR.

**Comment by chandra20500** [comment]
Hi @hmacdope @ooprathamm I want to work on this issue could you please assign this to me.

**Comment by SophiaRuan** [comment]
Hi @hmacdope, I made some revises last week. Could you have a look and give me some advices? Thank you so much! https://github.com/MDAnalysis/mdanalysis/pull/4028

**Comment by orbeckst** [comment]
@hmacdope while looking through @SophiaRuan 's PR #4028 I wondered how you'd handle `run()` if `_single_frame()` is removed? One could make `_single_frame()` just `pass` but then we'll iterate through the trajectory *twice*.  The other thing is that with the proposed implementation we loose (or have to reimplement) handling of `run(frames=[list of frames])` (I am not 100% sure if `frames` is so useful with MSD but there might be legitimate use cases for subsampling part of a trajectory and using masks instead of start/stop/step). We also loose the progress bar when using `timeseries`.

On that note, should we have progress bars in `_conclude()` given that this is compute-heavy?

**Comment by hmacdope** [comment]
That is a really good point I hadn't thought about that I can't see an easy way around. Perhaps best to can this whole idea? Doesn't make sense to go through trajectory twice  as very slow.

**Comment by MohitKumar020291** [comment]
@orbeckst @hmacdope I may be wrong but can we create a new method into analysisbase class which is similar like `run` but do not use `_single_frame` but then `test_msd.py` will also changed. But then another questions rises what about `frames`?

**Comment by orbeckst** [comment]
@MohitKumar020291 we could change AnalysisBase, as you suggest. However, introducing complexity tends to make code more error-prone, harder to understand, and — and that's the most important point — harder to maintain. If we had multiple analysis cases where we'd need a changed AnalysisBase then it might be worthwhile doing that. But just doing it for one case is not worth it.

**Comment by SophiaRuan** [comment]
@orbeckst @hmacdope I am not sure about how to make `_single_frame` pass as it was defined in the `Analysisbase`. Does that mean I need to change the `run()` in `base.py`? But in this way, I will change the class which may affect other classes for other analysis other than MSD.

**Comment by orbeckst** [comment]
I am tending towards closing this issue without implementing the suggested change. What do you say, @hmacdope ?

@SophiaRuan and @MohitKumar020291 I am apologizing to you because we clearly didn't think the whole thing through in advance. On the other hand, you now witness in real time how important it is to try out new solutions with actual code and constantly evaluate them. PR #4028 really made the full implications clear to me (especially @SophiaRuan 's question about `_single_frame` on the PR). 

If we are closing the issue, then I suggest we replace it with a new issue to add a progressbar to the processing in `_conclude()`.

**Comment by hmacdope** [comment]
Yes sadly I didn't think this through properly. Many apologies to @SophiaRuan and @MohitKumar020291 I agree with @orbeckst, we can change the issue.

**Comment by SophiaRuan** [comment]
Hi @hmacdope @orbeckst @MohitKumar020291, I will close the PR. I want to apply for this year's MDAnalysis project, so I will try to solve another issue. Thank you for the help from all of you!

**Comment by SophiaRuan** [comment]
@hmacdope @orbeckst Or I can see how you will change the issue and if I can work on the changed issue.

**Comment by orbeckst** [comment]
I'll close the issue. @hmacdope can you open a follow-up — that's cleaner than updating this one.

**Comment by hmacdope** [comment]
> 



> I am tending towards closing this issue without implementing the suggested change. What do you say, @hmacdope ?
> 
> @SophiaRuan and @MohitKumar020291 I am apologizing to you because we clearly didn't think the whole thing through in advance. On the other hand, you now witness in real time how important it is to try out new solutions with actual code and constantly evaluate them. PR #4028 really made the full implications clear to me (especially @SophiaRuan 's question about `_single_frame` on the PR).
> 
> If we are closing the issue, then I suggest we replace it with a new issue to add a progressbar to the processing in `_conclude()`.

IIRC most of the work in `_conclude` is done by `tidynamics` is it even possible to add a progressbar neatly in that case @orbeckst ?

**Comment by orbeckst** [comment]
Not sure — have a look and if there's nothing useful to be done, don't open an issue.

**Comment by hmacdope** [comment]
No I was wrong there is still a loop over particles that can have a progress bar added. I'll raise an issue.
