### ISSUE TITLE
Set `chainID` [was: `segID`] from `molblock` in TPR parser

### ISSUE THREAD

**Issue by pgbarletta** [MDAnalysis/mdanalysis#3994]
Hi,

I've been surprised by this renaming of the `molblock`'s moltype name, when setting the `segid` attribute:
https://github.com/MDAnalysis/mdanalysis/blob/363037a31d2eb208540c0f255d4aaf8e1944cf4b/package/MDAnalysis/topology/tpr/utils.py#L330

Given that there's a comment saying the naming is arbitrary and that gromacs sets molecule names as `Protein_chain_{chainID}`, could we perhaps replace that line with:
```
segid = molblock[14:] if molblock[:14] == "Protein_chain_" else molblock
```
So `segid`s get the chainID character, and if not, it just gets the original molecule's name (eg: ION, SOL, other custom names)?

**Comment by whoisrobinjha** [comment]
Hi there, I would like to contribute to this project although i am new to programming. 
Do I need to just replace the the original `segid = f"seg_{i}_{molblock}"` with `segid = molblock[14:] if molblock[:14] == "Protein_chain_" else molblock` . Please let me know.
Thanks!!

**Comment by orbeckst** [comment]
@pgbarletta did we change the segid name, and if so, when did that happen?

The main question is if your suggested change will break code.

**Comment by pgbarletta** [comment]
> did we change the segid name, and if so, when did that happen?

Sorry, I do not follow. You mean if the TPR parser used to load the `segid` attribute differently? I wouldn't know about that.

> The main question is if your suggested change will break code.

Provided that tests pass, there may also be users that rely on this behaviour. 

Something like a `rename_molblock` could be added to the [`do_mtop`](https://github.com/MDAnalysis/mdanalysis/blob/363037a31d2eb208540c0f255d4aaf8e1944cf4b/package/MDAnalysis/topology/tpr/utils.py#L288) function. The default `True` value would preserve behaviour and name the `segid` as `seg_{i}_{molblock}`, while when `False`, it would behave as proposed. 
This could be a keyword arg to the `Universe`, that gets propagated down to the [`parse`](https://github.com/MDAnalysis/mdanalysis/blob/363037a31d2eb208540c0f255d4aaf8e1944cf4b/package/MDAnalysis/topology/TPRParser.py#L181) function, which then does a `kwargs.get("rename_molblock", True)` when calling `do_mtop`

An alternative would be to leave `segid` untoched and do this behaviour onto the `chainID` attribute, but IDK if that's correct.

**Comment by IAlibay** [comment]
Do Segments even make sense in a Gromacs context? I was always under the impression that "Segments" is a CHARMM context that somehow permeated throughout the code.

Would switching to "Chain" be more useful here?

**Comment by orbeckst** [comment]
I think Segment makes more general sense than Chain because Segment can be "the lipids" or "the solvent" or "water" or "ions" whereas Chain is a polymer concept and refers to a single covalently linked molecule. I'd think that TPR blocks are best related to Segments because  each residue can only be in one block (IIRC). 

Maybe it makes sense to also set the ChainID if we detect that we get PROA, PROB etc... but that's ultimately guessing because PROA is just what pdb2gmx uses by default and you can change the ITP file if you like. In general, I've come around to Python's "withstand the temptation to guess in the face of uncertainty" so I'd leave it to the user (or specific guessers). 

Sidenote: In the atom - residue - segment hierarchy, segment is the one that is least clearly defined. It's not always a molecule (and often a "residue" is its own molecule) so perhaps we should clearly document what we consider it to be. What do our docs say @pgbarletta ?

**Comment by pgbarletta** [comment]
The UG and the recent workshop material agree that `AtomGroup` is the main way to handle atoms, while `Segment` or `SegmentGroup` is more of a handle that may or may not be useful. That is, it's not as reliable as `AtomGroup`

From the Edinburgh workshop:
> The two fundamental classes of `MDAnalysis` are the Universe and the `AtomGroup`.

From the UG:

>Most analysis requires creating and working with an `AtomGroup`, a collection of `Atom`. For convenience, you can also >work with chemically meaningful groups of `Atom`s such as a `Residue` or a `Segment`.

I think that even if we tried to define what `Segment` is, we may be surprised of what each topology format reader (that is, our own readers) understands it to be. And the creators of those formats will have different evolving opinions that we may fit into our model of `Segment` vs `chainID` today, but maybe not in the future.

I think it's good that the abstraction is called `Segment`, given that its definition is more general that that of **chain**/ `chainID`, but I don't see a way out of the ambiguity.
Perhaps this talk + what Irfan said about GROMOS can be added as a question on the FAQ? I'll put it on my TODO.

Having said all that, what should I do with the `molblock` attribute?

**Comment by IAlibay** [comment]
@MDAnalysis/coredevs a PR is blocked by a lack of discussion here, please chime in.

**Comment by orbeckst** [comment]
The proposed change to parse the TPR molblock ID and if it contains "Protein_chain_{chainID}" then to take "{chainID}" as the MDAnalysis segID has the potential to make it easier to recognize protein chains because many users appear to equate segID with chainID. 

There are disadvantages, though:
1. We would be relying on GROMACS keeping the naming convention. If they change it, we have to parse molblock IDs based on TPR file number in order to stay consistent. This creates additional maintenance burden (although we do have update the TPRParse regularly anyway to keep up with TPR format changes).
2. We are also relying on "{chainID}" to be unique. It's bad practice to rely on outside data to provide your internal identifiers. We would need additional checks to make sure that the identifiers are indeed unique.
3. It's a backwards-incompatible change that we can only implement in 3.0 and we need to add deprecation notices.

So, on balance I am _against_ changing it as I don't see the benefits outweighing the drawbacks. 

We could, however, use the "{chainID}" information and populate the `chainID` field of a topology. That one is not tied to the object hierarchy and acts as a simple tag. However, one would then have to decide what the chainID ought to be for other molblocks.

I'd be especially interested to hear opinions from other folks that regularly use GROMACS (e.g. @jbarnoud ).
