### ISSUE TITLE
Spack recipies are way out of date. 

### ISSUE THREAD

**Issue by hmacdope** [MDAnalysis/mdanalysis#4020]
## Expected behavior ##

Packaging with spack is getting more and more popular, we should probably bring the versions into the modern age. 
It will be a bit challenging getting the versioning of deps right in the spack language, but just thought I should flag. 

AFAIK they only have up to 1.0

https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/py-mdanalysis/package.py

**Comment by IAlibay** [comment]
The MDA spack packages aren't maintained by us so, similarly to various other package manager releases out of our hands, I don't really see this as an "us" issue.

If someone wants to take on that maintenance burden then I would say they are most welcome to do so. Personally, I don't really think it's wise to add yet another point of failure along the deployment workflow so I don't wish to take it on as an additional responsibility.

P.S. I'm removing the maint tag because of the "not us" context, feel free to re-add if you think otherwise.

**Comment by hmacdope** [comment]
Fair enough, just thought I would bring it to our collective attention.

**Comment by orbeckst** [comment]
Would it make sense to raise an issue in _their_ repo? We can always offer advice/help to maintainers and invite them to get involved here. 

But I echo Irfan: Distributions do their own thing: we do cf and pip, everybody else can package as they like. If they have problems then we welcome bug reports. Sometimes we just don't have the bandwidth to address everything  (e.g., that's why there isn't a Fedora package anymore afaik).

**Comment by RMeli** [comment]
I've been doing quite a lot of Spack recently. I could take care of that in my spare time if we want to have an updated recipe in Spack. However, I don't really see the usefulness of having high-level Python packages such as MDA in Spack though.

**Comment by RMeli** [comment]
I took some steps towards this: `py-chemfiles` (https://github.com/spack/spack/pull/35410) and `py-pytng` (https://github.com/spack/spack/pull/35575) are now available via Spack. `py-pyedr` and `py-panedr` will be hopefully added soon (https://github.com/spack/spack/pull/35576). This should cover all the new dependencies.

I started working on the MDA update (together with GridDataFormat). I assume it's OK to deprecate all versions up to `1.0.0`?

**Comment by IAlibay** [comment]
Yeah I'd say anything lower than 2.0 is definitely stuff we couldn't support anymore even if we had the energy for it.

**Comment by hmacdope** [comment]
Legend @RMeli :)

**Comment by RMeli** [comment]
Other updates towards this in https://github.com/spack/spack/pull/35827; I also deprecated `griddataformat` versions lower than `1.0.1`, let me know if this is _not_ ok.

**Comment by RMeli** [comment]
Fixed by https://github.com/spack/spack/pull/36052, bringing `2.4.2` to Spack's `develop`. I also added `MDAnalysisTests`, which was missing. I'll try to keep the package up-to-date, and I will remove the deprecated versions at Spack's next minor release.

---

**If you have issues installing MDAnalysis with Spack, please open an issue on the Spack repo and not the MDAnalysis repo.** Feel free to tag me (but I should be tagged automatically).

**Comment by hmacdope** [comment]
Thanks @RMeli  you rule.
