### ISSUE TITLE
Calculating free energies from steered MD

### ISSUE THREAD

**Issue by xhgchen** [MDAnalysis/mdanalysis#4041]
Hi everyone, I would like to suggest a new feature. In my undergraduate work, I calculated free energies from steered MD using Jarzynski’s equality via the second order cumulant expansion method from the work by Park et al. (Equation 20). This method is optimal when applied to a small number (~10) of trajectories of an irreversible process. The paper can be found at: https://doi.org/10.1063/1.1590311. My PI and I did the calculations in Mathematica using the smd.txt output files from AMBER, but I was thinking this could be implemented in MDAnalysis as a more general feature. Do you think this would be a useful addition?

In the same vein, I think including more analysis features for steered MD might be a possible direction for future enhancements. I searched through the documentation and I could not find anything related to “steered MD,” “SMD,” and similar keywords.

While I was looking for more recent papers on free energy calculations to check if there was a better approach to suggest, I found some relevant resources that may help if anyone is looking to dig deeper on this topic:

Computation of standard binding free energies with MD: https://doi.org/10.1021/jp807701h

Prediction of absolute solvation free energies with MD free energy perturbation and OPLS: https://doi.org/10.1021/ct900587b

Free energy calculation in MD lecture: https://personal.utdallas.edu/~son051000/comp/FreeE.pdf

**Comment by hmacdope** [comment]
@xhgchen, we generally steer (:wink:) away from (re-)implementing complex analysis tools for thermodynamics themselves. This is due to the range and complexity of tasks that can be conducted as well as the expert knowledge required to succesfully implement and test these methods. For equilibrium problems there are reference implementations of the most common estimators such as MBAR in `pymbar` or TI in `alchemlyb`. So we generally judge these tasks to be outside the domain of MDAnalysis. There is also a reference implementation of Jarzynski equality in `pymbar` see [here](https://pymbar.readthedocs.io/en/master/other_estimators.html#pymbar.other_estimators.exp). As a general rule of thumb if it needs the forcefield, it is likely out of the scope of the MDAnalysis core package. However we would still welcome a contribution in this area as an MDAKit (see [here](https://www.mdanalysis.org/2022/08/24/mdakits-intro/) for more details)  where you can adapt MDAnalysis to a more specialised problem.  

 Other @MDAnalysis/coredevs  may have a different opinion and I would encourage them to weigh in.

**Comment by orbeckst** [comment]
I echo @hmacdope , this is out-of-scope for MDA core functionality.

If the implementation only requires reading of energy files from the MD code then [alchemlyb](https://github.com/alchemistry/alchemlyb) would be a good place to suggest enhancements (I am also involved in that project).

If your implementation requires trajectory data together with force-field information then an MDAKit that uses MDA for trajectory parsing and other tools for the energy evaluation may be the better route. However, energy evaluations are tricky and can be MD-package dependent.
