### ISSUE TITLE
Reading forcefield parameters from tpr file

### ISSUE THREAD

**Issue by subhamoymahajan** [MDAnalysis/mdanalysis#4178]
I am working with gromacs .tpr and .trr files to read a Universe,

mol=mda.Universe(tpr_file,trr_file),

I was hoping that "mol" has all the forcefield parameters, i.e., equilibrium bond length, force constant of bond lengths, etc. because it reads the tpr_file. 

Could you please let me know how to access these parameters?

**Comment by hmacdope** [comment]
Hi @subhamoymahajan MDAnalysis does not read forcefield parameters, instead focusing on  trajectories and topologies. You will need to use another tool to such as [parmed](https://parmed.github.io/ParmEd/html/index.html) access the forcefield parameters.

**Comment by orbeckst** [comment]
We decided a while back to not get into force field parsing, simply because we don't have the people to do all the work. 

That said, it's not too hard to pull this information out of the TPR file. You're welcome to start a discussion on the developer mailing list or on discord in #developers and see if people would find that interesting. If so, you could work on it yourself and submit a PR. 

Actually, you can _always_ work on this problem for yourself: start with https://github.com/MDAnalysis/mdanalysis/blob/develop/package/MDAnalysis/topology/TPRParser.py and go through https://github.com/MDAnalysis/mdanalysis/tree/develop/package/MDAnalysis/topology/tpr . Once you have a solution that works for you, you can share it.

Until then I'll close the issue.
