### ISSUE TITLE
Error in PDBQT to PDB conversion

### ISSUE THREAD

**Issue by RortegaPQ** [MDAnalysis/mdanalysis#4207]
## Expected behavior ##

I am trying to convert a PDBQT file of a prepared protein to the PDB format using MDAnalysis. I expect that the conversion process will retain the correct atom types without any issues, ensuring that the resulting PDB file represents the original structure accurately.

## Actual behavior ##

During the conversion from PDBQT to PDB format, I encountered an unexpected behaviour. The atom types are being incorrectly assigned as the chain ID instead of retaining their actual atom types. As a result, the resulting PDB file does not accurately represent the original structure, leading to errors in further downstream processing, such as docking simulations using AutoDock Vina.

## Code to reproduce the behavior ##

``` python
import MDAnalysis as mda
from MDAnalysis.tests.datafiles import PSF, DCD,  GRO, PDB, TPR, XTC, TRR,  PRMncdf, NCDF

def pdbqt_to_pdb(pdbqt_file, pdb_file):
    # Load the .pdbqt file
    u = mda.Universe(pdbqt_file)

    # Save the structure in .pdb format
    u.atoms.write(pdb_file)

```

## Current version of MDAnalysis ##

- MDAnalysis version: 2.3.0
- Python version: 3.9.4
- Operating system: Linux Ubuntu 22.04.2 LTS

## Additional Notes ## 

I have consulted the MDAnalysis documentation in an attempt to find a solution, but I could not identify any direct method or tutorial addressing this specific conversion issue. The incorrect assignment of atom types to the chain ID in the resulting PDB file hinders my ability to proceed with my research on docking simulations.

I would greatly appreciate your help in resolving this bug or providing some guidance on how to correctly perform the PDBQT to PDB conversion using MDAnalysis. Your expertise and support would be invaluable in ensuring the accurate representation of molecular structures for further analysis.

Thank you for your attention to this matter, and I look forward to hearing back from you.

Sincerely,

Rita 
@RortegaPQ

**Comment by pgbarletta** [comment]
Those are the segment ids, not the elements. If you want to keep both, you could do:

```
from MDAnalysis.tests.datafiles import PDBQT_input
# Load the .pdbqt file
u = mda.Universe(PDBQT_input)


u.add_TopologyAttr('chainID', u.atoms.segids)
u.add_TopologyAttr('element', 
                   [guess_atom_element(atm.name) for atm in u.atoms])

# Save the structure in .pdb format
u.atoms.write(Path(PDBQT_input).stem + ".pdb")
```
I think you can make do with that for now.


Now, the `.pdbqt` parser says it [guesses elements](https://github.com/MDAnalysis/mdanalysis/blob/a1aff6638184a90ae36b879720b2fa78dee1d1ee/package/MDAnalysis/topology/PDBQTParser.py#L100), which it doesn't but I guess there's actually no need to do it, since the [AutoDock atom types](https://mmb.irbbarcelona.org/gitlab/BioExcel/structureChecking/-/blob/5f07d82dc36d1f43733ae3b1ecd9f40aebe8b0a2/biobb_structure_checking/dat/autodock_atomtypes.dat) are easily assignable to their corresponding atomic elements.

So,

1. Should I open a PR on the `.pdbqt` parser to read elements as well? Or is there a good reason why they're not read (like, perhaps they keep changing their atom types and it's too much work to support that)?
2. Should I open a PR on the `.pdbqt` parser to assign `segids` to `chainIDs`? The `.pdb` parser does it, I don't see why the `.pdbqt` parser shouldn't do it as well.

**Comment by RortegaPQ** [comment]
I think the second option would be fine? AS long as the resulting PDB has in the last column the correct letters (corresponding to the atom element), I'd be fine with it. 
As far as I know, other tools that do the conversion, conserve that las column with the element letters.

**Comment by orbeckst** [comment]
@RortegaPQ would you be able to post a few lines from (1) the input file, (2) the same lines from the output file with the current process, and (3) the same lines _as you would like them to come out_?

From the discussion above I am still not sure if there's a bug (is MDA writing segids into atom names??) or if this is more of an enhancement.

**Comment by orbeckst** [comment]
> Should I open a PR on the .pdbqt parser to read elements as well? Or is there a good reason why they're not read (like, perhaps they keep changing their atom types and it's too much work to support that)?

@pgbarletta if we can read actual elements (without guessing) then we should consider adding it to PDBQT. Otherwise, I'd leave it — there was some effort to implement a comprehensive guesser framework (#3856 and others — @jbarnoud may know more) so I'd just avoid patchwork.

> Should I open a PR on the .pdbqt parser to assign segids to chainIDs? The .pdb parser does it, I don't see why the .pdbqt parser shouldn't do it as well.

Given that you recently did just that elsewhere (TPR?? I can't remember where...), I think that's a good idea for consistency.
