### ISSUE TITLE
[CI] Nightly wheels numpy exceptions handling

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/mdanalysis#4232]
Nightly wheels CI broke last night. Mostly down to changes in numpy exception imports. It seems like everything will be fixed once scipy uploads it's next set of wheels (the issues were mostly through linalg imports), but we should keep an eye on this.

**Comment by tylerjereddy** [comment]
Ah, that's probably because of https://numpy.org/doc/stable/release/1.25.0-notes.html#numpy-now-has-an-np-exceptions-namespace and `2.0` related changes in NumPy `main` to remove exceptions from the root namespace.

So yeah, the shim I merged at https://github.com/scipy/scipy/pull/19015 should help, I hope.

**Comment by tylerjereddy** [comment]
Ok, `astropy` was having problems as well, so I went ahead and triggered new SciPy dev wheel builds just now. For more details, see cross-linked issue above (I didn't trigger for ARM builds on Cirrus CI, I may try to avoid that unless a project really needs those as well).

**Comment by IAlibay** [comment]
Thanks @tylerjereddy !

**Comment by IAlibay** [comment]
CI came back green, looks like that fixed it!
