### ISSUE TITLE
`NoJump` transformation ignores jumps across boundaries on the second frame for NPT trajectories

### ISSUE THREAD

**Issue by p-j-smith** [MDAnalysis/mdanalysis#4257]
## Expected behavior ##

It's very cool the MDAnalysis now has a nojump transformation 🎉 

After it was released I decided it would make sense to [deprecate the nojump transformation I had written for lipyphilic](https://github.com/p-j-smith/lipyphilic/pull/124), expecting the MDAnalysis transformation had been tested with an NPT trajectory.

## Actual behavior ##

Looking at the tests, it seems that [both trajectories used for testing](https://github.com/MDAnalysis/mdanalysis/blob/8923c4a8203e755939ad9fc3f2242a837a493c28/testsuite/MDAnalysisTests/transformations/test_nojump.py#L21-L48) are NVT.

I've written a couple of tests with dummy Universes and NPT trajectories and I think there might be issue with incorrect unwrapping, but I may be misunderstanding something.
## Code to reproduce the behavior ##

I've written two tests to check the unwrapping in the following situations:

- an atom remains stationary but crosses a periodic boundary due to decreasing box size
- an atom moves at a constant velocity and crosses a periodic boundary both due to it's velocity and the decreasing box size

First write the Universes and trajectories to file:
```python
import MDAnalysis as mda


def write_nojump_universe_stationary_npt():
    """
    Create a Universe in which a single atom remains stationary but box size
    decreases by 5 Angstrom at each frame.
    
    This initial box dimensions are [100, 100, 100, 90, 90, 90]
    The trajectory consists of three frames.

    Unwrapped coordinates: atom remains stationary
    coordinates = [
        [97.5, 50, 50]
        [97.5, 50, 50]
        [97.5, 50, 50]
    ]

    Wrapped coordinates: box dimensions decrease 5 Angstrom each frame, so atom is wrapped in x-dimension at 2nd frame
    coordinates = [
        [97.5, 50, 50]
        [2.5, 50, 50]
        [2.5, 50, 50]
    ]

    """
    n_atoms = 1
    n_frames = 3
    u = mda.Universe.empty(n_atoms, trajectory=True)

    coordinates = np.empty((n_frames, u.atoms.n_atoms, 3))
    coordinates[0] = [97.5, 50.0, 50.0]
    coordinates[1] = [2.5, 50.0, 50.0]
    coordinates[2] = [2.5, 50.0, 50.0]
    u.load_new(coordinates, order="fac")

    box = np.array([100, 100, 100, 90, 90, 90])
    u.dimensions = box
    u.atoms.write("nojump_stationary_npt.pdb")

    with mda.Writer("nojump_stationary_npt.xtc") as f:
        for ts in u.trajectory:
            box[:3] -= 5 * ts.frame  # shrink size by 5 Ansgtroms
            u.dimensions = box
            f.write(u.atoms)

def write_nojump_universe_constvel_npt():
    """
    Create a Universe in which a single atom move 5 Angstrom in the positive
    x directaion at each frame AND the box size decreases by 5 Angstrom at each frame.

    This initial box dimensions are [100, 100, 100, 90, 90, 90]
    The trajectory consists of three frames.

    Unwrapped coordinates: atom move 5 Angstrom in the positive x direction each frame
    coordinates = [
        [97.5, 50, 50]
        [102.5, 50, 50]
        [107.5, 50, 50]
    ]

    Wrapped coordinates: box dimensions decrease 5 Angstrom each frame and particle moves 5 A each frame in positive x-dimension
    coordinates = [
        [97.5, 50, 50]
        [7.5, 50, 50]
        [12.5, 50, 50]
    ]

    """
    n_atoms = 1
    n_frames = 3
    u = mda.Universe.empty(n_atoms, trajectory=True)

    coordinates = np.empty((n_frames, u.atoms.n_atoms, 3))
    coordinates[0] = [97.5, 50.0, 50.0]
    coordinates[1] = [7.5, 50.0, 50.0]
    coordinates[2] = [12.5, 50.0, 50.0]
    u.load_new(coordinates, order="fac")

    box = np.array([100, 100, 100, 90, 90, 90])
    u.dimensions = box
    u.atoms.write("nojump_constvel_npt.pdb")

    with mda.Writer("nojump_constvel_npt.xtc") as f:
        for ts in u.trajectory:
            box[:3] -= 5 * ts.frame  # shrink size by 5 Ansgtroms
            u.dimensions = box
            f.write(u.atoms)

write_nojump_universe_stationary_npt()
write_nojump_universe_constvel_npt()
```

Now run the tests:
```python
import pytest
import numpy as np
import MDAnalysis as mda

@pytest.fixture
def nojump_universe_stationary_npt():
    return mda.Universe("nojump_stationary_npt.pdb", "nojump_stationary_npt.xtc")

@pytest.fixture
def nojump_universe_constvel_npt():
    return mda.Universe("nojump_constvel_npt.pdb", "nojump_constvel_npt.xtc")

def test_nojump_stationary_npt(nojump_universe_stationary_npt):
    u = nojump_universe_stationary_npt
    u.trajectory.add_transformations(mda.transformations.NoJump())
    x_position = 97.5
    np.testing.assert_allclose(u.trajectory.timeseries()[:, 0, 0], x_position)

def test_nojump_constvel_npt(nojump_universe_constvel_npt):
    u = nojump_universe_constvel_npt
    u.trajectory.add_transformations(mda.transformations.NoJump())
    x_positions = [97.5, 102.5, 107.5]
    np.testing.assert_allclose(u.trajectory.timeseries()[:, 0, 0], x_positions)

```

The first test fails with the error message:
```
./tests/lipyphilic/analysis/transformations/test_transformations.py::test_nojump_stationary_npt Failed: [undefined]AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0

Mismatched elements: 2 / 3 (66.7%)
Max absolute difference: 95.
Max relative difference: 0.97435897
 x: array([97.5,  2.5,  2.5], dtype=float32)
 y: array(97.5)
nojump_universe_stationary_npt = <Universe with 1 atoms>

    def test_nojump_stationary_npt(nojump_universe_stationary_npt):
        u = nojump_universe_stationary_npt
        u.trajectory.add_transformations(mda.transformations.NoJump())
        x_position = 97.5
>       np.testing.assert_allclose(u.trajectory.timeseries()[:, 0, 0], x_position)
```

And the second test fails with the error message:
```
./tests/lipyphilic/analysis/transformations/test_transformations.py::test_nojump_constvel_npt Failed: [undefined]AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0

Mismatched elements: 2 / 3 (66.7%)
Max absolute difference: 95.
Max relative difference: 0.92682927
 x: array([97.5     ,  7.5     , 12.500001], dtype=float32)
 y: array([ 97.5, 102.5, 107.5])
nojump_universe_constvel_npt = <Universe with 1 atoms>

    def test_nojump_constvel_npt(nojump_universe_constvel_npt):
        u = nojump_universe_constvel_npt
        u.trajectory.add_transformations(mda.transformations.NoJump())
        x_positions = [97.5, 102.5, 107.5]
>       np.testing.assert_allclose(u.trajectory.timeseries()[:, 0, 0], x_positions)
```

So in both cases it seems that the atom is not being unwrapped in the x-dimension.

Note, both of these tests pass when using the lipyphilic nojump transformation:

```python
import pytest
import numpy as np
import MDAnalysis as mda
import lipyphilic as lpp

def test_nojump_stationary_npt_lpp(nojump_universe_stationary_npt):
    u = nojump_universe_stationary_npt
    u.trajectory.add_transformations(lpp.transformations.nojump(ag=u.atoms, nojump_z=True))
    x_position = 97.5
    np.testing.assert_allclose(u.trajectory.timeseries()[:, 0, 0], x_position)

def test_nojump_constvel_npt_lpp(nojump_universe_constvel_npt):
    u = nojump_universe_constvel_npt
    u.trajectory.add_transformations(lpp.transformations.nojump(ag=u.atoms, nojump_z=True))
    x_positions = [97.5, 102.5, 107.5]
    np.testing.assert_allclose(u.trajectory.timeseries()[:, 0, 0], x_positions)

```

but this may be because I have misunderstood something about nojump unwrapping!

## Current version of MDAnalysis ##

- Which version are you using? (run `python -c "import MDAnalysis as mda; print(mda.__version__)"`) 2.7.0-dev0
- Which version of Python (`python -V`)? Python 3.11.4
- Which operating system? macOS Monterey

**Comment by orbeckst** [comment]
@jvermaas could you please have a look? Thanks!

**Comment by jvermaas** [comment]
The thing that is actually guaranteed is that the positions won't change if you unwrap and then wrap. @p-j-smith, since you are changing the size of the box, the nojump transformation is trying to keep track of the change to the atom positions once the box has changed size. I think the first example is particularly instructive, since you are thinking in terms of "Oh, its still where I left it based on how the box-size has changed". However, MD algorithms in NPT aren't keeping track of where the atoms are in an absolute sense, but are trying to keep track of where the atoms are as a fraction of the box. So in the first example, you are 97% of the way along the x axis, but then in the next frame you are 3% of the way along the x-axis. The particle moved as the box shrunk! When we unwrap it, we need to account for this. Where you see this most clearly is in equation B8 from the paper where we work this out. https://pubs.acs.org/doi/full/10.1021/acs.jctc.2c00327 The alpha term is probably by how much the numbers are off from what you expect! Instead, I'd look at something like this to convince yourself that the transformation is right:

```
import numpy as np
import pytest
from numpy.testing import assert_allclose
import MDAnalysis as mda
from MDAnalysis.transformations import NoJump, wrap
from MDAnalysisTests import datafiles as data


def test_nojump_unwrapnpt():
    """
    Test if the nojump transform is returning the correct
    values when iterating forwards over the sample trajectory.
    """
    ref = mda.Universe(data.PSF_TRICLINIC, data.DCD_TRICLINIC)
    u = mda.Universe(data.PSF_TRICLINIC, data.DCD_TRICLINIC)
    workflow = [NoJump(),
        wrap(u.atoms),
    ]
    assert_allclose(
        u.trajectory.timeseries(),
        ref.trajectory.timeseries(),
        rtol=5e-07,
        atol=5e-06,
    )
    print(u.trajectory.timeseries())
    print(ref.trajectory.timeseries())
test_nojump_unwrapnpt()
```

The file loaded is a triclinic NPT simulation, which can be unwrapped and wrapped with no loss in precision. *That* is what the nojump transformation is trying to keep from changing, while diligently keeping track of how much things have moved from frame to frame.

**Comment by p-j-smith** [comment]
> MD algorithms in NPT aren't keeping track of where the atoms are in an absolute sense, but are trying to keep track of where the atoms are as a fraction of the box

Oh I see, thanks for the detailed  explanation @jvermaas!

Perhaps it's worth adding the test you wrote above, just so it's explicitly tested? Or if not, feel free to close the issue, thanks again

**Comment by jvermaas** [comment]
I'm going to leave that up to @hmacdope as to if they want to add it to the test case suite.

**Comment by hmacdope** [comment]
More tests for these kind of critical code paths are always better. :) Happy for anyone to do it. Thanks @jvermaas for the detailed explanation, much appreciated.

**Comment by p-j-smith** [comment]
> The alpha term is probably by how much the numbers are off from what you expect!

Just looking at this again, the error from the first test wss
```python
Not equal to tolerance rtol=1e-07, atol=0

Mismatched elements: 2 / 3 (66.7%)
Max absolute difference: 95.
Max relative difference: 0.97435897
 x: array([97.5,  2.5,  2.5], dtype=float32)
 y: array(97.5)
```
In this error message, the `x` array is the unwrapped `x` coordinate at each frame, and the `y` array is the unwrapped `x` coordinate I had naively expected. It makes sense to me now that they are not exactly the same, but the coordinates at frame 2 and 3 are off by 95, so  it still seems there has been a jump across a boundary and that this is not accounted for?

**Comment by p-j-smith** [comment]
After looking in to it some more, the issue seems to be that the jump across the boundary happens at the second frame - if it happens at the third frame instead then the coordinates are unwrapped correctly. I think the problem is the way the transformation is initialiased:

https://github.com/MDAnalysis/mdanalysis/blob/8923c4a8203e755939ad9fc3f2242a837a493c28/package/MDAnalysis/transformations/nojump.py#L111-L113

If instead it is initialised like this:
```python
L = ag.universe.trajectory.ts.triclinic_dimensions
Linverse = np.linalg.inv(L)
self.prev = ag.positions @ Linverse
self.old_frame = -1
self.older_frame = -2
```
then jumps that occur at the second frame are unwrapped correctly. This means the transformation would need to take an `ag` argument, but that would also be a useful way of reducing computational cost as typically you'd unwrap and calculate MSD for a subset of atoms only. I'll submit a pr that fixes this shortly

**Comment by jvermaas** [comment]
I think the rabbit hole goes deeper than that @p-j-smith . Here are the warnings that are being emitted by MDAnalysis while it is doing your test.

/home/josh/git/mdanalysis/package/MDAnalysis/transformations/nojump.py:131: UserWarning: NoJump transform is only accurate when positionsdo not move by more than half a box length.Currently jumping between frames with a step of more than 1.This might be fine, but depending on the trajectory stride,this might be inaccurate.
  warnings.warn(
/home/josh/git/mdanalysis/package/MDAnalysis/transformations/nojump.py:121: UserWarning: NoJump detected that the interval between frames is unequal.We are resetting the reference frame to the current timestep.
  warnings.warn(

The warning is coming from a reasonable place. At the first frame, the logic is to jump into this piece first:

```
if self.prev is None:
            self.prev = ts.positions @ Linverse
            self.old_frame = ts.frame
            return ts
```
which will set the `old_frame` to 0 in this case, and give you a self.prev to compare with in reduced coordinates. So far so good. The next go around, you are somehow tripping this block:

```
if self.check_c and np.abs(self.old_frame - ts.frame) != 1:
            warnings.warn(
                "NoJump transform is only accurate when positions"
                "do not move by more than half a box length."
                "Currently jumping between frames with a step of more than 1."
                "This might be fine, but depending on the trajectory stride,"
                "this might be inaccurate.",
                UserWarning,
            )
```
The thing that is bananas to me is how on earth this is triggering. `ts.frame` should be 1 here, `self.old_frame` should be 0, since you *did* advance the frame. But instead, `ts.frame` and `self.old_frame` are both 0 the second time around... As a result, when you then trigger the next frame, which has `ts.frame` of 1, you go through the second error-correcting block, which is trying to do the right thing by resetting to the current frame, since it sees a non-equal stride-length. If you turn the checks off (`NoJump(check_continuity=False`), it does the right thing, since the repeated frames become a no-op. @hmacdope , why would the frame be repeated when applying transformations? At first I thought it was because you are loading a pdb and xtc, and the pdb file was somehow being loaded, but if I use an xtc + psf, it does the same thing.

I also observe this strange behavior in the updated test.
```
def test_nojump_unwrapnpt():
    """
    Test if the nojump transform is returning the correct
    values when iterating forwards over the sample trajectory.
    """
    ref = mda.Universe(data.PSF_TRICLINIC, data.DCD_TRICLINIC)
    u = mda.Universe(data.PSF_TRICLINIC, data.DCD_TRICLINIC)
    workflow = [NoJump(),
    	wrap(u.atoms)
    ]
    u.trajectory.add_transformations(*workflow)
    for ts in u.trajectory:
    	1 + 1 # Some no-op so that the transformations are actually exercised.
    assert_allclose(
        u.trajectory.timeseries(),
        ref.trajectory.timeseries(),
        rtol=5e-07,
        atol=5e-06,
    )
test_nojump_unwrapnpt()
```
The 0th frame is repeated twice when doing the transformation, and also shows up at the end. *Why?* I could have sworn that it didn't do this before!

**Comment by jvermaas** [comment]
Oh boo. I see the problem now. It applies the transformation to the 0th frame as soon as the transformations are added. Then, when you explicitly loop through a trajectory, it can add the transformation *again*. We could add a really simple check like:
```
if ts.frame == self.old_frame:
            return ts
```
to avoid double-transforming, but since frame 0 also shows up at the end, I'm super confused.

**Comment by p-j-smith** [comment]
Oh well spotted! I didn't check for warnings.

I think that might be happening because when the transformations are added to the trajectory they are also applied to the 0th frame:

https://github.com/MDAnalysis/mdanalysis/blob/8923c4a8203e755939ad9fc3f2242a837a493c28/package/MDAnalysis/coordinates/base.py#L1415

Then when we iterate over the trajectory it's applied a second time

**Comment by jvermaas** [comment]
Any idea why it is applying the transform at the end too? I guess that isn't as bad, since it works out to be a no-op. But I still think its very strange.
