### ISSUE TITLE
atomgroup object can forget about positions

### ISSUE THREAD

**Issue by kain88-de** [MDAnalysis/mdanalysis#447]
I stumbled onto something very strange

This code snippet will result in `__getattr__` to throw

```python
sel = mda.Universe(PDB).select_atoms('name CA')
sel.positions
```

However this snippet works as expected.

```python
u = mda.Universe(PDB)
sel = u.select_atoms('name CA')
sel.positions
```

both snippets used to work in `0.10.0`

**Comment by mnmelo** [comment]
This behavior is as expected, as per #297. The universe goes out of scope since the AtomGroup now only holds a weakref to it. We agreed then that this wouldn't be a problem, but it might be.

Or maybe we just need to document it better.

**Comment by kain88-de** [comment]
This IS a problem. Because it goes against intuition using the library. For a novice to the library and an intermediate python user the first snippet should work. It is absolutely not obvious that AtomGroups are only good (having positions and other nice things) as long as the universe connected to it exists.

It also makes some nice syntactic sugar go away. In one of my scripts I had

```python
thingy = construct_thingy([merge_universes(universe_list)])
```

It took a good while until I noticed that the temporary merged_universe was the problem

Also thinks like

```python
def get_specific_selection(fname):
    u = mda.Universe(fname)
    return u.select_atoms('name CA')

sel = get_specific_selection(PDB)
sel.positions
```

won't work anymore. But just by looking at them I would expect them to work. Please note
that there might be perfectly good reason why someone might do things like that.


All in all I say this is a bug that is hard to pinpoint when triggered by a user. One needs to know the library pretty well to find that out.

**Comment by mnmelo** [comment]
Well, I would definitely not classify it as a bug, since we foresaw it and discussed whether to change the API in this respect or not.

Nomenclature aside I think you make the case to reopen that discussion. @richardjgowers, @orbeckst, and myself had no conflicting use of the Universes when the issue was brought up. The question is now whether to uphold the API change (and certainly better document it), revert it (we have to think what that entails, since it's linked to AtomGroup picklability), or something in between (doing our own AtomGroup-to-Universe bookkeeping?).

**Comment by richardjgowers** [comment]
I'm going to close this so we can use the old `__del__` discussion #297
