### ISSUE TITLE
rename PSAnalysis?

### ISSUE THREAD

**Issue by hainm** [MDAnalysis/mdanalysis#453]
I have no idea what `PS` is if not looking at the doc. Why explicitly writing 'Analysis' and shorten `PS`? 

Why don't you use `PathSimilarity`?
(given that in the code, you use longer keyword, such as `hausdorff_neighbors`, `get_path_metric_func` ...) 

`ps` is not commonly used as `rms` or `pca`.

**Comment by sseyler** [comment]
@hainm I'm just thinking out loud here; I'm very open to brainstorming and suggestions:

The analysis class was originally called `PSA`, but that makes aliasing the `psa.py` module irritating, because the class (`PSA`), module (`psa.py`), and most obvious alias (`psa`) all make for somewhat clumsy statements (i.e., `psa = MDAnalysis.analysis.psa.PSA(...)` is pretty ugly). `PSAnalysis` was used as a simple fix, although I also feel that there are probably better options.

I considered `PathSimiliarity` and, although I like it too, it seemed to emphasize only one aspect of the (many) possible analyses that aren't strictly about measuring path similarity (like `hausdorff_neighbors`). Using `Sim` is ambiguous since it could mean "simulation" as well. We're also somewhat committed to "Path Similarity Analysis", since that's what we've chosen to call it in the PLoS Comp Bio article...

**Comment by richardjgowers** [comment]
Hmm, I like PathSimilarity too.  If you really wanted to show off the features you could volunteer to put together a notebook example #420

**Comment by orbeckst** [comment]
@richardjgowers have you seen [Becksteinlab/PSAnalysisTutorial](https://github.com/Becksteinlab/PSAnalysisTutorial) ?

**Comment by orbeckst** [comment]
> We're also somewhat committed to "Path Similarity Analysis", since that's what we've chosen to call it in the PLoS Comp Bio article...
... is a pretty strong argument.

Also: if you invent something you get to name it ;-), i.e. ultimately it's up to @sseyler

**Comment by richardjgowers** [comment]
Ahh, no I hadn't, and it's very cool.  But this is the kind of thing we should link to off the MDA homepage, like a gallery of examples.

**Comment by orbeckst** [comment]
I like the idea of a gallery/examples page at mdanalysis.org, can you raise an issue there, please?
Plus suggestions!!

**Comment by kain88-de** [comment]
I think the analysis is redundant in the name `PSAnalysis` since it already lives in the analysis module. Just having `PathSimilarity` would be enough IMHO. Then it can be loaded as 

    from MDAnalysis.analysis import PathSimilarity

or

    mda.analysis.PathSimilarity

**Comment by hainm** [comment]
> from MDAnalysis.analysis import PathSimilarity

and I am not sure if `analysis` is necessary too. `MDAnalysis.analysis` :D 

```python
from MDAnalysis.PathSimilarity import xyz
```

**Comment by sseyler** [comment]
The functionality of the PSA will likely be extended in the future, so naming conventions may change in the future in a sensible way to accommodate new analyses, classes, etc. However, for the time being, the nomenclature should remain as is for consistency with the name *Path Similarity Analysis* in the paper. FYI: I've updated the PSA module with the corresponding paper's PLOS Computational Biology citation.
