### ISSUE TITLE
questions about filename, __repr__

### ISSUE THREAD

**Issue by hainm** [MDAnalysis/mdanalysis#455]
I don't know how which title for those question, so please rename (or let me know) it.

* Universe's filename

```python
In [8]: u = Universe(datafiles.PSF, datafiles.DCD)

In [9]: u.filename
Out[9]: '/home/haichit/anaconda3/envs/py2/lib/python2.7/site-packages/MDAnalysisTests-
0.11.1.dev0-py2.7.egg/MDAnalysisTests/data/adk.psf'
```

If I understand correctly, Universe has both topology and coordinates. Why `u.filename` shows only filename for topology? 

* What's motivation for `u.universe`?
```python
In [12]: u
Out[12]: <Universe with 3341 atoms and 3365 bonds>

In [13]: u.universe
Out[13]: <Universe with 3341 atoms and 3365 bonds>
```

**Comment by orbeckst** [comment]
* The thinking behind `Universe.filename` was that the fundamental input is the topology. Trajectories live in their reader, i.e. `Universe.trajectory` and in particular `Universe.trajectory.filename`.
* Having `Universe` contain itself is slightly redundant but was added so that you can seamlessly traverse object hierarchies: all atom containers have `universe`, `segments`, `residues`, `atoms` attributes so you can just take any old object and work with it without having to check its type.

**Comment by hainm** [comment]
Thanks.
