### ISSUE TITLE
create a useful setup.cfg

### ISSUE THREAD

**Issue by kain88-de** [MDAnalysis/mdanalysis#462]
Build options should be configurable from a `setup.cfg`. We shouldn't require people to edit the `setup.py`. See https://groups.google.com/forum/#!topic/mdnalysis-discussion/yblLSNvucq0 for recent examples

**Comment by orbeckst** [comment]
1. Sure; we used to have a `setup.cfg` but we actually removed it because it was more confusing that helpful. We didn't want to leave in a file just with defaults that we have to maintain. We've been looking at `setup.cfg` as something that the user can add if they need to change settings. 
2. Once a user has to edit `setup.py`, it's a bug... like #459 for the example that you mention.
