### ISSUE TITLE
global distance test 

### ISSUE THREAD

**Issue by euhruska** [MDAnalysis/mdanalysis#473]
Is there a global distance test (GDT) function in mdanalysis? I think it's pretty important since it's the scoring function at CASP. See: http://research.omicsgroup.org/index.php/Global_distance_test

**Comment by hainm** [comment]
at least you should change the name.

**Comment by euhruska** [comment]
sorry for that

**Comment by dotsdl** [comment]
Apologies for @hainm; he should be less terse and more helpful. :D

@euhruska MDAnalysis currently does not have a built-in implementation of GDT, but we welcome contributions such as this into the [analysis](https://github.com/MDAnalysis/mdanalysis/tree/develop/package/MDAnalysis/analysis) submodules. These submodules are contributed by users, often built out of their own needs for such tools.

Would you be interested in working on an implementation? We are more than happy to help you along with the process of contributing to the project.

**Comment by richardjgowers** [comment]
I think we've got lots of similar stuff though?

**Comment by euhruska** [comment]
Sounds good. I think I will decide next week if I will do an implementation.

**Comment by orbeckst** [comment]
Cool, would be a good addition. Right now we only have RMSD and simple distance-based native contacts. We're more than happy to give you some guidance on how to structure your analysis module so that it seamlessly fits into the rest of the library.

Typical development workflow for [contributed code](/MDAnalysis/mdanalysis/wiki/ContributingCode): Clone the repo, submit pull request, get feedback (code review), incorporate feedback, iterate, merge, be added to AUTHORS, be proud!

**Comment by hainm** [comment]
I had the implementation in pytraj before (call a file in ClusCo-0.2.1 package) but I removed from pytraj since  ClusCo-0.2.1 has GNU license (vs BSD in pytraj).

Fee free to implement it in MDAnalysis (more compat with ClusCo) if you like.

C code: https://github.com/hainm/pytraj/tree/7c42a6b19f1dd14689e8a6e33fc587c6a5b0d501/pytraj/externals/gdt/src

cython code
```python
from libcpp.vector cimport vector
ctypedef signed short sshort

cdef extern from "./src/gdt_.h":
    sshort * _gdt "gdtCPUOneReference"(double *reference, double *arr,  
                                       int conformers, int protlen, int score)

cdef sshort[:] gdt(double[:] reference, double[:] arr, int conformers, int protlen, int score):
    cdef sshort[:] arr0
    cdef sshort* ptr

    ptr = <sshort*> _gdt(&reference[0], &arr[0], conformers, protlen, score)
    arr0 = <sshort[:conformers]> ptr
    return arr0
```

Whole folder: https://github.com/hainm/pytraj/tree/7c42a6b19f1dd14689e8a6e33fc587c6a5b0d501/pytraj/externals/gdt

**Comment by euhruska** [comment]
Sounds great!

**Comment by euhruska** [comment]
I guess the code can't be Fortran, I can be only C, cython or python. Is that right?

**Comment by richardjgowers** [comment]
Fortran isn't a problem, but you'll have to write a small Cython wrapper to interface it with the numpy arrays.

**Comment by kain88-de** [comment]
@euhruska. Numpy and Scipy itself are using a LOT of fortan code.  They are using [f2py](http://docs.scipy.org/doc/numpy-dev/f2py/). I haven't used it myself so I don't know how easy it is to set up.

How many lines of Fortran-code would we be talking about? If it is not to much maybe we can help you to rewrite the important bits in python/cython.

**Comment by hainm** [comment]
AFAIN, f2py <http://docs.scipy.org/doc/numpy-dev/f2py/> does not work with
modern fortran.

Hai

On Wed, Oct 7, 2015 at 4:05 PM, kain88-de <notifications@github.com> wrote:

> @euhruska <https://github.com/euhruska>. Numpy and Scipy itself are using
> a LOT of fortan code. They are using f2py
> <http://docs.scipy.org/doc/numpy-dev/f2py/>. I haven't used it myself so
> I don't know how easy it is to set up.
>
> How many lines of Fortran-code would we be talking about? If it is not to
> much maybe we can help you to rewrite the important bits in python/cython.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MDAnalysis/mdanalysis/issues/473#issuecomment-146313201>
> .
>



-- 
Hai Nguyen

**Comment by euhruska** [comment]
I not sure, but maybe there is no need to write the function. After all, it's implemented, for example here: http://zhanglab.ccmb.med.umich.edu/TM-score/  The input includes the GDT value.

**Comment by hainm** [comment]
> I not sure, but maybe there is no need to write the function.

Yes, it depends on what you need.

**Comment by orbeckst** [comment]
@euhruska are you still considering working on a GDT implementation? 

If not I (or you) can close the issue and we can always re-open it when necessary.
