### ISSUE TITLE
numpy is required even for setup

### ISSUE THREAD

**Issue by jbarnoud** [MDAnalysis/mdanalysis#479]
MDAnalysis cannot be installed with pip if numpy is not installed.

This means that `pip install MDAnalysis` does not work if numpy is not installed.

This also makes it impossible to install a virtualenv with MDAnalysis uning only a requirement.txt file. To do so, numpy must already be installed when pip is called with the requirement file, or MDAnalysis must be installed after pip is called with the requirement file.

This is inconvenient when writing a program that depends on MDAnalysis. It makes setting up Travis CI, read the docs, or similar services more difficult to setup.

Ideally, MDAnalysis should tell pip it requires numpy and not crash. This should be possible as other packages such as scipy do it.

**Comment by orbeckst** [comment]
Would be nice to have.

Just fyi: We gave up on RTD --- it seems impossible to have C-extensions (which contain docs) to get to build there. There are a bunch of issues on this in the tracker.

**Comment by kain88-de** [comment]
I'm sorry I don't see an easy way for this to work. Also I couldn't find any project besides scipy that is able to do that. And even with scipy I'm sure they con only pull that off right now because they are shipping a wheel (pre build binary).

The thing is our configuration that is run before `setup(...)` just needs to know the numpy include directories. There is no easy way around that.

**Comment by tylerjereddy** [comment]
@orbeckst Although note that if we start using conda then RTD may become a possibility pending resolution of this popular issue: https://github.com/rtfd/readthedocs.org/issues/857

**Comment by kain88-de** [comment]
I just tried to install scipy from source in a virtualenv without numpy. That fails because scipy can't import the appropriate numpy module to configure the build environment. This means numpy has to be installed if MDAnalysis is installed from source.

But scipy can be installed via `pip` without having numpy installed because they uploaded wheels to PyPi instead of eggs.  So the only chance I see to fix this is converting our PyPi-package to a wheel.
But I suggest we wait with that until we refactored all C-extensions to be Py3 compatible. Then they should all hopefully be cleaned up making the process of building wheels easier.

Solving #368 here might actually help us for the process of distributing wheels if we use travis to build and upload them to PyPi

**Comment by orbeckst** [comment]
It seems there really isn't any sensible way to solve this issue at this moment so I am going to close it; we can revive it at a later date.

**Comment by mnmelo** [comment]
So, I dug a bit around and found that `setup.py` only uses `numpy` to find its include path.
By subclassing `setuptools.Extension` I could make a smart class that only really attempts to read `numpy`´s include dir at install time.
This seems to fix our problems but I'd appreciate it if someone else would test it in their virtualenvs. (PR #498)

On my tests the only issue was that `biopython` seems to suffer the same problem as we do, and defaults to a crippled install if `numpy` isn't found. Namely, as per their `setup.py`, the `Bio.Affy`, `Bio.Cluster`, `Bio.KDTree`, `Bio.Motif`, and `Bio.PDB.QCPSuperimposer` packages/extensions become unavailable. Even if `numpy` is later installed, `biopython` must be reinstalled/reconfigured to recognize it.

Do we use any of these functionalities?

**Comment by orbeckst** [comment]
Am Oct 19, 2015 um 17:58 schrieb mnmelo <notifications@github.com>:

> Do we use any of these functionalities?

Yes, we absolutely rely on Bio.KDTree.

**Comment by mnmelo** [comment]
Well, then I might as well forget about it... My workaround doesn't seem to be working anyway!

**Comment by mnmelo** [comment]
So, I kept at it and have a workaround that works for our case. PR #499 passes travis (yay) but that means little since its environment already has `numpy` installed.

I'd appreciate it if someone else could check that this works on their virtualenv(s).

We still face the problem that our dependencies (`biopython`) don't work around the pre-installed numpy issue. If we get this going would it be worth it trying to push similar solutions up to our dependencies?

**Comment by orbeckst** [comment]
Btw, on Mac OS X 10.6.8 there's no Biopython wheel so it would be useful to try and push a similar fix upstream to Biopython.

For the record, I had to do:
```
cd mdanalysis/package
pip install .  
pip remove biopython
pip install biopython
```

But everything else worked. Yay!

**Comment by orbeckst** [comment]
Well, just ask, maybe they simply hadn't had the bandwidth to come up with a better (= your) solution. 

--
Oliver Beckstein
email: orbeckst@gmail.com
skype: orbeckst


Am Oct 23, 2015 um 6:13 schrieb mnmelo <notifications@github.com>:

**Comment by mnmelo** [comment]
http://mailman.open-bio.org/pipermail/biopython-dev/2015-October/021106.html
