### ISSUE TITLE
Implement `AnalysisBase` class into `MDAnalysis.analysis.distances`

### ISSUE THREAD

**Issue by talagayev** [MDAnalysis/mdanalysis#4817]
Currently `MDAnalysis.analysis.distances` consists of separate functions `contact_matrix`, `dist` and `between`.
The main goal would be to implement an `AnalysisBase` class to have a structure similar to `MDAnalysis.analysis.rms`, which
would allow an easier implementation of the parallelization mentioned in #4661 

Things to be done:
- Implement an `AnalysisBase` class in `MDAnalysis.analysis.distances`
- Adjust tests in `test_contacts.py` if required

**Comment by orbeckst** [comment]
These functions do not do a frame-based analysis. I don't think that this module needs AnalysisBase — these are really more library functions than "analysis tools" and they seem somewhat out of place here.

Perhaps it makes sense to move them elsewhere???

I'll close the issue with "won't fix" because I don't believe these functions need AnalysisBase. Thank you for bringing it up!

**Comment by orbeckst** [comment]
FYI https://github.com/MDAnalysis/mdanalysis/blob/develop/package/MDAnalysis/analysis/distances.py

**Comment by talagayev** [comment]
Ah my bad, but good to know that they don't need an `AnalysisBase` :)
How is it then with Issue #4661 in that case?
