### ISSUE TITLE
tidynamics required by FFT in EinsteinMSD but not in requirements

### ISSUE THREAD

**Issue by tulga-rdn** [MDAnalysis/mdanalysis#4852]
Hi! A small issue: when running `MDAnalysis.analysis.msd.EinsteinMSD` with `fft=True`, it throws an error that `tidynamics` is not installed even though it is not in the requirements

**Comment by RMeli** [comment]
Hi @tulga-rdn. Assuming the error you see is
```
ERROR --- tidynamics was not found!
                tidynamics is required to compute an FFT based MSD (default)
                try installing it using pip eg:
                    pip install tidynamics
                or set fft=Fals
```
this is intended. `tidynamics` is an _optional_ dependency of MDAnalysis
https://github.com/MDAnalysis/mdanalysis/blob/4f143fdf02ddf9cdb43b0e69edc7cb41bb455556/package/pyproject.toml#L87
It is not required to be installed to use MDAnalysis, but if you try to use part of the code that needs it, then the nice error message on how to install it is printed out, so that users can take the necessary steps to make their code work (i.e. setting `fft=False` or installing `tidynamics`).

**Comment by tulga-rdn** [comment]
Yes, if it was intended, then I'll close my PR as well - I thought maybe it was smth that was forgotten and left over. Cheers!

**Comment by RMeli** [comment]
Thanks, and no worries!
