### ISSUE TITLE
Is the Amber netcdf writer fully compliant with the official spec?

### ISSUE THREAD

**Issue by CharlieLaughton** [MDAnalysis/mdanalysis#488]
I have had a problem reading AMBER .ncdf files into the AMBER analysis tool cpptraj:

```
CPPTRAJ: Trajectory Analysis. V14.22
    ___  ___  ___  ___
     | \/ | \/ | \/ | 
    _|_/\_|_/\_|_/\_|_
        Reading 'penta.top' as Amber Topology
> trajin mdanalout.ncdf
        Reading 'mdanalout.ncdf' as Amber NetCDF
NETCDF Error: NetCDF: Attribute not found
Error: Getting length for attribute title
NETCDF Error: NetCDF: Variable not found
Error: Getting spatial VID
Error: Could not set up mdanalout.ncdf for reading.
Error: Could not set up input trajectory 'mdanalout.ncdf'.
```

At first I thought this was an issue with cpptraj and raised it as an issue there (https://github.com/Amber-MD/cpptraj/issues/123) , but it seems it may be a MDAnalysis issue.

**Comment by dotsdl** [comment]
Yeah, reading the discussion it appears the problem has to do with the missing "spatial" variable. This might be a quick fix if that's the extent of the issue, but fixing this issue should also result in a thorough evaluation of the Amber NCDF format spec and whether our Writer fully conforms with it.

**Comment by richardjgowers** [comment]
Iirc, the Amber spec docs are actually quite good too, so this *should* be a fairly routine fix... (fatal last words?)

**Comment by swails** [comment]
It should be a 2-line fix [here](https://github.com/MDAnalysis/mdanalysis/blob/develop/package/MDAnalysis/coordinates/TRJ.py#L692-L693)

You just need to add something like the following:

```Python
spatial = ncfile.createVariable('spatial', 'c', ('spatial',))
spatial[:] = np.asarray(list('xyz'))
```

**Comment by swails** [comment]
On a tangentially related note, my experience has been that *just* for parsing NetCDF3-compliant file formats (of which the Amber NetCDF trajectory is an example), scipy's NetCDF readers and writers are rather superior to the ones provided by `netCDF4`.

`scipy` is a more popularly installed library, doesn't require the NetCDF libs to link, and actually reads/writes a bit faster than `netCDF4` according to some short benchmarks on Amber trajectories.

**Comment by hainm** [comment]
@swails In my experience, scipy netcdf does not read all amber netcdf files. Is there any recent update on scipy that I don't know?

**Comment by swails** [comment]
I've never seen an instance where scipy has failed to read an Amber NetCDF trajectory file before...

**Comment by orbeckst** [comment]
@swails thanks for the comments. We have to decide if users are better of with us requiring `scipy` or `netcdf`, both are somewhat complicated but I completely understand your argument that a user might be more likely to have/need `scipy` anyway and we already use it in the `MDAnalysis.analysis` module as an optional dependency.

**Comment by CharlieLaughton** [comment]
If you want a "compliant" Amber .ncdf file to play with, I could suggest you grab spcbox.nc from the cpptraj GIT repository: https://github.com/Amber-MD/cpptraj/blob/master/test/spcbox.nc

**Comment by orbeckst** [comment]
Thanks Charlie, excellent suggestion.

On 15 October 2015 at 11:58, Charlie Laughton <notifications@github.com>
wrote:

> If you want a "compliant" Amber .ncdf file to play with, I could suggest
> you grab spcbox.nc from the cpptraj GIT repository:
> https://github.com/Amber-MD/cpptraj/blob/master/test/spcbox.nc
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MDAnalysis/mdanalysis/issues/488#issuecomment-148339016>
> .
>



-- 
Oliver Beckstein * orbeckst@gmx.net
skype: orbeckst  * orbeckst@gmail.com

**Comment by swails** [comment]
> We have to decide if users are better of with us requiring scipy or netcdf, both are somewhat complicated but I completely understand your argument that a user might be more likely to have/need scipy anyway and we already use it in the MDAnalysis.analysis module as an optional dependency.

Do you have a way of collecting statistics on that?  While both may be somewhat complicated to install from source, both are fairly readily available through standard package managers, conda, or even canopy.  My thought is that scipy is more likely to be part of the standard toolkit for a heavy scientific Python user than netCDF4, with the latter likely being installed for the sole purpose of reading Amber trajectories with MDAnalysis -- at least that's true for me.

And there's always the actual *functional* advantage of scipy's parsing being measurably faster than netCDF4 :).

**Comment by swails** [comment]
Also, I'm not sure if you are aware, but Amber recently (~2-3 years ago) introduced a new NetCDF-based restart file format.  The format spec is in the same document as the NetCDF trajectory, with a sample parser [here](https://github.com/ParmEd/ParmEd/blob/master/parmed/amber/netcdffiles.py#L237-L404) and a sample file at https://github.com/ParmEd/ParmEd/blob/master/test/files/ncinpcrd.rst7.

**Comment by orbeckst** [comment]
On 15 Oct, 2015, at 14:05, Jason Swails wrote:

> And there's always the actual functional advantage of scipy's parsing being measurably faster than netCDF4 :).

Point taken :-)

**Comment by hainm** [comment]
Actually there is only a single file in scipy for netcdf parsing. You can copy it to mda if you want. It is quite light.

**Comment by orbeckst** [comment]
... and this single file is derived from [pupynere](https://bitbucket.org/robertodealmeida/pupynere/src) (although the scipy implementation is apparently Py3 ready whereas pupynere is not at the moment:[pupynere issue #8](https://bitbucket.org/robertodealmeida/pupynere/issues/8/python-3-port)).

**Comment by kain88-de** [comment]
Does the scipy implementation support the new netCDF4 format? netCDF4 is build on top off HDF5 and changed the standard a little bit by introducing groups. I can't find any hint in the docs and I can't remember that I needed to install hdf5 libraries to build scipy? Also from the source it looks like they are rather only able to parse the older netCDF3 standard. 

If we want to fully support the netCDF4 we should use a library that makes full use of the standard instead of one that can only read netCDF3 compatible files.

**Comment by orbeckst** [comment]
The Scipy implementation only supports netcdf3. That's sufficient for Amber, which is the only use case in MDA at the moment. 

--
Oliver Beckstein
email: orbeckst@gmail.com
skype: orbeckst


Am Oct 19, 2015 um 10:12 schrieb kain88-de <notifications@github.com>:

**Comment by orbeckst** [comment]
I tried the `scipy.io.netcdf` implementation instead of the `netCDF4` one for `NCDFReader` and `NCDFWriter` in the branch [feature/scipy-ncdf](https://github.com/MDAnalysis/mdanalysis/tree/feature/scipy-ncdf). The API is a wee bit different but otherwise the same tests as before pass.

However, at least looking at our unit tests, I find that netCDF4 is *much* faster than the pure python implementation (speed for `test_netcdf` on a single core (42 tests)):
   - netCDF4 + lib netcdf + lib hdf5: **6.562 s**
   - scipy.io.netcdf:  **25.545 s**
 i.e. at least in our case, using netCDF4 seems ~4x faster.

Perhaps someone could do a more careful benchmark, especially reading or writing longer trajectories.

Another potential disadvantage of the pure-python implementation is that it uses `mmap` by default (which is a good idea) but it means that one cannot just close the file if a reference to a mmap'ed array is still open. This might confuse users and it might make it harder to implement e.g. #239.

One possibility would be to use `scipy.io.netcdf` as a fall back if a user does not have `netCDF4`; we could even bundle the single file as very last resort. The code would look a bit ugly because the APIs are not the same but it's do-able.

**Comment by hainm** [comment]
@orbeckst  per speed test, I've done only reading (not writing). My observation is similiar to [xray] (https://github.com/xray/xray/issues/368).

per `mmap`, how's about `mmap=False`?
