### ISSUE TITLE
Handling enormous .gro files

### ISSUE THREAD

**Issue by tylerjereddy** [MDAnalysis/mdanalysis#550]
Although I can't immediately provide a non-confidential sample input file, I believe MDAnalysis is having problems handling the writing of `.gro` files with > 10 million particles. The actual file has more than 12 million particles, but I suspect the issue might occur when moving from 10^6 to 10^7 particle count, though it may be something else. By visual inspection, many of the coordinates get botched while a few remain reasonable, which is again consistent with some kind of truncation thing.

The final portion of the traceback when reading the file back in to MDA is as shown below. The writing process completes silently, without warning.

``` 
/Users/treddy/.local/lib/python2.7/site-packages/MDAnalysis-0.13.0.dev0-py2.7-macosx-10.5-x86_64.egg/MDAnalysis/coordinates/GRO.pyc in _read_first_frame(self)
    145                     continue
    146                 for i in xrange(3):
--> 147                     ts._pos[pos, i] = float(line[20 + cs*i: 20 + cs*(i+1)])
    148 
    149                 if not has_velocities:

ValueError: invalid literal for float(): 0  83.71
```

**Comment by richardjgowers** [comment]
https://github.com/MDAnalysis/mdanalysis/blob/develop/package/MDAnalysis/coordinates/GRO.py#L212

I think the problem will be here

```
In [1]: import MDAnalysis as mda

In [2]: fmt = mda.coordinates.GRO.GROWriter.fmt

In [3]: fmt['xyz']
Out[3]: '{resid:>5d}{resname:<5.5s}{name:>5.5s}{index:>5d}{pos[0]:8.3f}{pos[1]:8.3f}{pos[2]:8.3f}\n'

In [4]: fmt['xyz'].format(resid=1, resname='rname', name='name', index=1000000, pos=(1.0, 1.0, 1.0))
Out[4]: '    1rname name1000000   1.000   1.000   1.000\n'
```

The index field needs to crop to 5 decimal places, taking only integers from the RHS of the number

**Comment by richardjgowers** [comment]
It might just be as simple as `int(str(atom.index + 1)[-5:])`

**Comment by cing** [comment]
Don't know about the error, but you can generate a box of water with 12 million atoms and 4 million residues using GROMACS pretty easily,
```
gmx solvate -cs spc216.gro -box 50 50 50 -o bigbox.gro; #GROMACS5
genbox -cs spc216.gro -box 50 50 50 -o bigbox.gro; #GROMACS4
```
It comes to 539M ;)

**Comment by tylerjereddy** [comment]
@richardjgowers I'd like a solution that works at the `.format` stage (i.e., built into the format string). Unfortunately, this is impossible with python string formatting (and indeed with `C` `printf` itself -- see: http://stackoverflow.com/a/26532792/2942522). I had originally written a unit test for this in `fix-huge-gro` branch, only to discover it is impossible to fix that unit test!

We could truncate from the left fairly easily using the format string. But, I guess what I'll have to do is create a unit test for checking downstream in the control flow (in the actual written file I suppose). Can we easily fool MDAnalysis into writing a really small file with huge atom indices, without triggering index errors of various kinds? The fix itself is probably much easier than the design of the appropriate unit test.

**Comment by richardjgowers** [comment]
https://github.com/MDAnalysis/mdanalysis/blob/develop/package/MDAnalysis/coordinates/GRO.py#L288

Because we're enumerating atoms (to make them number from 1 to n within the gro file), it's not easy to test the atom's index wrapping over 100k without creating a file that large.

If we use a fix like below, we can make the max index (5 below, 100,000 for the real fix) part of the class and then edit it to make it wrap sooner and check that?

Or maybe making a gro file with 100,000+ atoms isn't that bad anyway, I think it comes to about a 9mb file.

```
In [12]: atoms
Out[12]: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [13]: zip(atoms, itertools.cycle(xrange(5)))
Out[13]: 
[('a', 0),
 ('b', 1),
 ('c', 2),
 ('d', 3),
 ('e', 4),
 ('f', 0),
 ('g', 1),
 ('h', 2),
 ('i', 3),
 ('j', 4)]
```

**Comment by orbeckst** [comment]
Gromacs implements funky things for the precision in [their specification of the GRO format](http://manual.gromacs.org/current/online/gro.html):

"This format is fixed, ie. all columns are in a fixed position. Optionally (for now only yet with trjconv) you can write gro files with any number of decimal places, the format will then be `n+5` positions with `n` decimal places (`n+1` for velocities) instead of 8 with 3 (with 4 for velocities). Upon reading, the precision will be inferred from the distance between the decimal points (which will be `n+5`). Columns contain the following information (from left to right):

* residue number (5 positions, integer)
* residue name (5 characters)
* atom name (5 characters)
* atom number (5 positions, integer)
* position (in nm, x y z in 3 columns, each 8 positions with 3 decimal places)
* velocity (in nm/ps (or km/s), x y z in 3 columns, each 8 positions with 4 decimal places)
"

However, this seems to imply that GROMOS87 gro files are handicapped in the number of atoms and residues that they can represent. If Gromacs can read or write these files I recommend looking at their source code to check exactly what they do (assuming that we strive for interoperability instead of implementing standards... which in the MD field appear to be [more guidelines than actual rules](https://www.youtube.com/watch?v=b6kgS_AwuH0)....)

**Comment by orbeckst** [comment]
Btw, should this be labeled a *defect* or an *enhancement*?

**Comment by tylerjereddy** [comment]
Strangely, I can also produce a problem with .gro file writing when I do something like the following, even when working with smaller numbers of particles:

```python
sel = u.select_atoms('not (resname W or resname WF or resname ION)')
sel.write('test.gro')
```
The result has the correct number of coordinates, but something is very wrong based on inspection in VMD.

I wonder if that is a separate issue. Regardless, it probably shouldn't misbehave silently. Is that selection string one of those cases where it doesn't produce what you'd expect? It seems (again) that the particle count is correct though. I'm basically just using MDAnalysis to filter out solvent particles, but keep ending up having to do this manually in vim, which (ideally) wouldn't be the preferred method.

**Comment by orbeckst** [comment]
If you have a small file then post it. From your description I don't understand what "very wrong" entails. If some parts are displayed correctly then I'd try to identify bad parts (eg by identifying particles in VMD) and then looking at the lines in the written file. Or start bisecting the file until the/a bad part is isolated.

**Comment by tylerjereddy** [comment]
It turns out this is still a truncation problem because MDAnalysis is failing to write `.gro` files properly at the `100,000` particle threshold. This is a lot lower than I would have thought, but the results from my quick and dirty testing below are pretty clear.

The test code output (cor=expected; mda=written by mda):
```
line mismatch at line 100001 in .gro file:
cor:   243PRO  SSAC200000  26.432  41.003  27.683
mda:   243PRO  SSAC2100000  26.432  41.003  27.683
```


The (very rough) test code:
```python
   with open('final_snapshot_compact_no_solvent.gro') as correct_file:
       with open('mda_out.gro') as mda_file:
           list_correct_file_lines = correct_file.readlines()
           list_mda_file_lines = mda_file.readlines()
           for line_number in xrange(len(list_correct_file_lines)):
               if not list_correct_file_lines[line_number] == list_mda_file_lines[line_number]:
                   print 'line mismatch at line {num} in .gro file:\n'.format(num=line_number), 'cor:', list_correct_file_lines[line_number], 'mda:', list_mda_file_lines[line_number]
                   break
```

**Comment by tylerjereddy** [comment]
Anyway, I'll have to take a look at how GROMACS itself does this at some point. As discussed above, it is not difficult for me to crudely fix the behaviour, but doing it the right way and with a nice test or two may require a bit more thought.

**Comment by broken1999** [comment]
http://manual.gromacs.org/archive/4.6.3/gmxfaq.html#systemsize

"
Note that the .gro format only support atoms numbers up to 99999, so it will loop once it reaches 100000 atoms. This is no problem in GROMACS since we don't use the atom number from the .gro file.
"
