### ISSUE TITLE
why should encourage user to use conda

### ISSUE THREAD

**Issue by hainm** [MDAnalysis/mdanalysis#567]
Just my 2 cents to reply to @ashkurti https://github.com/MDAnalysis/mdanalysis/issues/551#issuecomment-162601669

> I do not use conda as a point of principle so as I have more control myself on what has been installed and how has been installed. Plus a large number of users of the packages I have been developing do not use conda and I get questions related with separate packages installation issues, so I will need to face them myself first.

I agree that if you (in general) already have well established workflow, there is no point to 'upgrade'. But in the future, conda might help both developers and users to avoid headache. 

First, I don't see any other ways to install new package that is easier than conda. You can install pandas, numpy, scipy, ... within 10 **seconds** rather bothering installing from source code. Instead of trying to encountering bugs from traditional installing so help users, just persuade them to use conda (for greater good).
If you need them to install scipy, tell them `conda install scipy`, pandas? `conda install pandas`, ... (within few seconds).

> I do not use conda as a point of principle so as I have more control myself on what has been installed and how has been installed.

#### conda give you full control of what you installed, it can give you a list of packages in your env
- create new env
`conda create -n myenv python=2.7 numpy scipy ipython`

- activate
`source activate myenv`

- wanna update some package?
`conda update numpy`

This is the comparison between conda and virtualenv: http://conda.pydata.org/docs/_downloads/conda-pip-virtualenv-translator.html

### MDanalysis should use conda
This is workflow 
- push commit to travis
- build mda package by conda
- do the testing
- if good, push to anaconda.org so user can easily install by `conda install -c mdanalysis mdanalysis` (as an example).

Just give an example from my [pytraj] (https://github.com/Amber-MD/pytraj) package. It's Python front-end of [cpptraj] (https://github.com/Amber-MD/cpptraj), written in C++. Ask user to install `pytraj` from source code with cpptraj is too much work. So for inexperienced users, I just direct them to install `conda` then copy and paste `conda install -c ambermd pytraj-dev`. This will install precompiled cpptraj library, libnetcdf, numpy and pytraj. All happen within 30 seconds (vs 10 minutes if installing from source).

**Comment by hainm** [comment]
@richardjgowers it would be nicer if you can close an issue with a comment (saying why).

**Comment by ashkurti** [comment]
@hainm thank you, apparently you have a very strong opinion hear and well done on its documentation, there are some very interesting points that I will explore carefully.

One thing - what does the "my 2 cents to answer to @shkurti" expression mean though ...

**Comment by hainm** [comment]
> ? One thing - what does the "my 2 cents to reply to @shkurti" expression mean though ...

@ashkurti: sorry to not to be clear (due to my English). My 1st post meant to reply to your comment about your rationale to keep using `virtualenv` (I put a link to your comment too). I intended to reply to you in that issue but created this new issue so people can discuss more about `why should use conda`. Hopefully I am clear now.

**Comment by hainm** [comment]
The reason I created new issue because @orbeckst encourages people to do so. (Am I right?)

**Comment by orbeckst** [comment]
So far we haven't endorsed one way of installing python packages over any other, or rather, we take `pip install` as the canonical way to do things and try to make sure that this works and leave it to the users to install their scientific python stack by whatever method they feel comfortable with.

For workshops I have been suggesting to participants to use conda because we know we can get it to work (we use it in travis at the moment) but personally and in my lab we don't use it, pretty much for the reasons @ashkurti mentioned.

It might be good to also have a version of MDAnalysis installable from anaconda.org (if it can be integrated with minimal interruptions into the current workflow), simply because it gives more options to users and, as @hainm says, it can be especially useful for less epxperienced users. But I freely admit that I have no idea what one has to do for this to happen. This is again where the open source nature of MDAnalysis comes into play: if someone feels strongly enough about something, submit a PR that prototypes what needs to be done. For something like uploading to a different repo etc, this might not be that easy so instead open an issue and describe, step-by-step, what needs to be done (with links to relevant docs).
