### ISSUE TITLE
Make a copy of an MDAnalysis Universe (feature request)

### ISSUE THREAD

**Issue by tomnewport** [MDAnalysis/mdanalysis#635]
I would like to be able to make a copy of an MDAnalysis universe so I can modify it without making changes to the original file (edit - original universe object). Is this currently possible? (I checked the documentation and it appears not, but maybe I misread it)

    original = Universe("myfile.pdb")
    def make_modified_copy(original)
        changed = original.copy()
        # Modify changed
    make_modified_copy(original)
    # Modify changed universe without modifying original universe

**Comment by kain88-de** [comment]
MDAnalysis doesn't change files by default. You have to explicitly write a new topology or trajectory

To get two copies in python of the same topology you can do.

```python
>>> from MDAnalysisTests.datafiles import PDB
>>> u_1 = mda.Universe(PDB)
>>> u_2= mda.Universe(PDB)
>>> # change coordinates from u_2
>>> u_2.atoms.positions = np.random.rand(size=(u_2.atoms.positions.shape))
>>> np.any(u_2.atoms.positions == u_1.atoms.positions)
False
>>> # reloading the pdb will show that the coordinates in the file are still the same
>>> u_3 = mda.Universe(PDB)
>>> np.any(u_3.atoms.positions == u_1.atoms.positions)
True
``` 

All changes to the coordinates are in memory. If you want to write the changed universe to a new file do

```python
with mda.Writer('new-filename.pdb', n_atoms=u.atoms.n_atoms) as w:
    w.write(u)
```

**Comment by tylerjereddy** [comment]
If you want to create a new Universe with modified contents (and avoid writing a new file) you could for example use `Merge()` as shown in the docs for system building (https://pythonhosted.org/MDAnalysis/documentation_pages/core/AtomGroup.html#combining-objects-system-building):

```python
import MDAnalysis
u1 = MDAnalysis.Universe("protein.pdb")
u2 = MDAnalysis.Universe("ligand.pdb")
u3 = MDAnalysis.Universe("solvent.pdb")
u = MDAnalysis.Merge(u1.select_atoms("protein"), u2.atoms, u3.atoms)
u.atoms.write("system.pdb")
```

Copying or deep copying of universes is problematic because of the open file socket I think. But you can usually do topology manipulation with this kind of strategy, but you'll definitely want to check that setting / manipulating coordinates in the new universe actually worked properly, etc., because it can be a little tricky sometimes

**Comment by tomnewport** [comment]
Sorry, my sloppy writing - I wanted to avoid modifying the original object, rather than the file. Thanks, @tylerjereddy, that was exactly what I wanted.

**Comment by orbeckst** [comment]
See also #1029
