### ISSUE TITLE
Atom names are not always written correctly in PDB files

### ISSUE THREAD

**Issue by jbarnoud** [MDAnalysis/mdanalysis#647]
In a PDB file, atom names are written on 4 characters, and spaces carry some meaning. Thus the atom name for a carbon alpha is '`.CA.`', while the atom name for a calcium ion is '`CA..`' (dots are there to show the spaces). When reading a PDB file, MDAnalysis strips the spaces from atom names. This is expected as manipulating striped atom names is easier, and as the spaces in atom names are meaningless in most other formats. Yet, it means that MDAnalysis must rely on tricks to write PDB files correctly (see #641).

The issue is that the trick does not always work. For instance, the atom name for a calcium ion will be written '`.CA.`' like a carbon alpha, rather than '`CA..`' as it should. Some odd atoms in modified residues will not be written as expected either; it is the case for the selenium in selenomethionine that will be written '`.SE.`' instead of '`SE..`'.

[4D3L](http://www.rcsb.org/pdb/explore/explore.do?structureId=4D3L) has both calcium atoms and selenomethionine residues. It can be used to demonstrate the issue:

```python
import MDAnalysis as mda
u = mda.Universe('4d3l.py')
with mda.Writer('mda.py') as w
    w.write(u)
```

The carbon alpha is written (almost) as expected:

```
# first the original, then the file written by MDAnalysis
ATOM      2  CA  SER A 494      54.927 -20.568   1.220  1.00 31.56           C 
ATOM      2  CA  SER A 494      54.927 -20.568   1.220  1.00 31.56      A   C 0.00
```

The selenium atoms and the calcium ion have their atom name shifted (and their atom type wrong):

```
# first the original, then the file written by MDAnalysis
# selenium
HETATM  184 SE   MSE A 516      28.106 -22.839  -6.133  1.00 30.15          SE
ATOM    184  SE  MSE A 516      28.106 -22.839  -6.133  1.00 30.15      A   S 0.00

# calcium
HETATM 3177 CA    CA B1631      12.932 -51.723 -21.045  1.00 83.06          CA
ATOM   3174  CA  CA  B1631      12.932 -51.723 -21.045  1.00 83.06      B   C 0.00
```

I do not really know how to solve this issue. With the new attributes, it could be possible to keep a `pdb_name` attribute; but it would not solve the problem of writing PDB files from an other format. We could also have a guesser that guess the name as written in a PDB file.

**Comment by richardjgowers** [comment]
We've currently got 2 pdb parsers and 2 pdb readers, and I'd love to squash this all done into 1 of each.  I've done my best at making PrimitivePDBParser on the 363 branch work, but I don't use the format myself, so feel free to improve it.  I think @kain88-de had an example that didn't work on the mailing list.

I think being able to do a roundtrip with pdbs should be a good target.

One problem with whitespace is it will mess a lot with the selection system.  So how do I select `' Ca '` rather than `'Ca  '`.  So we'll need to maybe think about some sort of escape character for allowing spaces.

**Comment by jbarnoud** [comment]
I do not use much PDB files either; they are way to messy and they do 
not like 4 characters residue names.

Maybe the best would be to fix the issue on the 363 branch. I can have a 
look next week if nobody volunteered until then.

**Comment by orbeckst** [comment]
I disagree with the idea that you need to preserve spaces in atom names. The PDB specs state that having the name anywhere in the 4 columns is fine but depending what it is, different positioning is customary. Ultimately, a type/element guesser can take a hint from it but the real solution is to dig into the other records of a PDB file that tell you the identities of non-standard atoms. 

A Ca2+ ion will simply have the atom name CA and there's nothing you can do about it. That's why the C-alpha selection *should* be "protein and name CA" and not just "name CA".

For proper round-tripping you'd need to take into account what kind of atom it is. Would be do-able to implement. Did anyone check what the BioPDB PDB parser (our "strict" one) does?

I'd be happy to only have a single PDBParser. But the reason for keeping BioPDB around is that they figured out how to do many of the PDB quirks such as insertion codes etc that are not relevant when you do simulations *unless* you want to set up a system from a real PDB structure.

**Comment by jbarnoud** [comment]
Actually, the format for atom names is even more defined than what I though. Here is what I found from the [PDB format description](www.wwpdb.org/docs/documentation/file-format/PDB_format_1992.pdf) (page 26):

>    Four characters are reserved for these atom names. They are assigned as follows:
>    1-2 Chemical symbol - right justified
>    3 Remoteness indicator (alphabetic)
>    4 Branch designator (numeric)

Or, in the [definition of the ATOM field from a more recent document](http://www.wwpdb.org/documentation/file-format-content/format33/sect9.html#ATOM):

> Alignment of one-letter atom name such as C starts at column 14, while two-letter atom name such as FE starts at column 13.

The clearer definition I found is from the [documentation of Chimera](https://www.cgl.ucsf.edu/chimera/docs/UsersGuide/tutorials/pdbintro.html#misalignment):

> Atom names are composed of an atomic (element) symbol right-justified in columns 13-14, and trailing identifying characters left-justified in columns 15-16. A single-character element symbol should not appear in column 13 unless the atom name has four characters.

As I understand it, in the case of a carbon alpha, `CA` should be splited in the element `C` right justified on columns 13-14 and a 'remoteness indicator' `A` that follows. In the case of the selenium, there is no 'remoteless indicator' and just the atom element `SE` right aligned on columns 13-14.

**Comment by kain88-de** [comment]
Honestly I find neither of them very clear. The example from the chimera website are nice but they don't explain for me what should happen for your 'CA' case. I read it as they would have to be written the same way.

**Comment by jbarnoud** [comment]
> Honestly I find neither of them very clear. The example from the chimera website are nice but they don't explain for me what should happen for your 'CA' case. I read it as they would have to be written the same way.

In the case of a carbon alpha, the name `CA` is made from two parts: the `C` means carbon, and the `A` means that it is the one called A. The `C` being the element—we can also say the atom type—is written right aligned in columns 13-14. This gives `.C` (the dot shows the space). The `A` is  a "remoteness" indicator; it should be written left aligned on columns 15-16: `A.`. The two combined, we have `.CA.`.

In the case of the calcium, `CA` is the atom type. Being the atom type, it should be written right aligned on columns 13-14: `CA`. Since there is nothing else to the atom name, columns 15-16 are empty. This gives `CA..`.

Once read, the atom names of both the carbon alpha and the calcium are `CA`. But they are aligned differently when written in a PDB file.

Ultimately, the difference is small. But currently the PDB file we write do not follow the format, and that potentially means that some program can have issue reading them.

**Comment by orbeckst** [comment]
Am Feb 6, 2016 um 11:26 schrieb Jonathan Barnoud <notifications@github.com>:

> Ultimately, the difference is small. But currently the PDB file we write do not follow the format,

I couldn't find this specific formatting instructions in the PDB docs. Do you have a link except the Chimera docs?

> and that potentially means that some program can have issue reading them

We would need topology information to do this properly, specifically, we need to be able to guess the element correctly. 

If we can easily/reliably guess then we should align atom names in this fashion. (Conversely, an element guessed should also use this information...)

Is there something in 363 about improved element guessing?

**Comment by jbarnoud** [comment]
> I couldn't find this specific formatting instructions in the PDB docs. Do you have a link except the Chimera docs?

I gave the links and quoted the PDB format in a previous comment. The same as where I quote the Chimera doc.

**Comment by kain88-de** [comment]
Can we actually store something like remoteness indication and branch designator in our topology?

**Comment by richardjgowers** [comment]
Yeah we can store whatever we want, so a PDB parser could read the three things detailed above as separate entries, and mangle them together for "name"

So then we could have things like this in Writers (and other things that might want to work with PDB)

``` python
try:
    name = atom.symbol + atom.remoteness + atom.branchdesignator
except AttributeError:
    name = atom.name
```

So try and get PDB record, otherwise fall back to using name

**Comment by kain88-de** [comment]
So what we need is a common nomenclature for the remoteness and branchdesignator that we use across mda and various topology formats. 

Then we can write atom names correctly for hopefully all supported formats.

**Comment by jbarnoud** [comment]
I investigated how much we can guess the atom name based on the striped atom name and the residue name. It appears that we can guess quite a lot. It helps that there are actually very few problematic cases. Here is a notebook were I tried to guess the atom names for all (residue name, atom name) in the PDB; <https://gist.github.com/jbarnoud/37a524330f29b5b7b096>. By hard coding a surprisingly short amount of exception, I managed to guess the atom names for all pairs that appeat in more than 5 files in the whole PDB.
