### ISSUE TITLE
tests should not use a Python `assert` statement but instead use `numpy.testing.assert_`

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#724]
We still use `assert` in our test cases. The Python `assert` statement is [optimized away with `python -O`](https://docs.python.org/2/reference/simple_stmts.html#the-assert-statement), in which case some of the tests become useless. I don't think that tests are run with `-O` but better do it right because there's the potential for corrupted tests.

In all tests, `assert` should be replaced with `assert_`:
```python
from numpy.testing import assert_
```
(Do not alias to `assert` because that will be confusing and the calling signature is different: `assert_` is a function while `assert` is a statement.)

## `numpy.testing.assert_`
Doc string (cannot find it as a link to the online docs):
```
assert_(val, msg='')
    Assert that works in release mode.
    Accepts callable msg to allow deferring evaluation until failure.

    The Python built-in ``assert`` does not work when executing code in
    optimized mode (the ``-O`` flag) - no byte-code is generated for it.

    For documentation on usage, refer to the Python documentation.
```

## `assert` vs `assert_` 
You can test for yourself with gist [assert_test.py](https://gist.github.com/orbeckst/9e46d0653bf20fa0172d):
```bash
$ python assert_test.py
assert found an error
assert_ found an error
```

versus
```bash
$ python -O assert_test.py
py_assert did not raise exception but it should have!
assert_ found an error
```

**Comment by tylerjereddy** [comment]
As I understand it, the plain `assert` statement mostly shouldn't be used in unit testing modules, but looking around the internet there seem to be some long debates about this stuff. It is certainly to be used in the actual code base where you can ignore these statements (if you *really* need to) with the performance flag. So, `assert` in the code base commonly complements (but doesn't replace) actual unit tests, as you know.

I've occasionally wondered if mixing the standard library `unittest` module and `numpy.testing` is confusing, but they seem to work together well enough. 

Is there an example of a unit test in MDAnalysis where the python `assert` statement is needed and unambiguously more sensible than using `assertEqual` from `unittest`? The latter will often provide a more detailed feedback upon failure (i.e., the mismatched values in question). Do we really want to use `assert_` from `numpy` instead of `assertEqual` from the standard library? Isn't it a bit awkward to pull in something that "looks similar with an underscore at the end," from a different library, just to avoid the performance flag obliteration? I feel like these cases, in the context of the unit testing modules, are more cleanly replaced with `assertEqual`. 

My opinion seems to be shared by some (i.e., http://stackoverflow.com/a/6361186), but I'm sure you could find counter arguments as well. That SO response in particular also cites the superior feedback upon test failure when using the `unittest` methods over the statement. See also: http://stackoverflow.com/a/2958183

**Comment by orbeckst** [comment]
Am Feb 18, 2016 um 3:41 schrieb Tyler Reddy <notifications@github.com>:

> Is there an example of a unit test in MDAnalysis where the python assert statement is needed and unambiguously more sensible than using assertEqual from unittest

I have no problem with using assertEqual --- I went with assert_ because we need numpy.testing anyway and the syntax is similar to all other np testing assertions.

Anything but assert ;-)

**Comment by dotsdl** [comment]
I personally don't mind `assert`,  and for what it's worth the widely-used [pytest](http://pytest.org/latest/getting-started.html) testing module encourages their use as the primary assertion mechanism. But I'm for us being consistent, so happy to just use `numpy.testing` statements to get it done.

**Comment by jbarnoud** [comment]
If I well remember, the case of pytest is a bit different as pytest does some AST analysis to change the behavior of assert.
