### ISSUE TITLE
incorrect multiframe PDB format

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#741]
The mult-PDB writer appears to write HEADER and TITLE records for each MODEL (frame). This appears to be against the PDF file format description.

For more details (right now) see #734 .

**Comment by kain88-de** [comment]
So this happens because I of an inconsistent API. For PDBs the `write` method assumes that only a single frame will be written. So when I'm using write instead of `write_next_timestep` the HEADER record is written for every frame.

Upto now I assumed that `write` is the preferred method to us for writing trajectories manually with the writer interface. Is this not the case?

**Comment by orbeckst** [comment]
I don't think that it was ever intended that the two methods would give different results.

**Comment by kain88-de** [comment]
@richardjgowers you designed the new BaseWriter API. Do I assume correctly that `write` accepts arbitrary `Universe  / AtomGroup / Timestep` objects and should do any preparations necessary on object before passing it to `write_next_timestep`. While `write_next_timestep` should only accept timesteps and write them as they are?

If this is correct then `write` and `write_next_timestep` should give the exact same result when called with a TimeStep object. And that `write` is the preferred method for users to use, while `write_next_timestep` is more thought of as an internal method that should only be used for 'experts'.

**Comment by richardjgowers** [comment]
@kain88-de I'm not sure I defined Writer, I thought I just did the Readers.  Part of the reason why being Writers are a bit anarchic atm.

So with current behaviour, I think any of those three objects are used depending on what is needed.  If I had to guess, I'd say `DCDWriter` (the original/"base" format) just needed a `Timestep`, so `write_next_timestep` just required that, so that when PDB/XYZ came around they started using weird hacks as Timestep has no atom names.

In the future... I'd love to fix Writers.  I think of those three objects (Uni / AG / TS), I think we should base the API around AG as it has all the information, but only represents one frame (`W.write(Uni)` could be taken as write the entire trajectory)

This would mean we change our idiom of how to write a trajectory out though:
```python
with mda.Writer('out.dcd', n_atoms=len(ag)) as W:  # maybe fix how size is defined?
    for ts in u.trajectory:
        W.write(ag)  # NOT W.write(ts)
```

**Comment by kain88-de** [comment]
Well your code is exactly how I use the writer interface. It's the most natural to me.

**Comment by richardjgowers** [comment]
I think the idiom that's written everywhere (tutorials, examples etc) is `W.write(ts)`, which isn't sufficient for other formats

**Comment by kain88-de** [comment]
If someone wants to have a shoot at this. The fix to stop writing `HEADER` and `TITLE` records when using `MDAnalysis/coordinates/PDB.py:PrimitivePDBWriter.write`.
