### ISSUE TITLE
Atoms return a view of data (pos/vel/force)

### ISSUE THREAD

**Issue by richardjgowers** [MDAnalysis/mdanalysis#755]
### Expected behaviour

Doing a list comprehension of an Atom Timestep property to get a time series

### Actual behaviour

Get an array of only the first frames data, repeated many times

### Code to reproduce the behaviour

``` python
import MDAnalysis as mda

u = mda.Universe(top, trj)

[u.atoms[0].position for ts in u.trajectory]

```

### Currently version of MDAnalysis:
(run `python -c "import MDAnalysis as mda; print(mda.__version__)"`)

0.14.1-dev0

Took me a while to get it, but `Atom.position/velocity/force` is returning a view onto the array in Timestep,
so after iteration when the trajectory rewinds, all these views point to the same array address.  Just needs a copy call somewhere

AtomGroup is unaffected as it does a fancy index, and therefore always gets a copy.

**Comment by hainm** [comment]
you might need to measure performance too. I got similar issue in pytraj.

```python
[frame.xyz for frame in traj]
```
will return a list of identical coordinates. User needs to explicitly call copy method
```python
[frame.xyz.copy() for frame in traj]
```
I did not introduce the copy in pytraj because this will make the data loading from disk very slow (two times slower than before). And users can access positions from `traj.xyz` or from `pytraj.get_cooridiates(traj, frame_indices=...)`

Disclaim: I am sure much about MDA implementation, just want to share my though.

**Comment by orbeckst** [comment]
We *could* go with explicit copy if the performance hit is sizable.

The downside would be inconsistent behavior between `Atom` and `AtomGroup`, which is probably worse.

Does the change impact performance elsewhere, e.g., when we create AtomGroups or positions for AtomGroups?

**Comment by dotsdl** [comment]
There doesn't appear to be any noticeable difference on my machine doing:

```python
import MDAnalysis as mda
from MDAnalysisTests.datafiles import GRO, XTC

u = mda.Universe(GRO, XTC)

[u.atoms[0].position for ts in u.trajectory]
```

vs.

```python
[u.atoms[0].position.copy() for ts in u.trajectory]
```

If what we gain from making the second (returning a copy) is consistency with the behavior of everything else, I say we do it. The current behavior is pretty useless as it stands.

**Comment by orbeckst** [comment]
I think "useless" is a bit too strong here; I doubt that the list comprehension use case is the most common one. But nevertheless, I agree that consistency with `AtomGroup.positions` (which always returns a copy due to fancy indexing) would be important.

Which parts of the code do something like `Atom.position`? 

If you do a PR to add a copy we should check that this does not impact anything else negatively.

**Comment by orbeckst** [comment]
Btw, I timed it on my machine and got 45.7 ms with and 45.1 ms without copy...

**Comment by hainm** [comment]
Oh, for this case, only a single atom is copied, so the speed shouldn't be much different. I see.

**Comment by kain88-de** [comment]
@dotsdl have you tried it with a large system? Something with several million atoms
