### ISSUE TITLE
Bio PDB single frame reader reads whole trajectory

### ISSUE THREAD

**Issue by kain88-de** [MDAnalysis/mdanalysis#775]
### Expected behaviour

PDBReader should read only the first frame

### Actual behaviour

The whole PDB is read and all timesteps are stored into one TimeStep

### Code to reproduce the behaviour

``` python
import MDAnalysis as mda

pdb = mda.coordinates.PDB.PDBReader('multiframe pdb')
ppdb = mda.coordinates.PDB.PrimitivePDBReader('multiframe pdb
pdb.n_atoms == ppdb.n_atoms
```

### Currently version of MDAnalysis:
0.15.0-dev0

### Possible solution

We ask for the atoms with `get_atoms` on the BioPython parser. But that method returns every single `ATOM` record found in the PDB. Instead we should use the `get_model` and only parse the first model. From that model we can make a list of the atoms.

**Comment by richardjgowers** [comment]
At some point we really need to look into if we actually need 2 separate PDB readers at all.  I'd much rather just fix our Reader so we can ditch the other (same with Parsing)

**Comment by orbeckst** [comment]
I agree with @richardjgowers ; the original idea of having Bio.PDBReader was so that we could easily parse real PDB files with altloc and other funny things. However, it does not seem that useful and we never gave the user any choice (e.g. which altloc to choose). I think our PDBReader can actually read altlocs since 0.9.0 anyway although I don't recall what we do with it (maybe that was @jandom ?).

On the other hand, the Bio.PDBReader complains about lots of atom names, has to be hacked in order to deal with large resnums, and is a bit of a pain... we should ditch it and just work on a single PDBReader.

This will allow us to name it just PDBReader, get rid off the annoying distinction between permissive and strict readers (that only exist for PDB) and I am sure everyone will be happier :-).

**Comment by orbeckst** [comment]
I think we should entertain any fixes for this issue if they come in, should be easy enough.
However, if someone wants to raise an issue to ditch Bio.PDBReader and gets it done before this one then all the better.

**Comment by kain88-de** [comment]
Yeah lets ditch it.
