### ISSUE TITLE
Add top-level function `from_PDB` for obtaining structure directly from PDB

### ISSUE THREAD

**Issue by dotsdl** [MDAnalysis/mdanalysis#810]
It would be nice to be able to get a Universe directly from the PDB without first writing the file to disk. This could be done using perhaps a `NamedStream` so that we could do:

``` python
import MDAnalysis as mda

u = mda.Universe(mda.from_PDB('4AKE'))

```

where `u.filename` just returns the web address the `NamedStream` pulled from.

**Comment by jbarnoud** [comment]
I would call the function `fetch_PDB`. I feel `from` is too generic, while `fetch` is most commonly used in that context.

**Comment by kain88-de** [comment]
`from_PDB` could also be confused that it generates a universe from a PDB. And I would rather go that the API is  `u = mda.fetch_PDB('4AKE')`.  

where `u.filename` just returns the web address the `NamedStream` pulled from. Sure this won't confuse analysis algorithms that assume `u.filename` is an existing file on hard drive? Wouldn't it be better to save the pdb in a temporary directory?

**Comment by richardjgowers** [comment]
U. Filename is always the topology, which is read once and never used
again. So pulling from Web matches this pattern too? Or should the filename
be a URL to make it clear?

**Comment by jbarnoud** [comment]
> Sure this won't confuse analysis algorithms that assume u.filename is an existing file on hard drive?

Most of the time, if the analysis does not assume it receives a stream, it does something wrong.

**Comment by kain88-de** [comment]
> Most of the time, if the analysis does not assume it receives a stream, it does something wrong.

The old *soon to be deprecated* ContactAnalysis for example uses `u.filename` to create a new copy of the universe, this wouldn't work with that approach or our universe object needs to recognize urls. I would almost bet that any of the other older analysis classes does something similar.

Not to mention all the custom analysis code users have build on top of MDAnalysis and that might be shared inside of a research group. I'm pretty sure that they implicitly assume that `u.filename` is an actually existing path because it is in 99% of all cases.

**Comment by orbeckst** [comment]
Given that we don't really universaly support streams everywhere (it's still a hack) I'd go with the unambiguous
```
u = mda.fetch_PDB('4AKE', cache=True, cachedir=os.curdir)
```

If you decide to cache, `u.filename` is the cached file on disk, otherwise the URL.

I'd probably cache in the current directory and provide another kwarg to specify an alternative cache dir.

(It would be cool if we could use streams interchangeably with files everywhere, although I am not sure if the benefits really balance the time to implement a good solution.)

**Comment by mnmelo** [comment]
There's a compact alternative (that I'm not entirely sure I prefer), which is to overload the `universe` constructor with it:
```python
u = mda.Universe('4AKE', fetch=True)
```

We can even make it more flexible, database-wise:
```python
u = mda.Universe('4AKE', fetch='PDB')
```

And maybe allow further keywords to differentiate between fetching topology and trajectory.

**Comment by hainm** [comment]
+1 vote for `fetch_PDB`, +2 for `fetch_pdb` (pytraj uses it :)) ).

**Comment by kain88-de** [comment]
> which is to overload the universe constructor with it:

No that will just be more confusing.

**Comment by orbeckst** [comment]
On 1 Apr, 2016, at 00:56, Hai Nguyen wrote:

> +1 vote for fetch_PDB, +2 for fetch_pdb (pytraj uses it :)) ).

I don't mind `fetch_pdb()`.

**Comment by richardjgowers** [comment]
I don't want to add another kwarg to Universe, just because of complexity,
but another good reason is if we make fetch return a stream,
fetch_pdb('thing').save('./mycopy.pdb') is a way of downloading the files.

**Comment by kain88-de** [comment]
> is a way of downloading the files.

wouldn't we need to download it anyway to create the stream? So better would be `fetch_pdb('4AKE', fname='foo.pdb')`. The we don't write a temporary file but *foo.pdb* directly.

**Comment by hainm** [comment]
@orbeckst  does MDA have intention to add on memory Universe? pytraj has both on disk and on memory objects. The on-memory is good for interactive work (such like visualization).

**Comment by orbeckst** [comment]
FYI, @tomnewport showed one way how to do the PDB downloading in his issue report for #839.

**Comment by richardjgowers** [comment]
FWIW, mmtf at #907 has this built into their API (according to website) and is arguably a better solution for downloading than bulky PDB files?

**Comment by orbeckst** [comment]
> On 22 Jul, 2016, at 03:05, Richard Gowers <notifications@github.com> wrote:
> 
> FWIW, mmtf at #907 has this built into their API (according to website) and is arguably a better solution for downloading than bulky PDB files?

Good idea, although users probably still want to have a PDB file locally, simply because many other tools won’t have MMTF support (yet). Does MMTF have a way to convert to a “native looking” PDB, i.e., one with all the metadata? 

--
Oliver Beckstein * orbeckst@gmx.net
skype: orbeckst  * orbeckst@gmail.com

**Comment by orbeckst** [comment]
Simple code (from #839):
```python
import urllib 
downloader = urllib.URLopener()

def fetch_pdb(pdb_id, download_url="http://files.rcsb.org/download"):
    filename = "{0}.pdb".format(pdb_id.lower())
    downloader.retrieve("/".join([download_url, filename]), filename)
    return filename

# example use:
fetch_pdb("1osm")
```

**Comment by orbeckst** [comment]
We should use the functionality provided by MMTF, see #913.
```python
import mmtf
m = mmtf.fetch('1ake')
```

... although this `m` is not immediately useable so I assume that the MMTFParser and MMTFReader would need to be changed so that they can deal with a `<mmtf.api.mmtf_reader.MMTFDecoder instance>`.
