### ISSUE TITLE
writing files from AtomGroup fails cryptically if wrong kwargs are supplied

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#877]
### Expected behaviour

Writing a AtomGroup to a file with `atoms.write("foo.pdb", bogus="whatever")` should either write the file or provide an error message that I supplied kwargs ('bogus') that are not appropriate for the writer.
### Actual behaviour

Instead I get the confusing error message

```
ValueError: No writer found for format: foo.pdb
```
### Code to reproduce the behaviour

``` python
>>> import MDAnalysis as mda
>>> from MDAnalysisTests.datafiles import GRO
>>> u = mda.Universe(GRO)
>>> u.atoms.write("foo.pdb", bogus="something something complete")
```

This will raise `ValueError: No writer found for format: foo.pdb`.
### Diagnosis

When detecting coordinate writer we use the following 

``` python
        # From the following blocks, one must pass.
        # Both can't pass as the extensions don't overlap.
        try:
            writer = MDAnalysis.coordinates.writer(filename, **kwargs)
        except TypeError:
            # might be selections format
            coords = False
        else:
            coords = True
```

But if the coordinate writer gets a `kwarg` it does not like then it raises a `TypeError`, too:

``` python
>>> mda.coordinates.writer('foo.pdb', bogus="something")
TypeError: __init__() got an unexpected keyword argument 'remark'
```

and _this_ `TypeError` is wrongly interpreted up to mean "there is no format". 
### Currently version of MDAnalysis:

(run `python -c "import MDAnalysis as mda; print(mda.__version__)"`)

0.15.0 (but also in develop).

**Comment by kain88-de** [comment]
This is because we are likely capturing an exception and then throw another without inspecting the original exception. Should be found in the *AtomGroup* class. If anyone fixes this please fix it in the issue-363 branch.

**Comment by tylerjereddy** [comment]
Issue is for PDB file writing only.

**Comment by orbeckst** [comment]
https://github.com/MDAnalysis/mdanalysis/pull/1115#issuecomment-265771494 : 
> Another question might be why PDB writing is a special snowflake, and if we'd really want to have different behaviours for handling invalid kwargs for different output filetypes.

[...]

> Just to clarify -- with formats other than PDB, the default appears to be silently writing the file. For PDB, the default will be to raise an appropriate exception.

Good point, @tylerjereddy . Before going much further we should really decide what kind of *consistent* behaviour we want. I see pretty much two options: writers

1.  **ignore unknown kwargs** (either silently or logging/raising a warning?)
2. **raise an exception for unknown kwarg** (Which exception, `TypeError`?) 

I would be in favour of **1** (possibly with a mild warning/INFO level debug) because kwargs are optional and the *meaning* of an optional kwarg is that it, well, should not be needed for proper operation. It behooves the user to know what they can and cannot write into a chosen format. It also makes writing in scripts/interactively smoother because one does not have to check all the kwargs manually all the time or catch exceptions.

**Comment by tylerjereddy** [comment]
Ignoring is probably ok since everything I've tested except PDB already does that. I thought the whole point of inheriting from the base writer class was to harmonize behaviour, but clearly PDB has something unusual about it--I wouldn't be surprised if it has to do with all the extra stuff PDB has to handle and / or the historical existence (I think this is gone now?) of two separate PDB handlers & frame-related things?!

Slightly more annoying is looking for low-hanging fruit in between bigger projects by looking for 'Easy' tags on the github issue tracker... my experience with these tags is that they are not always accurate. Who decides what is easy anyway? If you don't know the solution with absolute certainty (and can you really be absolutely certain without implementing it--and then you should probably just patch it yourself), I'm not sure what purpose it really serves. If it takes 3 hours of testing to sort out what is going on, does it mean I'm bad at coding because there was an 'Easy' label on there... I suppose it is basically saying--'this is not intended as a major refactoring project / algorithm design' type message. But that's a separate discussion!

**Comment by richardjgowers** [comment]
I pushed a commit to the #1115 PR that should make thing less cryptic:

```
/home/richard/miniconda2/envs/mdadev/lib/python2.7/site-packages/MDAnalysis/core/groups.pyc in write(self, filename, file_format, filenamefmt, **kwargs)
   1476             raise ValueError("No writer found for format: {}".format(filename))
   1477         else:
-> 1478             with writer(filename, **kwargs) as w:
   1479                 w.write(self.atoms)
   1480 

TypeError: __init__() got an unexpected keyword argument 'bogus'
```

It was because we were squashing the logic of choosing a Writer and initialising the Writer together

So in pseudocode

```python
# Before:
try:
    the_class = get_writer_for()
    the_instance = the_class()
except:
    pass

the_instance.write()

# Whereas now it is:
try:
    the_class = get_writer_for()
except:
    pass

with the_class() as the_instance:
    the_instance.write()
```
