### ISSUE TITLE
replace custom ProgressMeter with tqdm

### ISSUE THREAD

**Issue by jbarnoud** [MDAnalysis/mdanalysis#928]
EDIT (@orbeckst): Based on the discussion in this issue we decided to replace our `lib.util.ProgressMeter` with [tqdm](https://github.com/tqdm/tqdm). Use this issue for discussion to refine this idea.

----
The progress bar could give an estimate of when the calculation is going to be done. This is reassuring for the end user, and allows to plan other things during long calculation (or to know when to come back from a coffee break).

This is easily achievable by keeping track of the time elapsed between two calls of the update method as we know how many frames remain to be analyzed.

It can be misleading for analyses that need to iterate several time through the trajectory, or that have a very long `_conclude` method. But the current progress bar is misleading already.

**Comment by orbeckst** [comment]
Instead of calculating time between two calls I would keep track of the time since the start because that should improve your estimate for the average time per iteration and thus improve your extrapolated ETC (estimated time to completion).

**Comment by kain88-de** [comment]
Have a look in the code of pyprind. I use the package to have long verbose views and it has a good ETC estimate.

**Comment by orbeckst** [comment]
As discussed in PR #960 (https://github.com/MDAnalysis/mdanalysis/pull/960#issuecomment-484962749 and following comments) we want to transition to using [tqdm](https://tqdm.github.io/).

There are some caveats regarding use in Jupyter notebooks (https://github.com/MDAnalysis/mdanalysis/pull/960#issuecomment-484990143) but overall everyone is happy with the provided functionality and we would be ok adding it as a core dependency.

Note that we need to
- deprecate `lib.log.ProgressMeter` (for anyone who has been using it in their own code) and remove in 1.0
- replace internal use of `ProgressMeter` with a new version based on `tqdm.tqdm()`.

Perhaps we can simply derive our own class from [tqdm.tqdm](https://tqdm.github.io/docs/tqdm/) with our default settings, like `lib.log.ProgressReporter` or `ProgressBar`
```python
import tqdm
class ProgressBar(tqdm.tqdm):
   def __init__(self, *args, **kwargs):
          verbose = kwargs.pop('verbose', True)
          # disable: Whether to disable the entire progressbar wrapper [default: False]. 
          # If set to None, disable on non-TTY.
          kwargs['disable'] = None if verbose else True
          super(ProgressBar, self).__init__(*args, **kwargs)
```
and then use as
```python
from ..lib.log import ProgressBar

for ts in ProgressBar(u.trajectory[start:stop:step], verbose=verbose):
      analyze(ts)
```

It should cut down on code because we don't need manual status updates such as the `pm.echo()`.

**Comment by orbeckst** [comment]
There is probably a way to switch to the fancy GUI version [tqdm.tqdm_gui](https://tqdm.github.io/docs/tqdm_gui/) (for notebooks) but I haven't looked into this at all.
