### ISSUE TITLE
iter_as_aux does not work as expected

### ISSUE THREAD

**Issue by jbarnoud** [MDAnalysis/mdanalysis#951]
This may be me doing something wrong, especially as the tests pass and as I do not see the issue in the code. But with the following example, I do not get the expected behavior:

```python
In [1]: import MDAnalysis as mda

In [2]: from MDAnalysis.tests.datafiles import PSF, DCD, AUX_XVG_LOWF

In [3]: u = mda.Universe(PSF, DCD)

In [4]: u.trajectory.add_auxiliary('low', AUX_XVG_LOWF, dt=2)

In [5]: u.trajectory.dt
Out[5]: 0.9999999119200186

In [6]: a = u.trajectory.iter_as_aux('low')
In [10]: for ts in a:
    print ts.frame, ts.time
   ....:     
1 0.99999991192
2 1.99999982384
3 2.99999973576
```

Ping @fiona-naughton 

### Expected behaviour

The visited frames are 0, 2, and 4

### Actual behaviour

The visited frames are 1, 2, and 3

### Currently version of MDAnalysis:
0.15.1-dev0  8f803a4

**Comment by fiona-naughton** [comment]
The xvg reader assumes it can read time from the first column by default, so it ends up ignoring the input `dt`; hopefully this is normally a reasonable assumption (though it might be better to leave the default as not reading time from the file?) but the test xvg just has one data column - so it's reading the step times as [1, 2, 4] instead of using dt=2 to get [0, 2, 4].

Getting it not to read time from the time by setting `time_selector` to `None` from the file works as expected:

```Python
>>> import MDAnalysis as mda
>>> from MDAnalysis.tests.datafiles import PSF, DCD, AUX_XVG_LOWF
>>> u = mda.Universe(PSF, DCD)
>>> u.trajectory.add_auxiliary('low', AUX_XVG_LOWF, dt=2, time_selector=None)
>>> a = u.trajectory.iter_as_aux('low')
>>> for ts in a:
...   print ts.frame, ts.time
... 
0 0.0
2 1.99999982384
4 3.99999964768
```

(It was matching to frames 1, 2, 3 rather than 1, 2, 4 because it's also assuming constant dt by default - which gets set to 1 based on the first two steps; the value from the file is used for the time stored in the auxiliary reader (so 4ps for step 2) but the iter_as_aux ends up calculating time from dt  and step number as 3ps instead; I should probably add something in to try and catch that in case it comes up elsewhere....)

**Comment by jbarnoud** [comment]
Thank you. So it was indeed not a bug: I was doing it wrong.
