### ISSUE TITLE
Reduce coveralls flood?

### ISSUE THREAD

**Issue by jbarnoud** [MDAnalysis/mdanalysis#955]
Currently, coveralls tells us about coverage change in PR using comments. This generates a lot of unhelpful comments.

It is now possible to configure coveralls to use the status API in the same fashion as travis or quantify code. Because we do not want a big red cross attached to a PR because of a minor drop of coverage, it is also possible to set a threshold of coverage decrease before failure.

Should we setup coveralls to use the status API rather than comments? What threshold should we use?

**Comment by richardjgowers** [comment]
It's kind of annoying yes.  I think one of the reasons why it fluctuates is because we're using random numbers in the transformations tests, which end up going down slightly different code paths.  If we fixed this then the comments would be a lot more useful.

**Comment by mnmelo** [comment]
Still, I vote for the conciseness of having it in the status window. As for a threshold, 0.5% seems to me to be a good marker. This might need to be lowered as the size of the code base increases.

**Comment by orbeckst** [comment]
I'd also prefer it in the status window instead of a comment. I don't really see any downsides.

If –0.5% drop is what we see due to random numbers then use it. But 0.5% is already a pretty big deal (I was very, very happy when I got coverage up by 1%...). I would err on the conservative/restrictive side for the tolerance. 

In any case, can someone go ahead and make the changes. Start with 0.5% tolerance if we don't have any better numbers and we can always adjust if necessary.

**Comment by mnmelo** [comment]
Hmm, I guess you're right, @orbeckst, that 0.5% might be too much. Now that you bring it up I think I'd rather have the opposite: to start with a tight threshold (which gives us more failures but reminds us to adjust it), rather than the opposite, which is to have a too loose threshold that we'll forget to tighten because tests are always green.

In addition coveralls also has a total-coverage threshold, below which we always fail. I'd say something round like 80% sounds good right now. We can then step it up by 5% or so. It is also a nice way to set coverage goals for ourselves (@orbeckst bumps the threshold to 85% and opens an issue "85% coverage marathon!").

**Comment by orbeckst** [comment]
80% as the lower boundary sounds good. I can tell you that getting the green marker back for 90% will feel VERY satisfying. 

As an aside: when I talked to Enthought folks at Scipy over testing and mentioned half-apologetically that we are climbing back towards 90% they were impressed. Apparently, for contract work a coverage of 70% or so is often deemed acceptable. So we are doing not too badly but of course we know that we need high coverage to sustain our liberal open source development model while also ensuring that we can trust the code for our own work. 

--
Oliver Beckstein
email: orbeckst@gmail.com


> Am Aug 26, 2016 um 4:43 schrieb mnmelo <notifications@github.com>:
> In addition coveralls also has a total-coverage threshold, below which we always fail. I'd say something round like 80% sounds good right now. We can then step it up by 5% or so. It is also a nice way to set coverage goals for ourselves (@orbeckst bumps the threshold to 85% and opens an issue "85% coverage marathon!").
>

**Comment by mnmelo** [comment]
Ok, with #958 out of the way (via @richardjgowers' #961) I think we can be more stringent with the failure threshold. More precisely, we should aim for a loss of coverage no greater than **0.0217%**. Details below.

On the less technical/more pragmatical side I'm not sure if this value is suitable at all. Anyway, as discussed above, we can always start strict and relax as we go.

The stats
----------

From [coveralls.io](coveralls.io): as of the last [build](https://coveralls.io/builds/7677318) we have 13722 relevant lines in our code base (of which 11573 are covered). If we compare to when we [started tracking](https://coveralls.io/builds/5562896) the `analysis` module, we're up 999 relevant lines, from 12723. There were roughly 47 PR merges since ("roughly" because I can't easily identify the squashed merges as such from the log...). This gives an average 21.2 extra relevant lines per merge.

Now, if we want to enforce contributions of at-least-commercial-grade coverage (70%, as per @orbeckst's findings), of those 21.2 lines 14.9 must be covered. With the current code base size, having that minimal coverage would cause a drop in global coverage of... 0.0217%

**Comment by orbeckst** [comment]
I love @mnmelo's scientific approach. Therefore, 0.0217% looks like a great number to use.

(I also love the fact that here "research-grade" is defined as "better than commercial-grade" ;-) ).

**Comment by mnmelo** [comment]
Ok, all that's needed now is for whoever added MDAnalysis to coveralls to go there and log out / log in. This is needed so that coveralls prompts for the extra Github permission to post to commit status boxes. Was that you, @orbeckst?

**Comment by orbeckst** [comment]
I just logged out, logged in, logged in. Not sure if anything happened.

Is there a way to add someone else to a coveralls.io account?

> On 30 Aug, 2016, at 17:53, mnmelo <notifications@github.com> wrote:
> 
> Ok, all that's needed now is for whoever added MDAnalysis to coveralls to go there and log out / log in. This is needed so that coveralls prompts for the extra Github permission to post to commit status boxes. Was that you, @orbeckst?

--
Oliver Beckstein * orbeckst@gmx.net
skype: orbeckst  * orbeckst@gmail.com

**Comment by mnmelo** [comment]
Not sure. I guess not, from the looks of [this issue](https://github.com/neovim/neovim/issues/1949) where they had to centrally reassign the owner.

**Comment by richardjgowers** [comment]
I opened #966 to see if coveralls rejects it now.  WRT who signed us up for coveralls, it was probably either me or @dotsdl

**Comment by mnmelo** [comment]
Then as I understand, if you (or @dotsdl, whoever actually did it) sign out then back in at coveralls.io, an extra permission request should pop up. This because they only implemented the commit status feature after we signed up MDAnalysis there, and that specific permission wasn't asked for then.

**Comment by richardjgowers** [comment]
Hmm, must be @dotsdl then, I didn't get anything

**Comment by mnmelo** [comment]
Yup, let's hope that's it. BTW, the lack of comments is ok (I switched that feature off in coveralls), but there should have been the test pass/failure mark in the commit status.

**Comment by orbeckst** [comment]
## Coveralls settings

I looked at the [settings for MDAnalysis on coveralls](https://coveralls.io/github/MDAnalysis/mdanalysis/settings) and *Use Status API* is enabled as well as the other settings – I assume that @mnmelo was able to change these settings. See screen shot

![coveralls_mda_settings](https://cloud.githubusercontent.com/assets/237980/18256358/393fb29c-7369-11e6-859b-bf35179c18b5.jpg)

I have no idea how to grant additional privileges and I can't remember who originally set up our coveralls account – it might have been me but I logged in and out and was never asked for more permissions. Did @dotsdl try since https://github.com/MDAnalysis/mdanalysis/issues/955#issuecomment-243760738 ?

## GitHub OAuth permissions for Coveralls
I looked at the specific Coveralls permissions on Github] and it may access the commit status – actually, that is from my @orbeckst account under *Personal settings/OAuth applications: Authorized applications* so I suppose I was the one who added it.

![github-orbeckst-coveralls-permissions](https://cloud.githubusercontent.com/assets/237980/18256445/5c27a55c-736a-11e6-9410-1f0ddc7224d5.jpg)

**Comment by dotsdl** [comment]
I just re-logged in, and the page asking for my GitHub credentials did ask for more permissions. Did this work?

**Comment by richardjgowers** [comment]
That sounds like what needed to happen iirc

**Comment by orbeckst** [comment]
Ah crap... my screen shot shows the Coveralls repo token. I am pretty sure that this should *not* be in the clear. Sorry. I can undisplay the image but it's uploaded and compromised.

Can someone please regenerate the token and make everything else work? I am not sure where the new token has to be put.

**Comment by dotsdl** [comment]
@orbeckst I don't believe I set this up (which is all very confusing to me), so I'm not sure exactly what to do. Where do go to get to the settings you screenshotted above? I can't find it for the life of me.

**Comment by orbeckst** [comment]
The coveralls screen shot comes from https://coveralls.io/github/MDAnalysis/mdanalysis/settings – go to https://coveralls.io/github/MDAnalysis/mdanalysis and click on *Settings* in a menu on the left hand site (at least for me).

The GitHub screenshot is from my Settings -> OAuth applications page: https://github.com/settings/applications

I'll open an issue to change the coveralls repo token. Should have done it right away.

**Comment by dotsdl** [comment]
@orbeckst yeah the same coveralls settings link doesn't show me any of that, so I guess I don't have those kind of permissions? It's all so confusing.

**Comment by mnmelo** [comment]
So... as per @richardjgowers' findings (#972) we still can't get API statuses from coveralls (commit comments work just fine as before; see #973).

Perhaps @dotsdl just needs to log out and back in again, now that the token has been changed (#971). But maybe the coveralls repo just got confused with all this back-and-forth...

Perhaps we could ask @nickmerwin to take a look if we're doing it right, and to see if there's a way to add more people with this kind of configuration permissions?

**Comment by nickmerwin** [comment]
Hi @mnmelo, it appears @richardjgowers's Coveralls account no longer shows this repo as write accessible, and since he added the repo, we're using his access token to post the status, which is 404'ing.

To fix I could either grant ownership to another user, or @richardjgowers could update his GH settings to allow Coveralls to see access to the MDAnalysis org.

**Comment by orbeckst** [comment]
Hi @nickmerwin, thanks for helping out.

If @richardjgowers agrees then transfer ownership of the coveralls account to me, @orbeckst. We are already using my token for travis and there's a fair chance that I will be sticking around for a while...

**Comment by richardjgowers** [comment]
@nickmerwin yeah if you could transfer my crown to @orbeckst that'd be awesome

**Comment by nickmerwin** [comment]
@richardjgowers @orbeckst done!

**Comment by orbeckst** [comment]
Thanks @nickmerwin ; I logged out and in on coveralls.io but wasn't really asked to update any permissions.

@richardjgowers maybe try again if the GitHub API is now being triggered?

**Comment by mnmelo** [comment]
Ok, we finally got the cool API integration (thanks @nickmerwin!). You can see it in action in the status of any recent PR.

It'll be cool to test the limits for failure. @richardjgowers, do you still have that `coveralls_test` branch around to open a PR from?

And finally, I can see from #976 that we're breaching the 85% mark. Should we raise the absolute bar to 85%, then?

**Comment by mnmelo** [comment]
(Actually, @richardjgowers, github makes it very easy to revive branches. Just opened a new test PR #980)
