### ISSUE TITLE
Nomenclature of submodules

### ISSUE THREAD

**Issue by richardjgowers** [MDAnalysis/mdanalysis#957]
So currently we have `MDAnalysis.coordinates` which contains `Reader`s and `MDAnalysis.topology` which (mostly) contains `Parser`s.

These are both a little confusing, `coordinates` doesn't have anything to help with coordinates (like `distance_array`), `topology` doesn't have anything that helps with topology things.

I propose we move:
 - `coordinates` to `io.readers`
 - `topology` to `io.parsers`
 - `topology` then contains things related to the topology such as guessers (esp. with 363 system)

**Comment by mnmelo** [comment]
Sounds sane. +1

**Comment by jbarnoud** [comment]
While I see the benefit of the proposal, I have a small issue with exposing readers and parsers only under the name readers and parsers. When I started contributing, I had no clue what the difference between a parser and a reader was. Yet, it was obvious what was in the coordinate or topology directories.

My objection is a small  and shy one, though.  Now that I now the code base, I prefer what is proposed; I just do not find that naming scheme very welcoming.

**Comment by orbeckst** [comment]
I am not a huge fan of this proposal because readers and parsers are too generic. You could call a topology parser a reader and no-one would object. I think in this case it is important to know what the data are that you are processing and these are clearly topologies or coordinate trajectories. With the new auxiliary module, we now have a third type of reader.

Additionally, renaming everything will produce a lot of unnecessary pain.

**Comment by orbeckst** [comment]
I do take your point that, for instance, guessers should live somewhere sane. Even if it's not 100% orthogonal, we could just do `topology.guessers.{masses,charges,...}` and it would still make sense.

Even though I said

> Additionally, renaming everything will produce a lot of unnecessary pain.

this *might* not be quite as bad because in fact most people probably don't deal with the readers/writers/parsers directly. Perhaps something like
```
topology/
               io/
                   PSF
                   PDB
                   base
               guessers/
                   masses
                   charges
coordinates/
               io/
                   DCD
                   PDB
                   base
```
provides sufficient organizational structure?

(One thing with open source projects is that both users *and* developers have to be happy so if @MDAnalysis/coredevs  want to re-organize the packae I am not going to stand in the way — I just see myself often as the voice of the users who are not involved at this stage but have to deal with it later.)

**Comment by richardjgowers** [comment]
Ok I'm happy to keep things as-is, if it ain't broke don't fix it!
